### ISSUE TITLE
site bug

### ISSUE THREAD

**Issue by reslear** [ts-rest/ts-rest#100]
<img width="1691" alt="Screenshot 2022-12-13 at 20 19 11" src="https://user-images.githubusercontent.com/12596485/207425147-bcc2744b-8917-4132-84cc-e0314ceecf11.png">

1710x1112

but fixe is: 
<img width="1014" alt="Screenshot 2022-12-13 at 20 24 56" src="https://user-images.githubusercontent.com/12596485/207426308-99d48670-3605-40ba-8e9c-b5239a905c0c.png">

**Comment by oliverbutler** [comment]
Hey @reslear, thanks for the report (and the hint!) I'll take a look and get this shipped ASAP 🙏

**Comment by oliverbutler** [comment]
Fixed in rebrand and move to Vercel, thanks @reslear !
