### ISSUE TITLE
Document *how* ts-rest works

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#109]
I want to better explain the mental model, with some diagrams.

## Contract `initContract` from @ts-rest/core
- Defined only on the front end, for an uncontrollable API
- Defined in a shared lib, used by both front and backend
- Defined by a shared npm module, for an internal or external API

^ To clarify and advertise that it isn't a full stack, all-or-nothing tech, it can be incrementally adopted and has no backend requirements.

## Base client `initClient` from @ts-rest/core
- Is a simple wrapper around fetch, nothing more, it has a type-safe wrapper around it but the implementation is SERIOUSLY tiny
- Can be used for _any_ framework, not restricted to @tanstack adapters 

^ To clarify that you can use any framework, no limits. (#71 )

## Other libs
- Adapters for first-class support with other libs, NOT REQUIRED
- 
^ To clarify that you can use ts-rest even without a supported adapter e.g. Vue (#71 )

**Comment by michaelangrivera** [comment]
I also think a great addition to the docs is having an API reference. 

A good example: https://firebase.google.com/docs/reference/js

Having that much detail might be overkill, but overall cold help street cred.

**Comment by oliverbutler** [comment]
Relevant to #132
