### ISSUE TITLE
Accessing Request object when using @ApiDecorator

### ISSUE THREAD

**Issue by ChrisKG32** [ts-rest/ts-rest#120]
Hello, I have been using @ts-rest with NestJS and enjoying it so far, however, documentation is sparse.

It's extremely common to need access to request headers and metadata in controllers, however, I don't see any way to achieve that when using @ts-rest. The `@Api` only returns the parsed params, query, and body, but the `@Api` decorator forces you to use `@ApiDecorator` and both of those require you to extend the `ControllerShape` of the Contract. 

How can we access the full request in the controller when using `@ts-rest` with NestJS?

**Comment by Gabrola** [comment]
You can still add extra arguments to your request handlers and decorate those with NestJS's own decorators.

```typescript
async getPost(
  @ApiDecorator() { params: { id } }: RouteShape['getPost'],
  @Req() req: Request
) {}
```

**Comment by michaelangrivera** [comment]
You also don't need to extend the `ControllerShape` anymore, see this this documentation https://ts-rest.com/docs/nest#response-return-type-safety.

**Comment by ChrisKG32** [comment]
Ah thanks guys this clears a lot up.
