### ISSUE TITLE
Passing Error object directly to HttpException is deprecated (NestJS)

### ISSUE THREAD

**Issue by Gabrola** [ts-rest/ts-rest#122]
Passing the Zod validation error directly to the `BadRequestException` constructor is now triggering this warning

`DEPRECATED! Passing the error cause as the first argument to HttpException constructor is deprecated. You should use the "options" parameter instead: new HttpException("message", 400, { cause: new Error("Some Error") })`

**Comment by michaelangrivera** [comment]
How are you using `HttpException` if you don't mind me asking? Right now I'm avoiding using that and just returning the status/response where I'd otherwise throw an HttpException. Ex:

```
    } catch (error) {
      const errorMsg = `Error querying DB for user activity logs`
      this.logger.error({
        message: errorMsg,
        data: { ...params, error: JSON.stringify(error) },
      })
      return { status: HttpStatus.INTERNAL_SERVER_ERROR, body: { error: errorMsg } }
    }
```

**Comment by Gabrola** [comment]
We're not using `HttpException` or ts-rest yet for error type safety.
