### ISSUE TITLE
Importing @ts-rest/express in a monorepo causes module not found error

### ISSUE THREAD

**Issue by stingrayfunk** [ts-rest/ts-rest#125]
Using `@ts-rest/express` 3.12.1.
Node 14.19.3
React 17.0.1
Using Craco 7.0.0 to override CRA Webpack configs

I have a Lerna monorepo. I have a React (CRA) app in one workspace called Navigator, which imports a TS file from another workspace (Arachne). That TS file in Arachne imports `@ts-rest/express`. However, when I load the React app, I get the following error:

```
Failed to compile.

Module not found: Error: Package path . is not exported from package /Users/seanmcgowan/Dev/CancerIQ/umbrella2/node_modules/@ts-rest/express (see exports field in /Users/seanmcgowan/Dev/CancerIQ/umbrella2/node_modules/@ts-rest/express/package.json)
ERROR in ../arachne/src/middleware/ts-rest.ts 6:0-46
Module not found: Error: Package path . is not exported from package /Users/seanmcgowan/Dev/CancerIQ/umbrella2/node_modules/@ts-rest/express (see exports field in /Users/seanmcgowan/Dev/CancerIQ/umbrella2/node_modules/@ts-rest/express/package.json)
```

I've tried updating my Webpack configuration to accommodate the module mapping, e.g.

```
  resolve: {
    alias: {
      "@ts-rest/express": path.resolve(
        __dirname,
        "node_modules/@ts-rest/express/src"
      ),
    },
  },
```

But it hasn't worked. Is there a problem with `@ts-rest/express` not supporting Monorepos, or am I doing something wrong? Any help would be greatly appreciated.

**Comment by oliverbutler** [comment]
hey! before we try and fix the issue here, to clarify, you're trying to import @ts-rest/express from a shared library? 🧐

just checking because normally i'd expect you'd import the contract, built using @ts-rest/core from the shared module not the backend packages!

**Comment by stingrayfunk** [comment]
Hey! Thanks for the prompt reply. So from your question, I realised my mistake. I was placing my server/express code in the same file as my API contract, and trying to import that file into the React app. Once I split out the server code, it worked. Thanks for your help 🙏

**Comment by oliverbutler** [comment]
Amazing! Great to know. If having the contract alongside your implementation is something you'd like, and if we can't offer that right now please open a new feature request issue :)
