### ISSUE TITLE
Expects QueryClientProvider to be used when using react-query

### ISSUE THREAD

**Issue by stingrayfunk** [ts-rest/ts-rest#126]
React 17.0.1
@ts-rest/core@3.12.1
@ts-rest/react-query@3.12.1
@tanstack/react-query@4.16.1

My code follows closely the TS-Rest React Query example provided in the docs:

```
import { initQueryClient } from "@ts-rest/react-query";
import { apiContract } from "arachne/src/middleware/ts-rest-contract";

const client = initQueryClient(apiContract, {
  baseUrl: "http://localhost:4000",
  baseHeaders: {},
});

export function App(): JSX.Element {
  const { data, isLoading } = client.getFoo.useQuery([]);

  console.log("data = ", data);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return <div>Result: {data}</div>;
}
```

However, I get this error in the browser consoloe:

```
QueryClientProvider.tsx:48 Uncaught Error: No QueryClient set, use QueryClientProvider to set one
    at useQueryClient (QueryClientProvider.tsx:48:1)
    at useBaseQuery (useBaseQuery.ts:33:1)
    at useQuery (useQuery.ts:139:1)
    at Proxy.<anonymous> (index.js:15:1)
    at App (index.tsx:10:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
```

I've added TanStack's React Query to my package.json because `@ts-rest/react-query` seems to expect it as a peer dependencies (though I couldn't see that mentioned in TS-Rest docs).

Can someone please help? I shouldn't need to use `QueryClientProvider` directly from TanStack's react-query if I'm using TS-Rest, right?

**Comment by oliverbutler** [comment]
Hey @stingrayfunk! I think the docs on this area need some love, have you followed @tanstack's guide for setting up useQuery? Have you got a `<QueryClientProvider>` wrapping your `<App>` component somewhere in the project?

**Comment by stingrayfunk** [comment]
I followed the TS-Rest docs, which uses the `initQueryClient()` method to create a query client, as in my example above.

The TanStack react-query docs say to create a new `QueryClient()` instance and pass that to the `<QueryClientProvider>` that is wrapped around my app.

So I'm confused. Do I use TanStack's `new QueryClient()` or TS-Rest's `initQueryClient()` to create the client? If I pass the client created by `initQueryClient()` to the provider, like in my code:

```
import { initQueryClient } from "@ts-rest/react-query";
import { QueryClientProvider } from "@tanstack/react-query";
import { apiContract } from "arachne/src/middleware/ts-rest-contract";

const client = initQueryClient(apiContract, {
  baseUrl: "http://localhost:4000",
  baseHeaders: {},
});

function Blah() {
  const { data, isLoading } = client.getFoo.useQuery([]);

  console.log("data = ", data);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return <div>Result: {data}</div>;
}

export function App(): JSX.Element {
  return (
    <QueryClientProvider client={client}>
      <Blah />
    </QueryClientProvider>
  );
}

```

I get the following TypeScript error on the `client` prop being passed to the provider:

<img width="787" alt="Screenshot 2023-01-21 at 12 26 34 pm" src="https://user-images.githubusercontent.com/1764083/213845077-2037f49a-1da7-4de2-a894-67635b80e19f.png">

Which looks to be saying that `client` isn't an instance of `QueryClient` when it should be.

Would really appreciate if you could clarify how I can use TS-Rest with TanStack's React Query, thanks again 🙏

**Comment by oliverbutler** [comment]
Hey again, this is completely on us, and knowing this is an area of confusion we can update the docs.

I've drawn a big diagram to explain the relationship between ts-rest and react-query a little more visually.

Orange is react-query bits, purple is ts-rest bits!

<img width="1343" alt="Screenshot 2023-01-21 at 11 44 51" src="https://user-images.githubusercontent.com/47489826/213865419-a1c053a9-55dd-41e2-bfac-4d680d032aee.png">

The summary is that you still need to initialise a query client with `client = new QueryClient()` and pass that to the provider, that provider will then be consumed by both "standard" react-query queries and ts-rest queries.

Remember that a ts-rest api.useQuery calls a normal useQuery under the hoot, it's just a type safe wrapper around it

**Comment by oliverbutler** [comment]
Also clone and play with the next example maybe https://github.com/ts-rest/example-next

it might help understanding!

**Comment by stingrayfunk** [comment]
This was very helpful, it works now. Thank you so much @oliverbutler!

**Comment by kennykingdev** [comment]
@oliverbutler
It might be helpful for new users to have this issue reopened until docs are updated to make this clear.  I ran into this myself and could have saved quite a bit of time if this were easier to find.

**Comment by telmogoncalves** [comment]
Somehow I'm still having this issue:

**pages/_app.tsx**

```tsx
import { QueryClient, QueryClientProvider } from 'react-query'


// ...
let queryClient = new QueryClient()

<QueryClientProvider client={queryClient}>
  <Component />
</QueryClientProvider>
```

**api/client.ts**

```ts
import { ApiFetcherArgs, tsRestFetchApi } from '@ts-rest/core'
import { initQueryClient } from '@ts-rest/react-query'

import { contract } from './contract'

export const api = initQueryClient(contract, {
  baseUrl: `${process.env.NEXT_PUBLIC_API_ENDPOINT}/api`,
  baseHeaders: {
    'Content-Type': 'application/json',
    'Key-Inflection': 'camel',
  },
  api: async (args: ApiFetcherArgs) => {
    args.headers = {
      ...args.headers,
      Authorization: `${localStorage.getItem('AUTH_TOKEN')}`,
    }

    return await tsRestFetchApi(args)
  },
})
```

**api/contract.ts**

```ts
import { initContract } from '@ts-rest/core'
import { z } from 'zod'

const c = initContract()

const CampaignSchema = z.object({
  publicId: z.string(),
  name: z.string(),
  status: z.enum(['draft', 'published']),
  icon: z.string().nullable(),
})

export const contract = c.router({
  campaigns: c.router({
    get: {
      method: 'GET',
      path: `/campaigns`,
      responses: {
        200: CampaignSchema.array(),
      },
      summary: 'Get a list of campaigns',
    },
  }),
})
```

**Comment by defguru** [comment]
I confirm that it is still happening, same as @telmogoncalves. Please reopen and provide updated instructions.

**Comment by Ryoto-kubo** [comment]
I have same problem

**Comment by ibash** [comment]
+1
