### ISSUE TITLE
Support useQueries in @ts-rest/react-query

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#127]
I just had a chat with a colleague who needed to use useQueries with react query.

I realised we don't support this! We support useQuery and useInfiniteQuery

Maybe we could use a proposed API like this? It closely reflects the RQ api.
![image](https://user-images.githubusercontent.com/47489826/213777404-865cb4b4-a40a-4e20-aa14-0d54c7a3531a.png)
![image](https://user-images.githubusercontent.com/47489826/213777429-7e4601da-beb2-4316-b2c7-269f5eb01b81.png)

**Comment by michaelangrivera** [comment]
LGTM, but the ts-rest api should stay as close to the react query API as possible imo. So something like:
```
api.posts.getPost.useQueries({ queries: [ { obj } ] })
```
