### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by stingrayfunk** [ts-rest/ts-rest#131]
I'm getting `'Proxy' is undefined` in IE11.

Would Polyfiling Proxy be the only obstacle to IE11 usage? Is there any plan to support IE11?

At my company, we've switched from tRPC to ts-rest in the hope that we can use it in IE11.

**Comment by stingrayfunk** [comment]
After adding [proxy-polyfill](https://www.npmjs.com/package/proxy-polyfill), the request object in the apiContract is undefined. So in my case, for this:

```
  const { data, isLoading } = apiClient.getFoo.useQuery([]);
```

The `getFoo` is `undefined`. Perhaps this means that Proxy was not poly-filled correctly? Any insights would be appreciated, thanks.

**Comment by oliverbutler** [comment]
I _think_ Proxy is the only aspect that won't support IE11

I've sadly never used proxy-polyfill, however from the docs you linked it should work fine with ts-rest. 

If you want to show me how you've configured the proxy ic an take a look, but otherwise the question might be best faced by the folks at the proxy :(

**Comment by stingrayfunk** [comment]
Thanks Oliver. All I'm doing is importing the proxy polyfill as the first line in my client application, as per the Proxy polyfill usage docs.

```
import "proxy-polyfill";
```

I'm not using Proxy myself. I'm just trying to make sure `ts-rest`'s Proxy usage works as expected.

Is there any reason why you think `apiClient.getFoo` wouldn't be available?

No worries if not, I can try debugging it.

**Comment by oliverbutler** [comment]
Hmm, as a first step can you try make a proxy, yourself? To see if it works.

**Comment by stingrayfunk** [comment]
Yes, good idea Oliver. I created a Proxy:

```
export function App(): JSX.Element {
  useEffect(() => {
    function observe(o: any, callback: any) {
      return new Proxy(o, {
        set(target, property, value) {
          callback(property, value);
          target[property] = value;
        },
      });
    }

    const x = { name: "BB-8" };
    const p = observe(x, (property: any, value: any) =>
      console.info(property, value)
    );
    p.name = "BB-9";
  }, []);
  return <div>Hello</div>;
}
```

And the console.info is output with `name BB-9` in IE11, which is correct. No errors are output.

**Comment by stingrayfunk** [comment]
Also, in my efforts to debug ts-rest in my app, I put a console.log in the `initQueryClient()` method in `node_modules/@ts-rest/react-query/index.js` but it was never output. I also restarted my React app but still don't see that log. There's also an `index.cjs` there too. I tried adding the log to the same function in there but I don't see it. Do you know why this might be?

**Comment by michaelangrivera** [comment]
> Also, in my efforts to debug ts-rest in my app, I put a console.log in the `initQueryClient()` method in `node_modules/@ts-rest/react-query/index.js` but it was never output. I also restarted my React app but still don't see that log. There's also an `index.cjs` there too. I tried adding the log to the same function in there but I don't see it. Do you know why this might be?

Just to clarify, where did you run into `proxy` being undefined? Did you observe this error during `initQueryClient`?

**Comment by stingrayfunk** [comment]
Yes, let me clarify @michaelangrivera.

In IE11, if I do not use the Proxy polyfill, yes I get `Proxy is undefined` when I do:

```
const apiClient = initQueryClient(apiContract, {
  baseUrl: "http://localhost:4000",
  baseHeaders: {},
});
```

If I just import `initQueryClient` without calling it, I don't get the Proxy undefined error.

If I add the Proxy polyfill, I get an error at the point where I try to access an API on the `apiContract`. This is my code:

```
import { initQueryClient } from "@ts-rest/react-query";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { apiContract } from "arachne/src/middleware/ts-rest-contract";

const apiClient = initQueryClient(apiContract, {
  baseUrl: "http://localhost:4000",
  baseHeaders: {},
});

const queryClient = new QueryClient();

function Blah() {
  const { data, isLoading } = apiClient.getFoo.useQuery([]);

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return <div>Result: {data?.body.message}</div>;
}

export function App(): JSX.Element {
  return (
    <QueryClientProvider client={queryClient}>
      <Blah />
    </QueryClientProvider>
  );
}

```

So `apiClient.getFoo` is undefined.

This is the IE11 error:

<img width="641" alt="Screenshot 2023-01-22 at 11 33 11 am" src="https://user-images.githubusercontent.com/1764083/213900782-042a6663-2cd7-48c9-9131-65a249e6372d.png">

It is line 104 in the bundle here:

<img width="663" alt="Screenshot 2023-01-22 at 11 33 57 am" src="https://user-images.githubusercontent.com/1764083/213900798-a32b454f-840c-4401-8897-4cde96ddcf46.png">

Does that clarify things? My comment that you replied to was just me asking how I could debug ts-rest in the node_modules with console logs. It's not my main question. I'm just trying to get ts-rest working in IE11, and I'd really appreciate any help you might have.

**Comment by stingrayfunk** [comment]
After using the Proxy polyfill in Chrome, I get the same error. I've confirmed that with the Polyfill, `new Proxy()` is returning `{}`, hence getting `getFoo is undefined` when doing `apiClient.getFoo.useQuery([])`. Why it is doing this, I don't yet know.

**Comment by stingrayfunk** [comment]
FYI, I've asked the question: https://github.com/GoogleChrome/proxy-polyfill/issues/83

**Comment by michaelangrivera** [comment]
> Yes, let me clarify @michaelangrivera.
> 
> In IE11, if I do not use the Proxy polyfill, yes I get `Proxy is undefined` when I do:
> 
> ```
> const apiClient = initQueryClient(apiContract, {
>   baseUrl: "http://localhost:4000",
>   baseHeaders: {},
> });
> ```
> 
> If I just import `initQueryClient` without calling it, I don't get the Proxy undefined error.
> 
> If I add the Proxy polyfill, I get an error at the point where I try to access an API on the `apiContract`. This is my code:
> 
> ```
> import { initQueryClient } from "@ts-rest/react-query";
> import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
> import { apiContract } from "arachne/src/middleware/ts-rest-contract";
> 
> const apiClient = initQueryClient(apiContract, {
>   baseUrl: "http://localhost:4000",
>   baseHeaders: {},
> });
> 
> const queryClient = new QueryClient();
> 
> function Blah() {
>   const { data, isLoading } = apiClient.getFoo.useQuery([]);
> 
>   if (isLoading) {
>     return <div>Loading...</div>;
>   }
> 
>   return <div>Result: {data?.body.message}</div>;
> }
> 
> export function App(): JSX.Element {
>   return (
>     <QueryClientProvider client={queryClient}>
>       <Blah />
>     </QueryClientProvider>
>   );
> }
> ```
> 
> So `apiClient.getFoo` is undefined.
> 
> This is the IE11 error:
> 
> <img alt="Screenshot 2023-01-22 at 11 33 11 am" width="641" src="https://user-images.githubusercontent.com/1764083/213900782-042a6663-2cd7-48c9-9131-65a249e6372d.png">
> 
> It is line 104 in the bundle here:
> 
> <img alt="Screenshot 2023-01-22 at 11 33 57 am" width="663" src="https://user-images.githubusercontent.com/1764083/213900798-a32b454f-840c-4401-8897-4cde96ddcf46.png">
> 
> Does that clarify things? My comment that you replied to was just me asking how I could debug ts-rest in the node_modules with console logs. It's not my main question. I'm just trying to get ts-rest working in IE11, and I'd really appreciate any help you might have.

Can you log the entire `apiClient` object for me when you get a chance? I want to see if that object is there and accessible during runtime.

**Comment by stingrayfunk** [comment]
This is a log of `apiClient` from within the `Blah` component, just before the useQuery call:

<img width="368" alt="Screenshot 2023-01-22 at 10 32 12 pm" src="https://user-images.githubusercontent.com/1764083/213924314-410d4bda-ebae-4f95-9844-252239823790.png">

And for what it's worth, this is the definition:

```
export const apiContract = c.router({
  getFoo: {
    method: "GET",
    path: "/ts/foo",
    responses: {
      200: c.response<{ message: string }>(),
    },
    body: c.body<ResponseType>(),
    summary: "Example GET",
  },
});
```

**Comment by michaelangrivera** [comment]
@stingrayfunk Sorry to have you look more, but can you also now log `apiClient.getFoo` and also expand all the proptypes and properties of the object? I want to see the entire object. 

Also, have you added this to your app? https://github.com/facebook/create-react-app/tree/main/packages/react-app-polyfill

**Comment by stingrayfunk** [comment]
@michaelangrivera, when using the [Proxy polyfill](https://github.com/GoogleChrome/proxy-polyfill), `apiClient.getFoo` is undefined. This is the issue I'm facing. So I can't really give you the output for `getFoo`, unless you mean in Chrome where the polyfill is not used?

Yes, I'm using React App Polyfill. The first two lines of my client-side code are:

```
import "react-app-polyfill/ie11";
import "react-app-polyfill/stable";
```

**Comment by stingrayfunk** [comment]
I'm not sure if you guys will see this message now that the issue is closed, but...

@Gabrola , thank you so so much for fixing this. I've confirmed it works in IE11. It has unblocked us to use this awesome tool. Much appreciated 🙏 

@oliverbutler and @michaelangrivera thanks so much for your responses and help along the way!
