### ISSUE TITLE
Capability to send non-JSON responses

### ISSUE THREAD

**Issue by Gabrola** [ts-rest/ts-rest#180]
The express and next server-side implementations do not allow the request handlers to return anything other than JSON since we are returning the response using `res.status(statusCode).json(body)`

There is no way to prevent this behavior so we'd need to expose the response object to the request handler functions, in addition, we need to define a method to prevent the default behavior of calling `.json` on the response object.

Might need to re-visit how we can define these responses in the contract if possible.

This problem doesn't exist in the NestJS implementation since we do a `res.status(...); return body;` in the interceptor, and the handler can access the response object by injecting it using the `@Res` decorator. Will need to double check that calling `res.status(...);` does not cause problems in case the status and/or response body was already sent manually by the handler.

**Comment by gbleu** [comment]
Exposing the response would also help migrating existing express api

**Comment by Gabrola** [comment]
Response object will be exposed in #232
