### ISSUE TITLE
Search is broken on docs

### ISSUE THREAD

**Issue by wladiston** [ts-rest/ts-rest#201]
<img width="962" alt="Screenshot 2023-04-13 at 2 50 38 pm" src="https://user-images.githubusercontent.com/1843792/231843033-6bc177b2-52a6-48b7-a137-65abcb2d1e3e.png">

**Comment by Gabrola** [comment]
@oliverbutler we might need to trigger algolia to recrawl the website. Might be a good idea to use a github action to recrawl on deployments too.

**Comment by oliverbutler** [comment]
I'll take a look at this now!

**Comment by oliverbutler** [comment]
Thanks @wladiston ! i spotted the crawler got stuck so I unblocked it. All sorted!
