### ISSUE TITLE
How about Fastify support?

### ISSUE THREAD

**Issue by gustawdaniel** [ts-rest/ts-rest#217]
Now I can select backend

```
yarn add @ts-rest/nest @ts-rest/express
```

but I would like to type

```
yarn add @ts-rest/fastify
```

and use this awesome tool with https://www.fastify.io/

**Comment by NOT-HAL9000** [comment]
The project looks amazing but this is currently a deal breaker for me.

**Comment by gustawdaniel** [comment]
@NOT-HAL9000 I was thinking the same 2 days ago, but tried it with express and now I feel that it's not that bad how I expected. Developer Experience even without fastify was amazing.

**Comment by NOT-HAL9000** [comment]
@gustawdaniel The dx of ts-rest looks amazing, but moving away from fastify to express is not an option.

**Comment by oliverbutler** [comment]
As this is in high demand I'm going to look into this :)

**Comment by oliverbutler** [comment]
@tsanyqudsi @NOT-HAL9000 @gustawdaniel The fastify lib is deployed under version 3.24.0-rc.0 :) 

Also the PR #237 is open so this is your opportunity for feedback before we can't make breaking changes!

**Comment by NOT-HAL9000** [comment]
@oliverbutler Amazing! Thank you so much!
