### ISSUE TITLE
Expected number, received string - pathParams: z.object({ id: z.number() }) 

### ISSUE THREAD

**Issue by gustawdaniel** [ts-rest/ts-rest#218]
I know that in url I will have "id" that is number, not string. Eg.: `/user/5`. I typed:

```typescript
  getUser: {
    method: "GET",
    path: `/user/:id`,
    pathParams: z.object({ id: z.number() }),
    responses: {
      200: z.object({ name: z.string() }),
    },
    summary: "Get a user by id",
  },
```

but I recived:

```json
{
    "issues": [
        {
            "code": "invalid_type",
            "expected": "number",
            "message": "Expected number, received string",
            "path": [
                "id"
            ],
            "received": "string"
        }
    ],
    "name": "ZodError"
}
```

I would like to be able write that param in url is number, if it i string then convert it to number, if conversion failing then return error. But "5" can be easy converted to 5, and I would like to not see this error.

Do you know, how to fix it?

**Comment by gustawdaniel** [comment]
Fixed by

```
    pathParams: z.object({
      id: z.preprocess((val) => Number(val), z.number()),
    }),
```

thanks to @KATT

https://github.com/colinhacks/zod/discussions/1132

**Comment by Gabrola** [comment]
@gustawdaniel You can also use `z.coerce.number()` as it'll give you better typing and ensure that you also pass a number from the client side
