### ISSUE TITLE
Restrict returned status codes to those that are defined

### ISSUE THREAD

**Issue by gingermusketeer** [ts-rest/ts-rest#220]
Been using this library for a month or so and have really enjoyed it. Has been a dramatic improvement for the flow of work!

One gotcha that I  have run into a few times is checking the response status. At the moment all the documented HTTP statuses are considered possible in TS. Would you be open to restricting these to only the defined statuses?

For example if you defined 200 as the only response status then you don't need to check the status field. If you defined two then checking for one would narrow both code paths.

This could be achieved via a flag to raise exceptions for non defined statuses.

## Current state

```ts
const postsContact = c.router({
  update: {
    method: "PUT",
    path: "/posts/:postId",
    body: PostSchema,
    responses: {
      200: ResponseSchema,
    },
    summary: "Update post information",
  },
});
const tsRestClient = initClient(postsContact)
const response = await tsRestClient.posts.update({
  params: { postId },
  body,
});

if (response.status === 200) {
  return response.body;
}

throw new UnexpectedError("Failed to update post", {
  response,
});


```

##

**Comment by Gabrola** [comment]
Yeah, a "strict" mode has been something that has been requested previously. Should be possible!

**Comment by gingermusketeer** [comment]
@Gabrola I put up PR #228 to add a strict mode. Let me know what you think!
