### ISSUE TITLE
Expose response headers to clients

### ISSUE THREAD

**Issue by Gabrola** [ts-rest/ts-rest#221]

**Comment by Jwcode-uk** [comment]
Am I good to grab this? looks like a good first issue :)

**Comment by oliverbutler** [comment]
We could make headers optional in ApiFetcher - it'd mean any custom clients need to add it before headers propagate to the clients

But for users without custom client it'll work straight away!

**Comment by oliverbutler** [comment]
Honestly even with this quirk I'd reckon this would be a great feature.

**Comment by Gabrola** [comment]
Also it would be easier to find the instructions on how to un-break, now that we have github releases working again 😄

**Comment by oliverbutler** [comment]
I actually like this in this case - I also belive it's probably OK for us to have differing tolerances for breaking changes based on what features of ts-rest you use.

e.g. 
- anything that breaks at runtime (not type-level) is a major change
- anything that breaks a type (like this) for **custom clients** is a minor change
   - What this change falls under

**Comment by Jwcode-uk** [comment]
time to break some eggs 🍳

**Comment by oliverbutler** [comment]
@all-contributors please add @Jwcode-uk for code and docs
