### ISSUE TITLE
Consume `AbortSignal` from react query and forward to API fetcher

### ISSUE THREAD

**Issue by Gabrola** [ts-rest/ts-rest#222]

**Comment by michaelangrivera** [comment]
What's this about? 🤔

**Comment by Gabrola** [comment]
> What's this about? 🤔

Queries aren't canceling at the moment when they should https://tanstack.com/query/v4/docs/react/guides/query-cancellation
We need to forward the AbortSignal too in case of using a custom API fetcher

**Comment by michaelangrivera** [comment]
Ah gotcha! nice!
