### ISSUE TITLE
@ts-rest/react-query - `content-type: multipart/form-data` header not correctly set on multipart/form-data 

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#238]
It seems like we need to set the header manually to work for file uploads

On the below fetch API we add the headers for json, not for multipart

<img width="758" alt="Screenshot 2023-05-31 at 10 33 29" src="https://github.com/ts-rest/ts-rest/assets/47489826/3e793ee5-c286-453b-b2c1-216c7a0b289a">

**Comment by dml0031** [comment]
This appears to be happening again with react query v5. The content type header is being set to `application/json`
