### ISSUE TITLE
"The type of this node cannot be serialized..." typescript v4.8+ error when generating declarations 

### ISSUE THREAD

**Issue by adrienrn** [ts-rest/ts-rest#276]
I am logging this in case there's someone encountering the same error.

With typescript v4.8+ and @ts-rest/core v3.26.0 (and v3.26.0), I am getting the following error:

```
> tsc && vite build

vite v4.3.9 building for production...
✓ 2 modules transformed.
dist/index.es.js  8.10 kB │ gzip: 2.33 kB
dist/index.cjs.js  8.21 kB │ gzip: 2.38 kB

[vite:dts] Start generate declaration files...
src/index.ts:26:14 - error TS4118: The type of this node cannot be serialized because its property '[iterator]' cannot be serialized.

26 export const contract = c.router({
                ~~~~~~~~
src/index.ts:26:14 - error TS4118: The type of this node cannot be serialized because its property '[unscopables]' cannot be serialized.

26 export const contract = c.router({
                ~~~~~~~~
src/index.ts:36:14 - error TS4118: The type of this node cannot be serialized because its property '[iterator]' cannot be serialized.

36 export const client = initClient(contract, {
                ~~~~~~
src/index.ts:36:14 - error TS4118: The type of this node cannot be serialized because its property '[unscopables]' cannot be serialized.

36 export const client = initClient(contract, {
                ~~~~~~

✓ built in 463ms
[vite:dts] Declaration files built in 396ms.
```

It is tempting to blame `vite-plugin-dts` but this is not related as I am getting the same error running `tsc` directly (e.g. `tsc --noEmit false --declaration --emitDeclarationOnly`).

If I rollback to v4.7.4, the same command above works fine.

Looked into the ts-rest repository for a similar issue or a lead on the error itself without luck. I suspect something with symbols?

There's a [_similar_ issue related to stitches ans TS](https://stackoverflow.com/questions/73962388/typescript-styled-component-the-type-of-this-node-cannot-be-serialized-because) which put me on the tracks for the typescript rollback work-around but that's pretty much all I could find.

Hope that helps!

**Comment by Gabrola** [comment]
@adrienrn thank you for raising this issue! We're currently looking into this but you'd get a much faster response if you can include a reproducible repo or codesandbox with your issue so we can quickly investigate.
