### ISSUE TITLE
Nest + ts-rest + fastify

### ISSUE THREAD

**Issue by btravers** [ts-rest/ts-rest#277]
Hello 👋🏻 

Thanks for this amazing library.

I tried to use it with `Nest` + `fastify` but I am facing an issue.

Here is a minimal repository with `Nest` + `ts-rest` + `fastify` : https://github.com/btravers/ts-rest-fastify

The first commit does not use `fastify` and it is perfectly OK.

When I introduce `fastify` in the second commit, I have the following error : 

```
throw new Error(`Method '${method}' already declared for route '${pattern}' with constraints '${JSON.stringify(constraints)}'`)
```

**Comment by oliverbutler** [comment]
Ah! We mentioned this amongst the core team the other day - we realised we **hadn't** tested the nest lib with Fastify yet. @ts-rest/core 

I'll pull the repo and take a look :)

**Comment by oliverbutler** [comment]
<img width="1098" alt="Screenshot 2023-06-13 at 23 10 15" src="https://github.com/ts-rest/ts-rest/assets/47489826/b6a1b597-a04a-4ba1-baf8-5d5a75c2ba47">

I think i found the bug - but first I'm going to walk you through _why_ I think this is a problem.

With the "single handler" approach in Nest we're able to call @Get/@Post/etc under the hood for every method, with "multi handler" we HAVE to call @All, theres no way (we found) to add a subset of methods.

From the compiled code I sent you can see it's adding the method many times, importantly this **isn't a set** so duplicates are possible.

This was OK with express + Nest as it appears no error is thrown and @All("/path") can be called twice, but this fails with Fastify.
