### ISSUE TITLE
@ts-rest/nest optional peer dependencies

### ISSUE THREAD

**Issue by btravers** [ts-rest/ts-rest#280]
Hello,

I think `@nestjs/platform-express` and `@nestjs/platform-fastify` should be optional peers. 

When I have a look on the actual package.json https://www.npmjs.com/package/@ts-rest/nest?activeTab=code, both are peer dependencies but none is optional. 

I am facing an issue because `pnpm` auto install peers by default.

**Comment by Gabrola** [comment]
@btravers thanks for raising this. I was actually just working on this last morning, so should have a fix out soon.
