### ISSUE TITLE
Usage with SWR

### ISSUE THREAD

**Issue by Riley-Brown** [ts-rest/ts-rest#287]
Just discovered ts-rest and it looks really promising for my application. However, I am using `swr` for data fetching and wonder if there is a way to make `swr` play nice with the custom `api` client arg.

The issue is `swr` assumes the `data` arg will have a successful response type

example: 
```ts
const { data } = useSWR('/user', tsRestClient.getUser)
```
The type of `data` here will be a union of each response in the `getUser` contract, including error responses. I am looking for a way to use the custom `api` client arg to infer only the valid 200-299 status responses

**Comment by Gabrola** [comment]
I don't think SWR specifically actually expects or even cares about the response status. What is returned in `data` or `error` depends on if you throw an error or not. `fetch` does not throw on non-2xx status codes, therefore SWR will include all responses in `data`. If you want to do this you need to build out some custom logic to throw error. They've outlined this in their docs
```typescript
const fetcher = async url => {
  const res = await fetch(url)
 
  // If the status code is not in the range 200-299,
  // we still try to parse and throw it.
  if (!res.ok) {
    const error = new Error('An error occurred while fetching the data.')
    // Attach extra info to the error object.
    error.info = await res.json()
    error.status = res.status
    throw error
  }
 
  return res.json()
}
 
// ...
const { data, error } = useSWR('/api/user', fetcher)
// error.info === {
//   message: "You are not authorized to access this resource.",
//   documentation_url: "..."
// }
// error.status === 403
```

You can do the same with ts-rest using a [custom client](https://ts-rest.com/docs/core/custom). To control the returned type you can narrow the response type using the inference [type helpers](https://ts-rest.com/docs/core/infer-types#inferring-response-types) using `ClientInferResponses` and pass the second optional argument as a union of all status codes 200-299 and enable `strictStatusCodes` in your contract.

**Comment by Riley-Brown** [comment]
Thanks for the response. After checking out `@ts-rest/react-query` I've realized that suits my needs more than `swr`
