### ISSUE TITLE
[OpenAPI] Add security to operation object

### ISSUE THREAD

**Issue by btravers** [ts-rest/ts-rest#288]
Hello,

Is there an easy way to provide the security field to an operation object in the generated OpenAPI document ?
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#operation-object

Maybe we should add a security field in `AppRouteCommon` https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/core/src/lib/dsl.ts#L27 ?

**Comment by Gabrola** [comment]
I've been on the fence for this for a while, but I think we currently have a strong case against making anything that is OpenAPI specific a first-class citizen in the contract definition. The contract mainly exists to facilitate the client-server behavior that is common between all the client and server libraries, however the OpenAPI library is only a plugin so it doesn't feel proper to include anything that has to do with it as part of our core library and it would have no effect on the client-server behavior.

Another major point is that since we do not do any kind of build-step processing on contracts, the entire contract is included in the client bundle and it would not be ideal, or in some cases secure, to include swagger definitions in the bundle.

We might be able to add some helpers in the OpenAPI library to facilitate adding operation fields, not just `security`, but definitely not as part of the main contract.

At the moment, our suggestion is to manually modify the generated OpenAPI document. If you still want to add the definitions to the contract, you can do so through the `metadata` field and traverse the contract manually.

**Comment by btravers** [comment]
Thank you for the answer.

Yes, I found a work around using the `metadata` field and traversing the contract.  

I do not know what solution is the best.
In my opinion, security means and required scopes should be parts of the contract. Those are required information for the client to correctly requesting the server.

**Comment by jvcmanke** [comment]
First of all, I love this lib, been testing it for the past few days and am really enjoying the dev experience so far.

Like @btravers I also had the same "issue" regarding how to better define these information within the contract.
I think it would be cool to have a field specifically for auth definitions, but there are so many different ways to handle auth that I feel it might create more issues than solve.

I also have used metadata in a similar way, but it does rely on you knowing how the OpenAPI spec is constructed from the contract, could the `@ts-rest/open-api` package accept a "transform" function (or something like that) that has access to the metadata to add extra information while it is generating the spec? I think it would be a very clean way that might be useful in other use cases as well.

**Comment by Gabrola** [comment]
@jvcmanke yeah, I'm thinking of something similar that should be constrained to the `@ts-rest/open-api` package.

I think what makes sense is to add another parameter to the `generateOpenApi` function similar to the request handlers for the server libraries, but instead it receives the generated schema for that route, and the function would be able to return a transformed schema.

```typescript
const openApiDocument = generateOpenApi(
  myContract,
  {
    info: {
      title: 'Posts API',
      version: '1.0.0',
    },
  },
  {
    getPosts: ({ route, schema }) => ({
      ...schema,
      security: {
        OAuth2: route.metadata.scopes
      },
    })
  }
);
```

**Comment by seagullmouse** [comment]
This is a blocker to adoption for us. We currently use TSOA which has `@Security` annotation.

This hands off to middleware for authentication.

**Comment by michaelangeloio** [comment]
Is anyone willing to help get this through the door? Following @Gabrola 's advice?

**Comment by anatolii-valence** [comment]
@Gabrola advice suggest to move this info to upper level but I have a strong feeling that security requiremenets are the part of the contract itself, wdyt?

**Comment by Gabrola** [comment]
I'd like to make a u-turn on my previous take. I see now how there are many cases where a security field serves a true purpose as part of the contract and can actually drive the implementation on the backend.

One thing to be extremely mindful of is my previous point regarding the entire contract being included in the client bundle. I can think of some (rare, I think) cases where one would not want to expose things such as the required oauth scopes for ALL endpoints in the client bundle. Yeah, security through obscurity and whatnot but still doesn't mean you'd want to expose the inner workings of your systems. I don't think this is a blocker though, just gonna be a caveat for some people.

The big consideration is that we need to make sure that this needs to be cleanly crafted for each backend library to allow a developer to inject their own auth middleware and be able to consume the security metadata. Currently the contract has been mainly used to drive just validation (and act as a contract obviously), and there is a currently no clean way to to plug-in a validation library other than zod. We need to make sure this does not become the case with auth.

**Comment by anatolii-valence** [comment]
That all make sense. Agree with every point in it. Gentlemen’s, let’s then design the solution and try to implement some?On 21 Jan 2024, at 07:20, Youssef Gaber ***@***.***> wrote:﻿
I'd like to make a u-turn on my previous take. I see now how there are many cases where a security field serves a true purpose as part of the contract and can actually drive the implementation on the backend.
One thing to be extremely mindful of is my previous point regarding the entire contract being included in the client bundle. I can think of some (rare, I think) cases where one would not want to expose things such as the required oauth scopes for ALL endpoints in the client bundle. Yeah, security through obscurity and whatnot but still doesn't mean you'd want to expose the inner workings of your systems. I don't think this is a blocker though, just gonna be a caveat for some people.
The big consideration is that we need to make sure that this needs to be cleanly crafted for each backend library to allow a developer to inject their own auth middleware and be able to consume the security metadata. Currently the contract has been mainly used to drive just validation (and act as a contract obviously), and there is a currently no clean way to to plug-in a validation library other than zod. We need to make sure this does not become the case with auth.
