### ISSUE TITLE
query with array docs - There is bug in fastify btw

### ISSUE THREAD

**Issue by gustawdaniel** [ts-rest/ts-rest#290]
There is docs of parameters

https://ts-rest.com/docs/core/#query-parameters

but I would like to handle arrays in query.

it would be awesome to support different formats

```
'foo[]=1&foo[]=2&foo[]=3'
'foo[0]=1&foo[1]=2&foo[3]=3'
'foo=1,2,3'
'foo=1&foo=2&foo=3'
// Any custom separator can be used:
'foo=1|2|3'
// ... and more custom formats
```

https://stackoverflow.com/a/67095427/6398044

I see that there is code to handle arrays

https://github.com/ts-rest/ts-rest/blob/8ae04a8d982736d179dc6d8d3b8836300a6c98a2/libs/ts-rest/core/src/lib/query.spec.ts#L68

but do not know how to define contract

**Comment by gustawdaniel** [comment]
done by `z.array(z.string().transform(Number))`

```
  getEvents: {
    method: "GET",
    path: "/events",
    summary: "Events",
    query: z.object({
      dateFrom: z.string().transform(Date),
      dateTo: z.string().transform(Date),
      sportIds: z.array(z.string().transform(Number)),
      disallowedEventStatuses: z.array(z.string().transform(Number)),
    }),
    responses: {
      200: z.array(
        z.object({
          eventStatusId: z.number(),
          id: z.number(),
          name: z.string(),
          startDate: z.string(),
        })
      ),
    },
  },
  ```

**Comment by Gabrola** [comment]
You can already define arrays in the query contract, but how it is formatted and parsed depends on your backend framework.

**Comment by gustawdaniel** [comment]
I had code with `ts-rest` with `/countries?id[]=2&id[]=3` that worked, but when I changed express to fastify it stopped working.

But I checked that form

http "localhost:4000/countries?id=2&id=3"

works in `fastify`.

So answer to my original question is:
- id depends

For express use `id[]=1&id[]=2` but for fastify `id=1&id=2`

Problem for fastify is for case with one element. Eg

```
GET localhost:4000/countries?id=2
```

gives

```
{
    "bodyErrors": null,
    "headerErrors": null,
    "pathParameterErrors": null,
    "queryParameterErrors": {
        "issues": [
            {
                "code": "invalid_type",
                "expected": "array",
                "message": "Expected array, received string",
                "path": [
                    "id"
                ],
                "received": "string"
            }
        ],
        "name": "ZodError"
    }
}
```

**Comment by gustawdaniel** [comment]
there is an open issue

https://github.com/fastify/fastify/issues/2841

I fixed by

```
export const queryNumbersArray = z
  .array(z.string().or(z.number()).transform(Number))
  .or(z.string().transform((v: string) => [Number(v)]))
  .optional();
```

and tests

```
import { queryNumbersArray } from '../src/queryNumbersArray';

it('problem with array', () => {
  const { z } = require('zod');

  // Test with different input scenarios
  const input1 = '42'; // Single string input
  const input2 = ['42', '54', '67']; // Array of string input
  const input3 = [42, 54, 67]; // Array of number input

  const result1 = queryNumbersArray.parse(input1);
  expect(result1).toEqual([42]);

  const result2 = queryNumbersArray.parse(input2);
  expect(result2).toEqual([42, 54, 67]);

  const result3 = queryNumbersArray.parse(input3);
  expect(result3).toEqual([42, 54, 67]);

  const result4 = queryNumbersArray.parse(undefined);
  expect(result4).toEqual(undefined);
});

```

**Comment by gustawdaniel** [comment]
I solved the problem with the server in prev command, but the client still sends `a[]=1&a[]=2` instead of `a=`&a=2` for fastify.

So fastify not detect these data correctly.

---

Solution would be enforcing treatment `a[]=1&a[]=2` as param `a = [1,2]`.

There is connected issue https://github.com/fastify/fastify/issues/726

Fix that I found

```
import qs from 'qs';

export function getFastifyServer(): FastifyInstance {
  const app = fastify({
    querystringParser: str => qs.parse(str)
  });

  return app;
}
```

**Comment by michaelangelo-io** [comment]
@gustawdaniel is this an issue with ts-rest? Please mention me to reopen if you think it is
