### ISSUE TITLE
feature request: support const type parameters from typescript V5

### ISSUE THREAD

**Issue by scarf005** [ts-rest/ts-rest#294]
# Summary

use [const type parameters](<https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters>) feature from typescript version 5.0 to enhance type safety for queries and mutations. 

## Problem

```ts
const getTodo = c.query({
  method: "GET",
  path: "/todos/:id",
  responses: {
    200: todoSchema,
    404: notFoundSchema,
  },
})
```

Query or mutation needs to be passed as property of another router, however type information for `path` property gets lost as typescript does not try to 'narrow' types by default. To fix this behavior, objects must be [const asserted](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions) to correctly narrow type of `path` to `/todos/:id`.

## Solution

https://github.com/ts-rest/ts-rest/blob/32d7167bff3c1f08dfb61ce90c21473725b5df50/libs/ts-rest/core/src/lib/dsl.ts#L182-L186

change to const type parameter for query (and other objects meant to be passed in to another object), for example:

```ts
 /** 
  * A single query route, should exist within 
  * a {@link AppRouter} 
  */ 
query: <const T extends AppRouteQuery>(query: T) => T
```

## Video demo

https://github.com/ts-rest/ts-rest/assets/54838975/cc1f5017-3471-438c-a79f-37aad579bf89

https://github.com/ts-rest/ts-rest/assets/54838975/29249467-8b4c-4b75-ba1d-49d669db3325

## Others

I'm interested in submitting a PR. However, this would be considered a breaking change as this requires bumping minimum required typescript version to `5.x`.

**Comment by Gabrola** [comment]
Thank you for the suggestion! Yeah, `const` modifiers on generics can improve so many things but at the moment it would be hard to introduce this as part of the exported declarations as it is indeed a breaking change. Even if we intend to release a major version for another reason, I think it would be hard to introduce this still as many users might still not be ready to upgrade to TS 5

**Comment by michaelangeloio** [comment]
Agree with @Gabrola, I think this is out of scope for now. We will eye this closely and take another look after TS 5 has had some time to mature.
