### ISSUE TITLE
Pass in contract information within implementation function

### ISSUE THREAD

**Issue by jvcmanke** [ts-rest/ts-rest#298]
I think it would be very useful to be able to access the contract metadata and possibly other contract information directly inside the implementation function without manually pathing from the contract.

As an example using the `@ts-rest/next` package, but it would be analogous in the other ones.
Currently I can do this:
```typescript
export const postsRouter = createNextRoute(apiContract.posts, {
  createPost: async (args) => {
    const metadata = apiContract.posts.createPost.metadata

    //...do stuff
  }
})
```
Which works fine, but would be much more intuitive and expandable (IMO) to be able access contract information like this:
```typescript
export const postsRouter = createNextRoute(apiContract.posts, {
  createPost: async (args) => {
    const metadata = args.metadata

    //...do stuff
  }
})
```
or
```typescript
export const postsRouter = createNextRoute(apiContract.posts, {
  createPost: async (args, route) => {
    const metadata = route.metadata

    //...do stuff
  }
})
```
or some similar way.

This is not really issue or anything, just convenience, but it would be very useful for creating some standard (custom) functionality, like middleware, based on metadata or other contract information, like this for example:
```typescript
export function checkScopes<
  Args extends { headers: IncomingHttpHeaders, metadata?: Record<string, unknown> },
  Return
>(route: (args: Args) => Promise<Return>) {
  return async (args: Args) => {
    const metadata = metadataSchema.parse(args.metadata);

    const authResponse = authenticate(args.headers, metadata.scopes);
    if (authResponse.type === "error") {
      return authResponse.error;
    }

    return await route(args);
  };
}
```

and then use it like this, basically in any route: 

```typescript
export const postsRouter = createNextRoute(apiContract.posts, {
  createPost: checkScopes(async (args) => {
    //...do stuff
  })
})
```

**Comment by jvcmanke** [comment]
@Gabrola I can submit a PR if I have the time, in particular for the `@ts-rest/next` side of things, I'm not that familiar with the other integrations.

Any preference on how would you pass in the infromation?
Within the `args` or as a separate parameter of the implementation function?

I've messed around a bit with the express integration, and I think it already has something like this within the middlware, which put this kind of information in the request parameter, but I'm not a big fan of that.

Just let me know and I'll get the PR ready.

**Comment by Gabrola** [comment]
Yeah feel free to to submit a PR, it's fine if it's just for the nextjs lib. The approach taken in the express lib is to able to have access to the endpoint schema in middleware since they only take the `req, res, next` params, so it must be passed through `req`. In your case, I think it's best to just add it to the `args` object.

**Comment by oliverbutler** [comment]
This is a nice enchantment, anybody looking into it? I could investigate the nest side.

**Comment by jvcmanke** [comment]
@oliverbutler Sadly, I didn't have enough time to start working on anything yet, even though I think it would be a really small change.

I was planning on working strictly on the nextjs lib so we probably wouldn't have much conflict anyway. 😄
