### ISSUE TITLE
nx 16.5 (@nestjs/common@10.0.5)

### ISSUE THREAD

**Issue by robert-king** [ts-rest/ts-rest#301]
It seems ts-rest needs:
   "@nestjs/common": "9.4.0",
    "@nestjs/core": "9.4.0",
    
after nx migrate to 16.5 i think i need:
    "@nestjs/common": "10.0.5"
    "@nestjs/core": "10.0.5",
    
    i guess for now i can just downgrade to 9.4.0, or try use --legacy-peer-deps

**Comment by oliverbutler** [comment]
#325
