### ISSUE TITLE
@ts-rest/openapi: cannot set description

### ISSUE THREAD

**Issue by scarf005** [ts-rest/ts-rest#305]
original discussion: https://discord.com/channels/1055855205960392724/1055857874359820318/1126692982230352005

![image](https://github.com/ts-rest/ts-rest/assets/54838975/d3587af4-d1ee-4360-9ab9-dfd297b949ae)

```ts
    patch: {
      // ...
      pathParams: z.object({
        reviewsId: z.number().int().describe('reviews ID to check').openapi({ title: 'a', description: 'b', example: 1 }),
      }),
      responses: {
        402: z.number().describe('when not authorized'),
      },
    },
```

version: 3.26.4

**Comment by stephyswe** [comment]
yeah this need to be looked over. have you made any example using ts-rest ? @scarf005

**Comment by scarf005** [comment]
not yet. i'll inspect whether the bug is comming from @anatine/zod-openapi or @ts-rest/openapi after i get some free time.

**Comment by llllvvuu** [comment]
This is working fine for me. I'm using RapiDoc to render the openapi.json

here is where zod-openapi added the feature: https://github.com/anatine/zod-plugins/issues/61

**Comment by llllvvuu** [comment]
I spoke too soon, it only renders in the Resp but not in the Req.

I suspect this is because zod-openapi puts the description in the `schema` but OpenAPI expects it in the parent object for parameters:

```json
    "/orders/{orderHash}": {
      "get": {
        "summary": "Get an order by order hash",
        "tags": [],
        "parameters": [
          {
            "name": "orderHash",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "pattern": "^0x[0-9a-fA-F]{64}$",
              "description": "EIP-712 `hashStruct` / `ethers@6` `TypedDataEncoder.hash`"
            }
          }
        ],
```

zod-openapi's behavior is correct for the scope of zod-openapi, I would say it's in ts-rest's scope to fish out the `description` and move it to the parent object. I can make a PR sometime this month if desired.

**Comment by llllvvuu** [comment]
Fix and test cases added: https://github.com/ts-rest/ts-rest/pull/364
