### ISSUE TITLE
multiple contracts for generateOpenApi

### ISSUE THREAD

**Issue by kurdin** [ts-rest/ts-rest#309]
Hello, 

I am evaluating ts-rest as a backend for my next project and I could not figure out how can I add multiple contracts to openAPI swagger UI. Am I missing something but first param of `generateOpenApi` does not except an array of contracts.  

```js
	// messages contract
	createExpressEndpoints(messagesContracts, messagesRouter, app)
	// posts contract
	createExpressEndpoints(postsContracts, postsRouter, app, { jsonQuery: true })

	const openApiSchema = generateOpenApi([messagesContracts, postsContracts], {
		info: { title: 'API Docs', version: '0.1' }
	})
```
~~how can I combine contracts for `generateOpenApi` ?~~

I found the way to combine multiple contracts into a single object with 
```js
const c = initContract()

const apiRoutes = c.router({
	posts: postsContracts,
	messages: messagesContracts
})

export default apiRoutes
```

and use this as an input for `generateOpenApi`
```js 
const openApiSchema = generateOpenApi(apiRoutes, {
 info: { title: 'API Docs', version: '0.1' }
})
```

**Comment by kurdin** [comment]
Another problem I see, if I describe a post contracts  as Typescript instead of zod, I can't get Swagger UI to display `Request body` params

<img width="1041" alt="image" src="https://github.com/ts-rest/ts-rest/assets/6027060/30a30be4-ee03-4bbd-8ac9-a3e1eb3e42d3">

**Comment by oliverbutler** [comment]
@kurdin I think this is all intended behaviour!

As you've found thats the correct way to combine routers, you can also spread them together if you don't want to introduce another layer to the object.

Given that c.type<> doesn't exist at runtime it's impossible for us to generate OpenAPI docs from the types sadly - so that's why we require Zod here

**Comment by kurdin** [comment]
@oliverbutler sorry for reopening this issue. 
First of all, thank you for the ts-rest project. I think you found a very elegant way to describe contracts and routes with validation, and I believe this project deserves more visibility in the similar field.

>Given that c.type<> doesn't exist at runtime it's impossible for us to generate OpenAPI docs from the types sadly - so that's why we require Zod here

Ok, so does this mean that if I use Typescript in contracts for validation instead of Zod, it wont work as well on runtime ? If so, what is the point to use typescript like this in the example you provided. 

```js
body: c.type<{
  title: string
  description: string | null
  content: string | null
  published: boolean
  tags: string[]
}>()
```	

Thank you again.
