### ISSUE TITLE
Response headers not sent to the client (NextJS)

### ISSUE THREAD

**Issue by ivan-dalmet** [ts-rest/ts-rest#316]
First nice work on this project!

We are trying to migrate an existing application to ts-rest and nextjs.
But we have an issue on the response headers.
The current API is sending a custom header for pagination total in the response.
It's working on the client, we can get the header in the response if we use the existing API. But now that we are trying to use ts-rest on the backend with nextjs, we can't make the header to be available in the response.

```ts
export const usersRouter = createNextRoute(contract.users, {
  getAll: async ({ req, query }) => {
    // ... code to get the users and the total ...

    const headers = new Headers();
    headers.set('x-total-count', total.toString());

    return {
      status: 200,
      body: users,
      headers, // NOT WORKING 😭
    };
  },
});
```

Any idea how we can make it work?
Thanks for your time 🙏

**Comment by oliverbutler** [comment]
Hey @ivan-dalmet thanks for the issue! Do any of the types indicate that you're able to return headers from getAll? 🤔 

I _believe_ the only/correct way to do this is to destructure `res` and set the headers you want using `res.setHeader`

If this doesn't work out I'll add this to my list and try write some tests to check the functionality and how we do this in the other server libs!

![Screenshot 2023-07-27 at 23 10 45](https://github.com/ts-rest/ts-rest/assets/47489826/848f7db0-92ed-403e-a319-b00891cfc2b5)

**Comment by ivan-dalmet** [comment]
> Hey @ivan-dalmet thanks for the issue! Do any of the types indicate that you're able to return headers from getAll? 🤔 
> 
> I _believe_ the only/correct way to do this is to destructure `res` and set the headers you want using `res.setHeader`
> 
> If this doesn't work out I'll add this to my list and try write some tests to check the functionality and how we do this in the other server libs!
> 
> ![Screenshot 2023-07-27 at 23 10 45](https://github.com/ts-rest/ts-rest/assets/47489826/848f7db0-92ed-403e-a319-b00891cfc2b5)
> 

No the type is not saying that I can pass headers in the return, it was just a guess on my side.
You solution seems fine!
I'm away from the computer for a long time but, the solution you give seems good, we can close the issue and I will reopen it if it's not working.

Thanks for your time!
