### ISSUE TITLE
docs of e2e setup

### ISSUE THREAD

**Issue by gustawdaniel** [ts-rest/ts-rest#317]
I am looking for documentation or examples of code with e2e tests.

A perfect example is fastify, which can be tested without `supertest` by `app.inject`

```
https://fastify.dev/docs/latest/Guides/Testing#benefits-of-using-fastifyinject
```

but here I have a custom client

https://ts-rest.com/docs/core/custom

and probably I am able to use it with an instance of fastify or Express supertest instead of Axios.

Did everybody try to do it?

**Comment by masterbater** [comment]
Setup openapi, use openapi to generate e2e

**Comment by michaelangelo-io** [comment]
@gustawdaniel sorry, do you mind explaining further what you're trying to achieve?

**Comment by michaelangeloio** [comment]
Going to close this; please let me know if you'd like to reopen. TIA!
