### ISSUE TITLE
ClientInferResponseBody has a bug when handling Arrays

### ISSUE THREAD

**Issue by renatoaraujoc** [ts-rest/ts-rest#331]
Hello,

I have just found out that `ClientInferResponseBody` has a bug regarding handling inference of Arrays. I'll show some screenshots and in the end prove that it indeed has a bug by supplying a dirty code to "fix" the issue.

Consider you have this:

```typescript
// We're saying that the return type is an array of strings
getAll: {
    method: 'GET',
    path: '/get-all',
    responses: {
        200: c.type<string[]>()
    }
}
```

When we use the `ClientInferResponseBody` on this response we get this:

![Screenshot 2023-08-04 at 02 06 32](https://github.com/ts-rest/ts-rest/assets/358128/e3d15cb0-f501-4bf7-bbc8-2b2660393131)

So, for some reason the type being inferred is an object that has all array properties, right...

Now let's try to infer the type of this array, it should be a `string`, plain and simple, but we get:

![Screenshot 2023-08-04 at 02 08 38](https://github.com/ts-rest/ts-rest/assets/358128/8d0ea8c2-85cd-46aa-ba9a-c5bc4c078258)

In the end, some nasty code is necessary to get the array type, like this:

![Screenshot 2023-08-04 at 02 10 37](https://github.com/ts-rest/ts-rest/assets/358128/1ee5ef96-7ab8-431a-bd48-c2fac25f3f45)

I made this little hack myself to keep going with my development:

![Screenshot 2023-08-04 at 02 30 22](https://github.com/ts-rest/ts-rest/assets/358128/27deaf9c-78f1-46b8-8372-b8d443235af7)

Thank you!

**Comment by michaelangelo-io** [comment]
@Gabrola mind taking a look?

**Comment by Gabrola** [comment]
Looks like it's a bug in the LSP displaying the tooltip. However, if you try to do something like `const foo: RespArrType = 2` it will actually complain that it is not a `string`

Works fine here [Playground Link](https://www.typescriptlang.org/play?ts=5.0.4#code/JYWwDg9gTgLgBAbzsAdsGBhCKZQIYDGMANHBgDbACmOAkigGZVQBKVAzpCu1QEIQATAJ5wAvnAZQIIOAHIAAjHYBaKBxgB6AtCqyA3ACgD27vAJwAvMjSZsuQjAAUASkMn2Zu-iKW4BAHRSAK4wzI4IBnBRcADmVDAAyrioMewAXIiR0dkg8QAWghmyAOIAogAqssRZ2VFgeDB5RRoeUCnsVTW1apzYPOmZtUNwAEwADGMZATBCYFQAPK0pANoAugB8LtXDYl2iBqKuRjNzcACCUPhC5bNUvhTUdIzMbL3cfIJC8ydUEAx+Xgc-jiiWSKFSpHGY3Whh+50ueCEtFCMisFyuNzmyxQQRAACNmKs9EA)
