### ISSUE TITLE
Example Fastify + Swagger and swagger-ui

### ISSUE THREAD

**Issue by anaelChardan** [ts-rest/ts-rest#332]
How to use swagger-ui with fastify and ts-rest ;)

**Comment by dohaicuong** [comment]
@anaelChardan I just quickly draft a minimal setup on how to use it with @fastify/swagger and @fastify/swagger-ui
https://github.com/dohaicuong/ts-rest-fastify

**Comment by michaelangelo-io** [comment]
closing for now, let me know if anything else is needed

**Comment by anaelChardan** [comment]
Hum I still have a problem, none of the parameters or responses are displayed:

<img width="915" alt="CleanShot 2023-08-09 at 01 40 51@2x" src="https://github.com/ts-rest/ts-rest/assets/6115681/73707117-26d9-4eb1-8e2d-9c6adab781be">

**Comment by dohaicuong** [comment]
> @dohaicuong this is great!
> 
> Do you mind opening a PR to add to our docs this example? This is a good place to add it: https://ts-rest.com/docs/fastify

so for the late reply, yes I will open an PR for that

**Comment by dohaicuong** [comment]
@michaelangelo-io here you go
https://github.com/ts-rest/ts-rest/pull/345

let me know if it's ok

**Comment by dohaicuong** [comment]
> Hum I still have a problem, none of the parameters or responses are displayed:
> 
> <img alt="CleanShot 2023-08-09 at 01 40 51@2x" width="915" src="https://user-images.githubusercontent.com/6115681/259258834-73707117-26d9-4eb1-8e2d-9c6adab781be.png">

that seems to be other problem, I have come across a thread about the response is not parsed or something

**Comment by anaelChardan** [comment]
Yes indeed this is another problem that we would need to tackle I guess otherwise the generation is less useful :D
