### ISSUE TITLE
Response does not parse when response content-type header is `application/problem+json`

### ISSUE THREAD

**Issue by SeanCassiere** [ts-rest/ts-rest#335]
Trying out the library, and noticed this.

APIs built on `.NET` sometimes (tend to) return a `content-type` header value of `application/problem+json; charset=utf-8`.
This header value can be seen on a `400` level error.

This presents a problem as the `tsRestFetchApi` function only uses the `.json()` parse method when the content-type header strictly matches `application/json` as seen [here](https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/core/src/lib/client.ts#L94-L100).

Not sure if this is something to be covered within the scope of this project, but it's something I ran into, and I'll leave it up to you folk to decide on.
For now, I'll be rolling my own fetch adapter allowing for this variation of the header's value whilst testing out the library.

**Comment by SeanCassiere** [comment]
This is what I ended up rolling in my custom ts-rest compatible fetcher fn.

```ts
  if (contentType?.includes("application/") && contentType?.includes("json")) {
    return {
      status: result.status,
      body: await result.json(),
      headers: result.headers,
    };
  }
```

**Comment by michaelangelo-io** [comment]
Yeah, this is a valid bug. We should be more flexible in our implementation, I'll open a PR to fix this.
