### ISSUE TITLE
Next.js 13 app router integration

### ISSUE THREAD

**Issue by XDean** [ts-rest/ts-rest#336]
Since [Next.js 13.4 released](https://nextjs.org/blog/next-13-4), it's recommended to use the new app router.
We need integrate with the new API.

**Comment by sandervspl** [comment]
Version 3.28 shipped app router support

https://github.com/ts-rest/ts-rest/pull/315

**Comment by wjoel** [comment]
3.28 helps the client, but it doesn't seem to do much for the server, unless I'm missing something.
I currently have `pages/api/[...ts-rest].tsx` with
```typescript
...
const router = createNextRoute(api, apiRouter)
export default createNextRouter(api, router)
```
which works fine, but ideally we'd have a way that doesn't use `pages` at all, but rather `app/api/[...slug]/page.tsx`, or something like that. I don't see how to do that with 3.28.

**Comment by michaelangelo-io** [comment]
Hi, yes, we're still working on App Dir API routes support. I will update y'all as we make progress. I'll use this issue as a way to track progress. @oliverbutler

**Comment by kylegillen** [comment]
@michaelangeloio that's great news! Any progress on this? I'm picking up TSRest (and loving it!) on a new NestJS / NextJS project (I really don't want to use TRPC 😩).

Anything I can help with to move things along?

**Comment by wjoel** [comment]
I saw the comment from @michaelangeloio here: https://github.com/ts-rest/ts-rest/issues/428#issuecomment-1807141900
but I feel this thread is more appropriate for my reply.

In our case, we use ts-rest to get a stable and documented API that can be used by external clients as well. We use it specifically to avoid having a server action/component only API in Next.

Eventually we may move the API to a separate, pure backend service that doesn't use Next at all, but it is currently part of one fullstack service that uses Next and ts-rest. So this would still be useful to us (even though the Pages router is still supported), and so would support for Next 14, and that's the use case we have, fwiw.

**Comment by hichemfantar** [comment]
Hey, are there any updates on this?
May I ask what exactly is blocking this?
If it's an implementation issue then perhaps you could check the [create-t3-app implementation](https://github.com/t3-oss/create-t3-app). I believe they added app router support not that long ago so maybe that could help.

**Comment by lucyawrey** [comment]
It seems to me that there does not need to be specific NextJs 13 app dir support for hosting the server, but that instead there just needs to be a server adapter for the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), using it's standard Request and Response objects.

That is what Next 13+ Route Handlers are built on--as well as an increasing number of other platforms. It seems like this existing PR #273 may include functionality to make this work, although I am not sure it makes sense to bundle Fetch API support in with other serverless support. Additionally, that PR has not had any movement in a while.

**Comment by markdon** [comment]
Any plan for documentation and examples for using ts-rest with route handlers? Similar to the page router doc: https://ts-rest.com/docs/next

**Comment by Gabrola** [comment]
@markdon docs are here https://ts-rest.com/docs/serverless/next-serverless

**Comment by markdon** [comment]
@Gabrola I really appreciate the helpfulness! I hadn't bothered to look at that section, not planning to target serverless. [The example linked](https://github.com/ts-rest/ts-rest/blob/main/apps/example-next/app/api/app-router/%5B...ts-rest%5D/route.ts) is great :)

**Comment by Gabrola** [comment]
@markdon no worries :) Yeah, the package name "serverless" is a bit of a misnomer. It started out for serverless runtimes but expanded to more than just serverless runtimes.
