### ISSUE TITLE
Guards support in ts-rest/nest

### ISSUE THREAD

**Issue by AryanshMahato** [ts-rest/ts-rest#340]
Hello all! I was wondering how would we integrate AuthGuards while using ts-rest for nestjs.

**Comment by rklubenspies** [comment]
@AryanshMahato `ts-rest/nest` simply passes controller decorators through to Nest under the hood. We integrate it no different than any other route's auth guards:

```ts
@Controller()
// ! All routes require the workspace in Request to own the Account referenced in params
@UseGuards(AuthGuard, AccountOwnershipGuard)
@TsRest({ jsonQuery: true })
export class SampleController {
  constructor(
    private readonly sampleRepo: SampleRepository,
  ) {}

  @TsRestHandler(c.getSamples)
  async getSamples(@Request() req: ApplicationRequest) {
    return tsRestHandler(c.getAccountChecks, async ({ params }) => {
      // Get samples
      const samples = await this.sampleRepo.findAllForAccount(
        params.accountId,
      )

      return {
        status: 200,
        body: {
          samples,
        },
      }
    })
  }
}
```

**Comment by rklubenspies** [comment]
@AryanshMahato `@ts-rest/nest` simply passes controller decorators through to Nest under the hood. In our applications, we apply guards no different than any other Nest controller (see Nest docs [here](https://docs.nestjs.com/guards#authorization-guard)).

In the following example we are applying two guards `AuthGuard` and `AccountOwnershipGuard` to all routes in this controller, and all routes in the controller are powered by ts-rest. This works with both single and multi-handler approaches documented [here](https://ts-rest.com/docs/nest/).

```ts
@Controller()
// ! All routes require the workspace in Request to own the Account referenced in params
@UseGuards(AuthGuard, AccountOwnershipGuard)
@TsRest({ jsonQuery: true })
export class SampleController {
  constructor(
    private readonly sampleRepo: SampleRepository,
  ) {}

  @TsRestHandler(c.getSamples)
  async getSamples(@Request() req: ApplicationRequest) {
    return tsRestHandler(c.getSamples, async ({ params }) => {
      // Get samples
      const samples = await this.sampleRepo.findAllForAccount(
        params.accountId,
      )

      return {
        status: 200,
        body: {
          samples,
        },
      }
    })
  }
}
```

**Comment by mrsafalpiya** [comment]
Hello. Is there any way to apply guard in only one of the handlers in the multi-handler approach?

**Comment by ezorita** [comment]
I just had exactly the same question as @mrsafalpiya, how can guards be applied per method in multi-handler approach?

Thanks!

**Comment by cavator** [comment]
@rklubenspies u know if it's possible to apply Guards per method using multi-handler approach? because if u have RBAC u need to apply route by route
