### ISSUE TITLE
Documentation bug in README

### ISSUE THREAD

**Issue by sramam** [ts-rest/ts-rest#347]
I just started to look at ts-rest. 
Seems like a very interesting project. 

Is this a bug or intended?
https://github.com/ts-rest/ts-rest/blob/main/README.md?plain=1#L59
Shouldn't 
```
59:  getPost: async ({ params: { id } }) => {
```
Really be?
```
59:  getPosts: async ({ params: { id } }) => {
```

**Comment by michaelangelo-io** [comment]
Will fix this
