### ISSUE TITLE
Type error when combining server contracts with fastify

### ISSUE THREAD

**Issue by ryanstaniforth** [ts-rest/ts-rest#349]
After failing to figure out how to combine routers, I found issue #262. Turns out I had it right but there seems to be an issue with `@ts-rest/fastify`.

This code presents a type error at `auth: authServer`, but compiles fine if you swap `@ts-rest/fastify` for `@ts-rest/express`.

```typescript
import { initContract } from '@ts-rest/core';
import { initServer } from '@ts-rest/fastify';
import { z } from 'zod';

const c1 = initContract();

export const authContract = c1.router({
  login: {
    method: 'POST',
    path: `/auth/login`,
    body: z.object({
      email: z.string(),
      password: z.string(),
    }),
    responses: {
      200: z.object({
        token: z.string(),
      }),
    },
  },
});

const c = initContract();

export const contract = c.router({
  auth: authContract,
});

const s1 = initServer();

export const authServer = s1.router(contract.auth, {
  login: async () => {
    return {
      status: 200,
      body: {
        token: 'secret token',
      },
    };
  },
});

const s = initServer();

export const router = s.router(contract, {
  auth: authServer,
});
```

**Comment by oliverbutler** [comment]
Hey @ryanstaniforth thanks for reporting - this is bizarre upon first glance.

I'll take a look at the differences between the two libs, it's very possible I missed testing combined contracts with the fastify lib...

**Comment by oliverbutler** [comment]
As I'm investigating this and writing some more tests around the lib I want to suggest a super temporary fix 

I'd (for now) register each router individually 

```ts
const contractA = c.router({
      a: {
        method: 'GET',
        path: '/a',
        responses: {
          200: c.otherResponse({
            contentType: 'text/plain',
            body: c.type<string>(),
          }),
        },
      },
    });

    const contractB = c.router({
      b: {
        method: 'GET',
        path: '/b',
        responses: {
          200: c.otherResponse({
            contentType: 'text/plain',
            body: c.type<string>(),
          }),
        },
      },
    });

    const routerA = s.router(contractA, {
      a: async () => {
        return {
          status: 200,
          body: 'a',
        };
      },
    });

    const routerB = s.router(contractB, {
      b: async () => {
        return {
          status: 200,
          body: 'b',
        };
      },
    });

    const app = fastify({ logger: false });

    app.register(s.plugin(routerA)).register(s.plugin(routerB));

    await app.ready();
```

hopefully a workaround whilst i investigate!

**Comment by oliverbutler** [comment]
@ryanstaniforth ah this is an unfortunate one.

Looks like `.router` from the fastify implementation returns a object of the shape

```ts
{
  contract: TContract;
  routes: RecursiveRouterObj<TContract>;
}
```

The problem here is when you try pass the subRouter into another router it's expecting `RecursiveRouterObj<TContract>` NOT an object containing the `routes` object.

I've fixed the issue on the lib, but it'll be a breaking change currently - requiring `contract` to be passed when the fastify routes are added to the fastify app.

I'll investigate how to fix this in a non breaking way now

![Screenshot 2023-08-13 at 13 18 38](https://github.com/ts-rest/ts-rest/assets/47489826/e52104d0-1f0f-4af2-a3af-3b3d5bb9c0a7)

**Comment by ryanstaniforth** [comment]
Thanks @oliverbutler! I'll try that out when I get home.

**Comment by oliverbutler** [comment]
There is, therefore, another fix which is to access `.routes` on the subRouter

Personally not a huge fan of this object return from `.router`

![Screenshot 2023-08-13 at 13 22 27](https://github.com/ts-rest/ts-rest/assets/47489826/fecb2bdc-3ac8-4a54-ba8c-41a16f2ecd8a)
