### ISSUE TITLE
Is ts-rest framework agnostic as in I can connect it with any backend framework?

### ISSUE THREAD

**Issue by Blankeos** [ts-rest/ts-rest#360]
Looking to try this project out in an unconventional way, specifically using Sveltekit. Can't find anything in the docs about implementing the ts-rest contract on an agnostic backend though. is this possible?

**Comment by michaelangeloio** [comment]
if Sveltekit supports the `fetch` API, this is entirely possible (for the client side at least)!

Looking at some of the code here:
https://kit.svelte.dev/docs/routing#server

You could theoretically define a contract and then type cast incoming requests as the contract, like (pseudo code):
```ts
// contract.ts
const contract = c.router({
 getRandomNumber: {
   query: z.object({
     min: z.string()
     max: z.string()
   }),
   method: 'GET'
   ...
```


```ts
//+server.js
const searchParams = url.searchParams<z.infer<contract.getRandomNumber.query>>
```
This assumes searchParams takes a generic, but hopefully that gets your creative juices flowing. 

Then for fetching you use the `@ts-rest/core` client as normal:

```
// some component
const client = initClient(contract)
const data = await client.getRandomNumber()
```
