### ISSUE TITLE
Remove "as const" requirement from Nest API

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#37]
Currently we need "as const" in the Nest response, investigate whether this can be removed using some kind of type narrowing.
<img width="612" alt="Screenshot 2022-08-27 at 18 03 47" src="https://user-images.githubusercontent.com/47489826/187040493-ece60a4e-e8fd-42ff-836d-2aa97955955d.png">

**Comment by ecyrbe** [comment]
from all i know, type narrowing can only work with functions.
So you'll need something like this :  
```ts
function response<T extends Response>(res: Narrow<T>): T {
  return res;
}
```
```ts
return response({
  status: 200,
  body: { posts, total: totalPosts },
});
```
