### ISSUE TITLE
trying to get basic example working

### ISSUE THREAD

**Issue by colinricardo** [ts-rest/ts-rest#378]
i could just be dumb but i cant get a simple unified version the basic NextJS code from the quickstart working:

in my `[...ts-rest].tsx`
```
import { initContract } from "@ts-rest/core"
import { createNextRoute, createNextRouter } from "@ts-rest/next"
import { z } from "zod"

const c = initContract()

const dogeContract = c.router({
  getDoge: {
    method: "GET",
    path: "/doge",
    responses: {
      200: z.object({
        message: z.string(),
      }),
    },
    summary: "Get doge",
  },
})

const api = {
  doge: dogeContract,
}

const dogeRouter = createNextRoute(api.doge, {
  getDoge: async () => {
    return { message: "wow" }
  },
})

const router = createNextRoute(api, {
  doge: dogeRouter,
})

// Actually initiate the collective endpoints
export default createNextRouter(api, router)

```

i get this type error: 

```
Type '() => Promise<{ message: string; }>' is not assignable to type 'AppRouteImplementation<{ summary: "Get doge"; responses: { 200: ZodObject<{ message: ZodString; }, "strip", ZodTypeAny, { message: string; }, { message: string; }>; }; method: "GET"; path: "/doge"; }>'.
  Type 'Promise<{ message: string; }>' is not assignable to type 'Promise<Prettify<AppRouteResponses<{ summary: "Get doge"; responses: { 200: ZodObject<{ message: ZodString; }, "strip", ZodTypeAny, { message: string; }, { message: string; }>; }; method: "GET"; path: "/doge"; }, HTTPStatusCode, "server", "default">>>'.
    Type '{ message: string; }' is not assignable to type 'Prettify<AppRouteResponses<{ summary: "Get doge"; responses: { 200: ZodObject<{ message: ZodString; }, "strip", ZodTypeAny, { message: string; }, { message: string; }>; }; method: "GET"; path: "/doge"; }, HTTPStatusCode, "server", "default">>'.ts(2322)
```

what am i doing wrong here?

like am i crazy but does each of the quickstarts/code/examples give a different way to actually get things set up?

e.g. 

![CleanShot 2023-09-01 at 13 21 39@2x](https://github.com/ts-rest/ts-rest/assets/21294951/8dba2a48-5182-49ce-9b7a-9950105d7940)

what is `c`?

elsewhere: 

```
import { initContract } from "@ts-rest/core"
const c = initContract()
```
but `contract` doesn't exist on c?

![CleanShot 2023-09-01 at 13 22 28@2x](https://github.com/ts-rest/ts-rest/assets/21294951/a8fec373-c2bf-4fa7-884d-049d137e3db4)

some of the docs say to use `c.type` in responses, elsewhere it says to use `z.object()` 

elsewhere, we make a contract with `c.router`?

![CleanShot 2023-09-01 at 13 23 36@2x](https://github.com/ts-rest/ts-rest/assets/21294951/2a20463b-4852-4ddc-8f84-59c5c806f181)

am confuse

is there a canonical self-contained example that i can just copy/paste and modfify?

**Comment by michaelangeloio** [comment]
Which version of Next are you using?

**Comment by colinricardo** [comment]
`13.4.13`

**Comment by Gabrola** [comment]
You need to return `{ status: 200, body: { message: 'wow' }}` not just `{ message: 'wow' }`
