### ISSUE TITLE
Responses object from contract only works with some statuses.

### ISSUE THREAD

**Issue by kapsule-studio** [ts-rest/ts-rest#379]
I have discovered this library and I love it. I have started implementing it in my project and everything seems to work fine except for a couple issues that I will post. Here is the first one. 

Before that, I have to say that the documentation is VERY confusing. It seems like it has been written by different people not talking to each other or consulting what others wrote... At some point we see `contract = c.router({...})`, later the router is named `router`. Same with `client` that becomes `api`. It takes some time to figure it out and how to set everything up.

On top of that, most sections lack explanations. You should really put yourself in the shoes of the person discovering your library for the very first time upon writting your docs. Especially because I have found only a single video tutorial on your library. I couldn't even find a blog article about it (which is not your fault but that's a reason to have a well explained documentation).

Now, back to the first issue I have encountered:

My contract looks like this (I have added a bunch of responses status to test):

![image](https://github.com/ts-rest/ts-rest/assets/77295465/f2e34d03-231c-4852-8cf1-c7300bc95e36)

Yet, when I hit the route with `useMutation()`, of all the status I defined in the contract, only 201 and 202 went through:

![image](https://github.com/ts-rest/ts-rest/assets/77295465/3d656d62-bdd3-4518-8dee-30d79c05aa41)

I get this error for other statuses:

![image](https://github.com/ts-rest/ts-rest/assets/77295465/675534fa-940e-4a03-8379-25c1ef619cd1)

Is it some intentional behavior? If not, how can I solve this problem? Any help would be greatly appreciated!

**Comment by michaelangeloio** [comment]
@kapsule-studio do you have a minimal reproduction repo you can point us to?

**Comment by Gabrola** [comment]
No error responses (status code >= 300) are included in the `result.data`, rather the query will fail and you'll find the response in `result.error` rather than in `result.data` and `result.isError` will be `true`
