### ISSUE TITLE
Unexpected status 500 whereas there is no error in the code.

### ISSUE THREAD

**Issue by kapsule-studio** [ts-rest/ts-rest#380]
After setting my contract, client and route, I have tried to use `useMutation()` and it works. The `console.log()` in the route is correctly sent and yet, instead of getting the right response, with the typesafe body, I get a status 500 error. 

Here is what my route looks like (I'm using Next js App Router):

![image](https://github.com/ts-rest/ts-rest/assets/77295465/4ddba14d-7824-4f40-bf18-fc7efed929c5)

The 'It Works' is correctly logged so I know that the route is hit and that my set up is working. But instead of returning the request's body like instructed:

![image](https://github.com/ts-rest/ts-rest/assets/77295465/0f3e3364-815b-4fa1-b4fd-101d76eb248a)

I get this error: 

![image](https://github.com/ts-rest/ts-rest/assets/77295465/d40fbcbd-7bb2-4f39-adcd-6311edbc2024)

What's the matter with my code? Thanks for the help.

**Comment by michaelangeloio** [comment]
Hi @kapsule-studio, unfortunately, the Next 13 App router isn't supported yet :( We're working on this and will keep you updated!

**Comment by kapsule-studio** [comment]
Thanks for the answer. Would it work if I put the API route in a pages/api folder? Next js supports having both App and Pages router at the same time.

**Comment by michaelangeloio** [comment]
please try it! It should work with the pages API routes.
