### ISSUE TITLE
DELETE with react-query client breaks fastify because it sets content-type request header to application/json

### ISSUE THREAD

**Issue by firxworx** [ts-rest/ts-rest#383]
The ts-rest client with react-query erroneously sets the request header "content-type: application/json" for `DELETE` requests that appropriately have an empty body.

I have not tested with the fetch client however it may be impacted as well.

This header behaviour breaks Fastify with its default content type parser. Clients receive an error 500 response.

Internally the error is logged as `FST_ERR_CTP_EMPTY_JSON_BODY`: https://fastify.dev/docs/latest/Reference/Errors/#fst_err_ctp_empty_json_body

This behaviour can be replicated with any API client such as Postman or the VSCode ThunderClient extension: 

- if you send a valid DELETE request to your ts-rest powered Fastify API (e.g. to an endpoint with 'DELETE' method, no body, and receiving an id via params) then it will be accepted fine
- if you add "Content-Type" "application/json" to the request headers and send a similar DELETE request with no body you will produce the same error

The ts-rest client is replicating this exact same error condition with its behaviour of setting "content-type" (note: it looks exactly like that in my network tab, specified in lowercase).

In my contract definition with `method: 'DELETE'` I have `body: null`. If this should be set to something else or a particular zod schema (e.g. `z.void()`) I think that should be clear in the docs (as the typing requires that a `body` property exist) and there should be test cases surrounding this.

---

An undesirable workaround is setting the `body` of the `method: 'DELETE'` contract to `z.object({})` in the contract definition and then specifying an empty object (`{}`) as the body on the client-side in React.

I don't think this workaround should be relied on as I think it defeats the purpose of ts-rest to implement standard RESTful API's that behave the way external/non-ts-rest-client users expect.

---

Issue #307 may be related to this in some way. It is not clear from the OP if they are using Fastify or not.

In researching this issue I found the same problem was faced by React-Admin in the past. Check out the following for context:
https://github.com/zachrybaker/ra-data-rest-client/issues/1

Fastify has had a few related issues here and there in the past e.g. https://github.com/fastify/fastify/issues/297 (see links to other mentions). My understanding is that the maintainers have concluded that the behaviour described in this issue is correct and the error response is warranted.

Thanks for your attention on this issue!

**Comment by michaelangeloio** [comment]
Hi @firxworx , have you tried implementing a custom client?

https://ts-rest.com/docs/core/custom

You can steal the fetch code we've implemented in the core client and modify it to your needs. If this can be solved via a custom client, I think this should be an item for v4. I'm hesitant to touch the core code for reasons like breaking changes/introducing new bugs/etc, which would affect a number of apps.

**Comment by Gabrola** [comment]
I think we can treat both issues separately. For this issue, I think in the fetcher code, we shouldn't pass a content-type header at all if the body is null or undefined. I would treat this as a bug as indeed setting `content-type: application/json` and then not sending a body is incorrect behavior.

So on https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/core/src/lib/client.ts#L229

We should do this

```typescript
  return apiFetcher({
    route,
    path,
    method: route.method,
    credentials: clientArgs.credentials,
    headers: {
      ...(body !== null && body !== undefined && { 'content-type': 'application/json' })
      ...combinedHeaders,
    },
    body:
      body !== null && body !== undefined ? JSON.stringify(body) : undefined, // <-- like this
    rawBody: body,
    rawQuery: query,
    contentType: route.method !== 'GET' ? 'application/json' : undefined,
    signal,
    next,
    ...extraInputArgs,
  });
```

**Comment by michaelangeloio** [comment]
@firxworx should be fixed!
