### ISSUE TITLE
Question: How can I obtain a request-handler's input and output types at compile time?

### ISSUE THREAD

**Issue by laser** [ts-rest/ts-rest#385]
Hi, folks. 

First off - thank you for building such a wonderful library. Our team has really enjoyed working with it.

It appears that the typical way that a developer would implement a contract/router defined with ts-rest is by defining an object literal containing a bunch of functions w/out input or output types:

```ts
import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import { initServer } from '@ts-rest/express';

export const EchoSchema = initContract().router({
  echo: {
    method: 'POST',
    path: '/echo',
    body: z.object({
      call: z.string(),
    }),
    responses: {
      201: z.object({
        response: z.string(),
      }),
    },
  },
});

const router = initServer().router(EchoSchema, {
  echo: async (req) => {
    return {
      status: 201,
      body: {
        response: `you said: ${req.body.call}`,
      },
    };
  },
});
```

In our application, we'd like to use an instance of a _class_ to implement our contract/router:

```ts
import { initContract } from '@ts-rest/core';
import { z } from 'zod';
import { initServer } from '@ts-rest/express';

export const EchoSchema = initContract().router({
  echo: {
    method: 'POST',
    path: '/echo',
    body: z.object({
      call: z.string(),
    }),
    responses: {
      201: z.object({
        response: z.string(),
      }),
    },
  },
});

class Controller {
  public async echo(req: any): Promise<any> {
    return {
      status: 201,
      body: {
        response: `you said: ${req.body.call}`,
      },
    };
  }
}

const router = initServer().router(EchoSchema, new Controller());
```

Does ts-rest provide any mechanism for defining proper types for the methods on our `Controller` class such that we could change `public async echo(req: any): Promise<any>` to something like `public async echo(req: EchoSchema['echo']['input']): EchoSchema['echo']['output']`?

Thanks again for the great library!

**Comment by Gabrola** [comment]
Hi @laser! Glad your team's experience has been great so far.

Have a look at https://ts-rest.com/docs/core/infer-types this should be exactly what you are looking for. So in your case you'll need to use `ServerInferRequest<typeof EchoSchema>` and `ServerInferResponses<typeof EchoSchema>`

**Comment by laser** [comment]
Lovely, thanks a bunch! Apologies for missing that - I should have read the docs closer.

**Comment by laser** [comment]
resolved

**Comment by laser** [comment]
Lovely, thanks a bunch! Apologies for missing that - I should have read the docs closer.

**Comment by laser** [comment]
@Gabrola - One final question: I note that if I use `ServerInferRequest<typeof EchoSchema>['echo']` that the `res` property of the `req` (the Express response) is not available, which means that I can't use request locals. 

If I use `ServerInferRequest`, is there any way to get at that value?

Example:

```ts
class Controller {
  public async echo(req: ServerInferRequest<typeof EchoSchema>['echo']): Promise<ServerInferResponse<typeof EchoSchema>['echo']> {
    console.log(`middleware value: ${req.res.locals.someval}`);

    return {
      status: 201,
      body: {
        response: `you said: ${req.body.call}`,
      },
    };
  }
}
```

**Comment by laser** [comment]
Note: Although passing an instance of `Controller` that uses `ServerInferRequest` and `ServerInferResponses` does compile, the server fails to boot. See [this GitHub issue](https://github.com/ts-rest/ts-rest/issues/386) for more information.
