### ISSUE TITLE
Problem with documentation quickstart

### ISSUE THREAD

**Issue by mrlectus** [ts-rest/ts-rest#390]
for the nextjs example for post.controller.ts `const c = nestControllerContract(apiBlog);` where is the `apiBlog` coming from?

**Comment by michaelangeloio** [comment]
@mrlectus hi there! Can you provide a link to the section you're referring to? TIA!

**Comment by mrlectus** [comment]
> @mrlectus hi there! Can you provide a link to the section you're referring to? TIA!

https://ts-rest.com/docs/quickstart
