### ISSUE TITLE
[@ts-rest/nest] Use of Fastify deprecated property 

### ISSUE THREAD

**Issue by btravers** [ts-rest/ts-rest#392]
I am using `@ts-rest/nest` and `@nestjs/platform-fastify` together.

`@nestjs/platform-fastify@10.2.6` has just been released and includes `fastify@4.23.2`.

Now, `fastify` emits the following log :

```
(node:10341) [FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.
```

**Comment by techgerm** [comment]
> I am using @ts-rest/nest and @nestjs/platform-fastify together.

@btravers do you mind sharing how you're using them together?

I have a NestJS server that I'm trying to move to Fastify but when I do, all of my routes break (understandably so) and I'm not able to find instructions in [the docs](https://ts-rest.com/docs/nest/#single-handler-approach---easy-migration-and-flexibility-%EF%B8%8F) on how to properly set up my router for a NestJS server that uses fastify - maybe I missed it though?

**Comment by btravers** [comment]
I use the [multi handler approach](https://ts-rest.com/docs/nest/#multi-handler-approach---ultimate-type-safety-%EF%B8%8F) with one controller per resource and response validation. 
Also I use it in combination with fp-ts for error handling.

It runs perfectly.

I have only noticed one issue : you have to make sure your pathes are consistent.
You cannot have one route `GET /books/:id` and another `DELETE /books/:bookId`.

I will try to find some free time in the next days to create an exemple I can share.
