### ISSUE TITLE
[feature request] framework agnostic server adapter

### ISSUE THREAD

**Issue by qin-guan** [ts-rest/ts-rest#396]
Hey, thanks for the insane work done on this lib. Would the team be open to building an adapter for fetch / edge runtimes, similar to tRPC [here](https://trpc.io/docs/server/adapters/fetch)? 

This would allow ts-rest to support many more frameworks out of the box (Nuxt, Cloudflare Workers, etc) which would be awesome! I am not familiar with the technical complexity of implementing this, so just throwing the idea around for now

**Comment by Gabrola** [comment]
`@ts-rest/serverless` is now available. No docs yet, but you can see an example here https://github.com/ts-rest/ts-rest/blob/main/apps/example-cloudflare-worker/src/index.ts
