### ISSUE TITLE
pathPrefix is totally ignored on the parent contract

### ISSUE THREAD

**Issue by msalahz** [ts-rest/ts-rest#397]
Hi! I'm using ts-rest with nest.js and I just noticed that pathPrefix is totally ignored on the parent contract, Can you advise?
Here is an example
```js
const nestedContract = c.router(
  {
    getPost: {
      path: '/mypath',
      //... Your Contract
    },
  },
  {
    pathPrefix: '/posts',
  }
);

const parentContract = c.router(
  {
    posts: nestedContract,
  },
  {
    pathPrefix: '/v1',
  }
);
```
 in the example above `/v1/mypath` will return 404 while `/mypath` works fine

**Comment by uooq** [comment]
@msalahz I wouldn't expect `/v1/mypath to work the way you've set this up... you've got the `/posts` path prefix to contend with as well.  Is `/v1/posts/pathPrefix` working for you?
