### ISSUE TITLE
validateResponseOnClient isn't working when specified in AppRouter

### ISSUE THREAD

**Issue by uooq** [ts-rest/ts-rest#398]
The only way to get validateResponseOnClient to work is to specify it it in the AppRoute, it's not being applied to the routes when specified in the AppRouter

I submitted a PR to fix this a couple of days ago but I'm worried that it got overlooked so I'm reporting it as an issue here. 

here's the PR
https://github.com/ts-rest/ts-rest/pull/395

Thanks!

**Comment by michaelangeloio** [comment]
should be fixed with #395

**Comment by michaelangeloio** [comment]
should be fixed with #395
