### ISSUE TITLE
how to extend contract response types

### ISSUE THREAD

**Issue by bingtsingw** [ts-rest/ts-rest#401]
Now, the response type of contract can accept `zod.ZodSchema` or `c.type<>()`, like this:
```
responses: {
  200: c.type<{ posts: Post[]; total: number }>(),
},
```

 I want to pass a [class-transformer](https://github.com/typestack/class-transformer) class, are there any ways to extend it.

**Comment by michaelangeloio** [comment]
hi @bingtsingw ! 

Have you tried passing the class-transformer in that type? Curious to know what it says? 

Perhaps you can derive an interface from the class and pass that?
