### ISSUE TITLE
react-query strictStatusCodes ignored

### ISSUE THREAD

**Issue by sebastienne** [ts-rest/ts-rest#407]
From my understanding, when using `strictStatusCodes` the expectation is that you shouldn't have to assert on status codes not strictly returned from the api in `onError` hooks when using `useMutation`, for example. At least this is how the rest client behaves.

```
const { mutateAsync } = client.contract.route.useMutation({
    onError: (res) => {
      res.status // includes all error statuses
      res.body // type is unknown
```

https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/react-query/src/lib/types.ts#L31

```
// Error response if it's not a 2XX
export type ErrorResponse<TAppRoute extends AppRoute> = ClientInferResponses<
  TAppRoute,
  ErrorHttpStatusCode,
  'ignore'
>;
```

Looks like removing `ignore` in the line above fixes everything, but I can't be sure of its original intention.

**Comment by Gabrola** [comment]
See https://github.com/ts-rest/ts-rest/issues/471#issuecomment-2029049834
