### ISSUE TITLE
NestJS Interceptor receives a Promise instead of resolved data 

### ISSUE THREAD

**Issue by chrber04** [ts-rest/ts-rest#408]
I am using ts-rest in a NestJS application and I've encountered an issue with interceptors. I have an interceptor that is supposed to modify the response before it is sent. However, when I try to access the response data in the interceptor, I get a Promise instead of the resolved data.

Here is a simplified version of my interceptor:

```
@Injectable()
export class MyInterceptor implements NestInterceptor {
	intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
		return next.handle().pipe(
			tap((data) => {
				console.log("data", data);
				// Modify the response...
			}),
		);
	}
}

```

I use the interceptor in a controller method like this (using the single handler approach):

```

@TsRestHandler(c.login)
@UseInterceptors(AuthDataInterceptor)
@UseGuards(EmailPasswordAuthGuard)
async login(@AuthDataFromGuard() authData: AuthData) {
	return tsRestHandler(c.login, async () => {
                // ...
		return {
		  status: 201, 
		  body: authData,
		}
	});
}

```

When I log the tapped data in the interceptor, I get a Promise, not the resolved data. This makes it impossible for me to modify the response as intended. I would expect the interceptor to receive the resolved data, not a Promise.

Is this a known issue, or am I doing something wrong? Any help would be appreciated.

**Comment by GaryGreerKK** [comment]
Having a similar issue also. I had an interceptor to map custom Errors to HttpExceptions. Since upgrading to 3.26.4 and changing over to using tsRestHandler these are now Promises vs Errors so no longer hitting my catchError block.

@chrber04 did you find anything else on this?

**Comment by andronov04** [comment]
The same problem
