### ISSUE TITLE
Exporting `c` freezes IDE/throws typescript error (repro included)

### ISSUE THREAD

**Issue by underfisk** [ts-rest/ts-rest#409]
I've been trying to setup ts-rest with contracts being exported but for that, we'd started by exporting `c` as you would do with `trpc` but that started throwing off errors, such as: `Exported variable 'c' has or is using name 'tag' from external module "/Users/rodrigorodrigues/Documents/project-ember-web/node_modules/.pnpm/@ts-rest+core@3.30.4_zod@3.22.4/node_modules/@ts-rest/core/src/lib/type-utils" but cannot be named.ts(4023)`
Without being able to export we decided to have factory methods that would receive `c` as a parameter and return the contract that feels weird and unnecessary
Ultimately when hovering (using VSCode) over the exported `c` it freezes for a while the IDE and becomes super slow.

The repro has a zod with an empty object on purpose, if you remove that you'll notice that the `contract` object will start throwing an error, for some reason it forces us to import `zod` to silence the error.

Reproduction: https://github.com/underfisk/ts-rest-ts-issue-repro

**Comment by jma1020** [comment]
I have the same problem

**Comment by hngngn** [comment]
By explicitly typing the exported variable `c` as a `ContractInstance`, you can successfully export the contract without encountering the mentioned errors.

```ts
type ContractInstance = ReturnType<typeof initContract>
export const c: ContractInstance = initContract()
```

**Comment by Gabrola** [comment]
`initContract` is actually stateless so you can just import it multiple times and call `initContract()` multiple times whenever you need `c`. This is just vestige from some older versions when it used to be stateful. We will be exporting `c` directly in the next major version.
