### ISSUE TITLE
Allow error handler to handle ZodError too

### ISSUE THREAD

**Issue by egoist** [ts-rest/ts-rest#411]
Zod errors for request headers / body / param are not caught by the `errorHandler` in `ts-rest/next`, 

https://github.com/ts-rest/ts-rest/blob/984b9b5aa229eb60562e7805a3f4bc8666ed0a26/libs/ts-rest/next/src/lib/ts-rest-next.ts#L216

I want to catch the zod error server-side and output it in a custom format.

**Comment by michaelangeloio** [comment]
I believe this PR https://github.com/ts-rest/ts-rest/pull/444 closes this issue. If not, please mention me to re-open it
