### ISSUE TITLE
Question/Request: Easier way to handle "ok" from fetch/react-query in case of 304?

### ISSUE THREAD

**Issue by t1mmen** [ts-rest/ts-rest#412]
Through no (known) explicit action of my own, my NextJS Pages API-based app return `304 Not Modifier` on occasion when I've already made the call to the same endpoint elsewhere on the same page.

This has lead to a few bugs in code such as...

![CleanShot 2023-10-15 at 12 21 37@2x](https://github.com/ts-rest/ts-rest/assets/192263/986208cd-5b78-48b8-b8b4-0750cb05a910)

... not properly setting the state when 304 is returned. While it seems the API does respond with the payload, I believe the HTTP indicates this should not be done, so it's possibly a thing the client-side "fills in" somehow? 

It is unclear to me how to handle this situation with type-safety. This does not work:

![CleanShot 2023-10-15 at 12 21 16@2x](https://github.com/ts-rest/ts-rest/assets/192263/3131cf4f-a053-4ee4-81c8-90f2f0b57c7a)

Is there a correct way to handle this?

If not, perhaps the 200-definitions of a route handler should be (optionally?) aliased on 304 as well?

My contract:
```ts
  getAccountId: {
    method: 'GET',
    path: `/accounts/:accountId`,
    description: 'Gets an account by `accountId`',
    responses: {
      200: AccountSchema,
      ...GenericErrorResponsesSpread,
    },
  },
```

My API implementation:
```ts
  getAccountId: async ({ req, res, params }) => {
    const { supabase, user } = await apiRouteInitializer({ req, res });
    const { data: accounts } = await getAccounts(supabase, {
      userId: user.id,
      accountId: params.accountId,
    });
    if (!accounts.length) return { status: 404, body: { message: 'Account not found' } };
    return { status: 200, body: accounts[0] };
  },
```

**Comment by Gabrola** [comment]
`304` responses are totally transparent to the client, and the client will just see `200`. I believe this is the case for both `fetch` and `axios`
