### ISSUE TITLE
@ts-rest/nest - Add a way to set tags

### ISSUE THREAD

**Issue by IShungite** [ts-rest/ts-rest#416]
Add the possibility to move a route to a specific tag
![image](https://github.com/ts-rest/ts-rest/assets/56173955/a2c6b356-5519-47fc-9a2a-03f194f41014)

**Comment by tr43om** [comment]
This would be super useful, when you need to group api routes by entities

**Comment by pradok** [comment]
Yes this would be very helpful to have the ability of settings tags probably would need to be somewhere when defining contract, but then contract is supposed to be only router. Openapi spec is added on top of it.

**Comment by tr43om** [comment]
I found a way to set tags. You need to group your related path with router:

To define and group your API endpoints using tags in ts-rest, you first need to initialize a contract and define your mutations or queries. You need to group them with a router:

`
const c = initContract();

const getInfo = c.mutation({
 method: "POST",
 path: API_ENDPOINTS.GET_RESOURCES,
 body: schemas.resource.req,
 responses: {
    200: schemas.resource.res,
 },
});

export const resources_collection = c.router({
 [API_ENDPOINTS.GET_RESOURCES]: getInfo,
});
`

After defining your routes for related paths, you group them again into a router, which you pass to the generateOpenApi() method:

`
const c = initContract();

const contract = c.router(
 {
    Facets: facets_collection,
    Contacts: contracts_collection,
    Resources: resources_collection,
    Evaluation: evaluation_collection,
    KPIs: kpis_collection,
 },
);

const openApiDocument = generateOpenApi(contract, {
 info: {
    title: 'Your API Title',
    version: '1.0.0',
 },
});
`

![image](https://github.com/ts-rest/ts-rest/assets/67281226/3fe29111-54c9-4743-b563-0ce2cb02c30f)

**Comment by pradok** [comment]
That was awesome @tr43om . Thanks!
