### ISSUE TITLE
Could I combine multiple Contracts in one Swagger UI Docs?

### ISSUE THREAD

**Issue by razb-viola** [ts-rest/ts-rest#423]
I want to document microservices and I want to have a single api docs for all of them. For example, `Posts` and `Users` microservices. Using the `@ts-rest/open-api` I can only create one OAS (OpenAPI Specification) yaml. Then I have to serve each separately - I want to combine them all together into a single specification yaml file. 

Can I do that? How?

**Comment by oliverbutler** [comment]
If you're contracts are defined in a central location you could combine them into a single super-contract before creating the OAS.

Failing that, I may be mistaken, but isn't it possible to combine multiple OAS's into a single swagger UI?

The resulting JSON blob from `@ts-rest/open-api`'s `generateOpenApi` function can be manipulated by you however you'd like!

**Comment by razb-viola** [comment]
Thanks. And can I define a contract from an existing OpenAPI specification file? 
(I have a swagger.yaml file and I want to produce the ts-node router but without to repeat it)
