### ISSUE TITLE
@ts-rest/nest Multi Handler Approach handler 404 error

### ISSUE THREAD

**Issue by veax** [ts-rest/ts-rest#429]
First of all thanks for the lib, it's great and I would like to use it in my projects.

Unfortunately I'm stuck on implementing Nest controller with Multi Handler Approach. 
For example code below works perfectly with Single Handler Approach and i have response on /api/users endpoint:
```
user.controller.ts

@Controller()
export class UserController {
  constructor(private readonly userService: UserService) {}

  @TsRestHandler(UserAPI.getUsers)
  async getUsers() {
    return tsRestHandler(UserAPI.getUsers, async () => {
      const users = await this.userService.getUsers()

      return { status: 200, body: users }
    })
  }
}

```

however I have 404 error for same endoint in multi handler syntax:
```
user.controller.ts

@Controller()
export class UserController {
  constructor(private readonly userService: UserService) {}

  @TsRestHandler(UserAPI)
  async handler() {
    return tsRestHandler(UserAPI, {
      getUsers: async () => {
        console.log('getUsers endpoint')
        const users = await this.userService.getUsers()
        return { status: 200, body: users }
      },
    })
  }
}
```

As response on /api/users I have:
```
{
"message": "Couldn't find route handler for this path",
"error": "Not Found",
"statusCode": 404
}
```
Can someone guide me what's wrong with my code? I use the same contract in both cases, and controller is imported in module, there's no other changes in code that I mentionned above between 2 approach
Even according to logs endpoint is ready:
```
t] 68030  - 11/04/2023, 7:32:41 PM     LOG [RoutesResolver] AppController {/api}: +10ms
[Nest] 68030  - 11/04/2023, 7:32:41 PM     LOG [RouterExplorer] Mapped {/api, GET} route +2ms
[Nest] 68030  - 11/04/2023, 7:32:41 PM     LOG [RoutesResolver] UserController {/api}: +0ms
[Nest] 68030  - 11/04/2023, 7:32:41 PM     LOG [RouterExplorer] Mapped {/api/users, ALL} route +1ms
[Nest] 68030  - 11/04/2023, 7:32:41 PM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 68030  - 11/04/2023, 7:32:41 PM     LOG 🚀 Application is running on: http://localhost:3000/api
```
It will be helpful if someone has complete example.  [The only one that I found use Single Handler approach](https://github.com/ts-rest/ts-rest/tree/main/apps/example-nest)

**Comment by michaelangeloio** [comment]
I believe the multi handler is completely broken as of now :( 

Would you mind trying the single-handler approach?

**Comment by veax** [comment]
> I believe the multi handler is completely broken as of now :(
> 
> Would you mind trying the single-handler approach?

Yes, I’m using single-handler finally, I leave this issue open for future reference

**Comment by ihusemann** [comment]
Multi handler seems to be working fine for me. 

I ran into a similar issue when I had `globalPrefix` in the Nest.js `main.ts` file.  Since the path defined in the contract is the **full path**, any prefixes defined anywhere in the Nest setup - like in `@Controller("my-path")`, or in `main.ts` - will interfere with the route you're expecting. 

Hope that helps!
