### ISSUE TITLE
Express - per request data attached by middleware

### ISSUE THREAD

**Issue by msikora78** [ts-rest/ts-rest#430]
I really like the idea of this project and I'm evaluating if it would be a good fit for our existing Express API/React UI, however, from the docs it is not clear to me how to handle properties attached to the Express request object by a middleware. 

In our project we parse out headers/cookies in our Auth middleware and attach a `user` object to request like this:

```
    req.user = {
        cid: claims.cid,
        shopperId: claims.shopperId,
        plid: claims.plid,
        isEmployeeAccount,
        currency: req.cookies.currency,
        market: req.cookies.market,
    };
```

These values are something that the client code doesn't need to be aware of at all for the most part, but they are obviously super important on the server. What is the `ts-rest` way to handle this?

Thank you all in advance for your help!

**Comment by cjroebuck** [comment]
@msikora78 I'd also be keen to see how to get ts-rest to be aware of custom properties added to the request by middleware...

**Comment by pthieu** [comment]
@msikora78 or anyone else find a resolution for this?
basically need to attach a user from the auth session, can do it by declaring an extension to my express Request type but can't seem to do it with ts-rest

**Comment by pthieu** [comment]
for anyone reading this, I had to extend my express `Request` type like this:

```ts
declare global {
  namespace Express {
    interface Request {
      // auth: LooseAuthProp['auth'] & { sessionClaims: CustomClerkSessionData };
      user?: User;
    }
  }
}
```

note that I think the TS community is moving away from namespaces but i wasn't able to get it to work using the `declare module 'express'` way
