### ISSUE TITLE
Explicit support for file download

### ISSUE THREAD

**Issue by gjuchault** [ts-rest/ts-rest#431]
Hello!

I think it would be nice for ts-rest to support file download. I've been able to achieve it doing like this:

```ts
const contract = initContract().router({
  downloadFile: {
    method: "POST",
    path: "/download-file",
    body: z.object({
      id: z.string(),
    }),
    responses: {
      200: z.unknown(),
    },
  },
});

function handler() {
  // ...
  return {
      status: 200,
      body: Buffer.from("ABC"),
      headers: {
        "Access-Control-Expose-Headers": "Content-Disposition",
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="file.pdf"`,
      },
    };
}
```

**Comment by michaelangeloio** [comment]
Are you meaning a new API? A bit confused about how we'd implement this? 

Would you mind adding this to our documentation @gjuchault ? Perhaps proper documentation is best for this scenario.

**Comment by damieng57** [comment]
I have the same issue. I would like download a file stored on my server or in mongoDb with GridFs.
The goal is:
- Download file as an attachment file
- If it's an image, display the image directly in the browser

I tried to do something like this:

`export const fileControllers = {
  getFile: {
    middleware: [
      async (req, res, next) => {
        // req.tsRestRoute is typed as the contract route
        const fileId = new ObjectId(req.params.id);

        const { downloadInfo, downloadStream } = await retrieveFile(fileId);

        if (downloadInfo.filename && downloadInfo.contentType) {
          res.setHeader('Content-disposition', `attachment; filename=${downloadInfo.filename}`);
          res.setHeader('Content-type', 'image/png');
        }
        console.log(res);

        downloadStream.pipe(res);
        next();
      },
    ],
    handler: async () => {
      return SuccessResponse();
    },
  },
}`
I also tried to put the code directly in the handle, it's the same. And using Buffer doesn't work (or I don't know how to use correctly)

Contract looks like:

`export const fileContract = c.router({
  // Used to download file or image
  getFile: {
    method: "GET",
    path: `/file/:id`,
    headers: z.object({
      "Content-Type": z.string().optional(),
      "Content-disposition": z.string().optional(),
    }),
    pathParams: z.object({
      id: z.string(),
    }),
    responses: {
      200: z.unknown(),
      404: error,
      405: error,
      500: error,
    },
    summary: "Get a file by id",
  },
})`

If I tried a classic way with express, it works well with this code:

`app.get('/file', async (req, res) => {
  const fileId = new ObjectId(req.params.id);
  try {
    const { downloadInfo, downloadStream } = await retrieveFile(fileId);
    if (downloadInfo.filename && downloadInfo.contentType) {
      res.setHeader('Content-disposition', `attachment; filename=${downloadInfo.filename}`);
      res.setHeader('Content-type', 'image/png');
    }

    downloadStream.pipe(res);
    res.send(SuccessResponse());
  } catch (error) {
    res.status(500).send('Erreur lors du téléchargement du fichier');
  }
});`

If someone knows how to do in the Ts-Rest way.
Thank you

**Comment by damieng57** [comment]
I propose to add these lines in ts-rest-express.ts to handle download file. In the function mainReqHandler:

```
...
...
const statusCode = Number(result.status);

var { Stream } = require('stream');    <<< Add   (should be import at top of file -- it's for the example)
if (result.body instanceof Stream) {     <<< Add
    return result.body.pipe(res.status(result.status));  <<< Add
}     <<< Add

let validatedResponseBody = result.body;
if (options.responseValidation) {
...
...
```

Like that, I just need to return the stream in the response object.

```
return {
  status: 200,
  body: myStream
}
```

In my controller, I can set the headers like that:

```
getFile: async ({ req, res }) => {
    const fileId = new ObjectId(req.params.id);
    const { downloadInfo, downloadStream } = await retrieveFile(fileId);
    res.setHeader('Access-Control-Expose-Headers', 'Content-Disposition');
    res.setHeader('Content-Disposition', `attachment; ${downloadInfo.filename?.originalname}`);
    res.setHeader('Content-type', downloadInfo.contentType);
 
    return {
       status: 200,
       body: downloadStream 
    };
},
```

Don't know if it really in the ts-rest spirit but it works as expected for me. My stream is an instance of GridFSBucketReadStream, but that should also work for a Readable stream (from node fs class)

**Comment by damieng57** [comment]
To be more clear, I made a PR to discuss about this topic: https://github.com/ts-rest/ts-rest/pull/473
