### ISSUE TITLE
`useQuery` is expecting the `queryKey` again in the optional react-query params

### ISSUE THREAD

**Issue by hexcowboy** [ts-rest/ts-rest#442]
with the example here (https://ts-rest.com/docs/react-query)

```ts
const queryResult = client.posts.get.useQuery(
  ['posts'], // <- queryKey
  { params: { id: '1' } }, // <- Query params, Params, Body etc (all typed)
  { staleTime: 1000 } // <- react-query options (optional)
);
```

there's a typescript compiler error:

```
Property 'queryKey' is missing in type '{ staleTime: number; }' but required in type 'UseQueryOptions<...>'.
```

right now the workaround is to just supply the `queryKey` again:

```ts
const queryKey = ['posts'];
const queryResult = client.posts.get.useQuery(
  queryKey,
  { params: { id: '1' } },
  { staleTime: 1000, queryKey } // <- supply it here as well and error goes away
);
```

**Comment by hexcowboy** [comment]
> Do you mind making a PR for a docs? Or do we think this is a bug?

i'm kind of thinking this is a bug. why would the `queryKey` need to be supplied twice?

**Comment by Gabrola** [comment]
`queryKey` is only required in the options in react-query v5. Make sure you have v4 instead as ts-rest is not compatible with v5 yet.
