### ISSUE TITLE
Next.js: Allow custom handling of request validation errors

### ISSUE THREAD

**Issue by dennyferra** [ts-rest/ts-rest#443]
I noticed there are ways to handle request validation errors with express, fastify, and nest (example express: https://ts-rest.com/docs/express/#request-validation-error-handling). However, this capability does not appear to exist with next.js. Would it be possible to add this functionality?

Thanks

**Comment by sebpowell** [comment]
@dennyferra – I was looking for this the other day, thanks for the fix! I'll use that whilst waiting for the PR to be merged in.

**Comment by michaelangeloio** [comment]
Merged!

**Comment by sebpowell** [comment]
@dennyferra @michaelangeloio thank you so much both, going to try using it today.
