### ISSUE TITLE
Body property's type of `tsRestHandler` function is unknown in jest

### ISSUE THREAD

**Issue by maronnjapan** [ts-rest/ts-rest#446]
I have two questions as follows:

1.  I would like to know the reason for setting multiple types in a union for the AppRouteResponses type in libs/ts-rest/core/src/lib/infer-types.ts.
2.  If using a union type is necessary as mentioned in question 1, I would like to know how to enable type completion for the 'body' property in the return value of the tsRestHandler function using jest.

Background for asking the questions:  
I used @ts-rest/nest and wrote test code in NestJS as follows.   
```tsx
it('should return "Hello"', async () => {
    const resultFn = await appController.getHello();
    const result = await resultFn({ headers: {} })
    expect(result.body).toEqual('Hello')
});
```
At this point, the type of the 'body' property becomes 'unknown', preventing access to the properties I want to compare.   
<img width="222" alt="image" src="https://github.com/ts-rest/ts-rest/assets/52373331/67980a61-d534-43ab-aa97-7afaa00b06cf">

I recognize that this is due to setting the following type when defining the AppRouteResponses type in [libs/ts-rest/core/src/lib/infer-types.ts](https://github.com/ts-rest/ts-rest/blob/main/libs/ts-rest/core/src/lib/infer-types.ts#L85). 
```tsx
  | (Or<
      Extends<TStrictStatusCodes, 'force'>,
      And<
        Extends<T, AppRouteStrictStatusCodes>,
        Not<Extends<TStrictStatusCodes, 'ignore'>>
      >
    > extends true
      ? never
      : Exclude<TStatus, keyof T['responses']> extends never
      ? never
      : {
          status: Exclude<TStatus, keyof T['responses']>;
          body: unknown;
        } & (TClientOrServer extends 'client'
          ? {
              headers: Headers;
            }
          : {}));
```  
When I remove the relevant part, type completion works, and I can access the corresponding property.   
<img width="116" alt="image" src="https://github.com/ts-rest/ts-rest/assets/52373331/cf5a172d-bcbc-4440-accc-b49ed5d609ea">

Also, even after removing the relevant part, I think it does not affect the operation of the application.   
Based on these observations, I wanted to understand the reasons for making the AppRouteResponses type a union type.   
If the type is necessary, I would appreciate guidance on how to enable type completion for the 'body' property, which is the return value of the tsRestHandler function.

**Comment by michaelangeloio** [comment]
I think the Nest recommended way to test controllers is outlined here:
https://docs.nestjs.com/fundamentals/testing#end-to-end-testing

My company uses a hybrid approach of incorporating unit tests with supertest (instead of full e2e). We don't necessarily rely on the type inference from the controllers, since that is sort of abstracted away (it'll be hard to get the types, like you show here). Here is some sudo code from one of our tests:

```ts
  let otherService: OtherService
  let dbService: DBService

  beforeEach(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [
        CacheModule.register({
          isGlobal: true,
        }),
      ],
    })
    otherService = moduleRef.get(OtherService)
    dbService = moduleRef.get(DBService)
    loggerSpy = jest.spyOn(clsService.get('logger'), 'info')

    app = moduleRef.createNestApplication()
    await app.init()
  }


 it('should return 200 if all steps are successful', async () => {
      ;(dbService.something as jest.Mock).mockResolvedValue([
        { name: 'create-vcluster', workflow_uid: 'workflow-uid' },
      ])
      ;(otherService.somethingElse as jest.Mock).mockReturnValue('hello')
    // complicated logic you want to test in the controller
      const res = await supertest(app.getHttpServer())
        .post(contract.something.path)
        .send({
          user_id: 'userid',
        })
        .expect(200)
      expect(res.body).toStrictEqual({
        status: 'success',
      })

      expect(dbServiceSpy).toHaveBeenCalledWith({
       somedatahere
      })
    
```

Really, because the controller itself provides compiler type safety, the tests (IMO) should be testing underlying logic that is hard to replicate purely through types.

**Comment by michaelangeloio** [comment]
I will close this for now. Mention me if you don't think this helps!
