### ISSUE TITLE
@ts-rest/open-api: No possibility to set security requirement

### ISSUE THREAD

**Issue by ChLah** [ts-rest/ts-rest#449]
I'm trying to move from just nestjs  with @nestjs/swagger to a ts-rest based approach with the @ts-rest/nest and @ts-rest/open-api package.
Everything so far was working fine but now I'm stuck on how to signal swagger which endpoints to protect with bearer auth.
I was able set the security scheme with the following code since the generate method did not provide the possibility to do so in an atomic expression (as e.g. the DocumentBuilder):
```ts
const securityConfig: SecuritySchemeObject = {
    type: 'http',
    scheme: 'bearer',
    bearerFormat: 'JWT',
  };

openApiDoc.components = {
    ...openApiDoc.components,
    securitySchemes: {
      bearer: securityConfig,
    },
  };
```
where openApiDoc is the `OpenAPIObject` created by calling `generateOpenApi()` on my contract.

I now could protect all routes by setting `openApiDoc.security = [{ bearer: [] }];`
but I need the possibility to set the security requirement on method / controller level since not all endpoints need to be called authenticated.

In @nest/swagger I could set a guard and the authentication method with the respective decorators like
 ```ts
@UseGuards(AuthGuard)
@ApiBearerAuth()
async protectedMethod() {
   ...
}
```

Is there a possibility to do something like that? If not, I unfortunatelly cannot use ts-rest.

Thanks in advance for your reply

**Comment by anatolii-valence** [comment]
it is related to https://github.com/ts-rest/ts-rest/issues/288

**Comment by ChLah** [comment]
Oh I did not see that, thanks for pointing out.
