### ISSUE TITLE
Documentation lacks `pathParams` details

### ISSUE THREAD

**Issue by ihusemann** [ts-rest/ts-rest#465]
There's no clear information in the docs on how to implement `pathParams` in a contract.  It should be clear that `pathParams` expects a zod schema - I think it'd make sense to include an example using `z.coerce.number()` as well. 

Happy to take a swing at updating the docs w/ some guidance on where it'd make sense to include this information. 

Something like:

```ts
export const contract = c.router({
  getUser: {
    method: 'GET', 
    path: '/users/:id', 
    pathParams: z.object({
      id: z.string()
    }), 
    // ...
  }
})

// or, if the ID is a number, use zod coerce:
export const contract = c.router({
  getUser: {
    method: 'GET', 
    path: '/users/:id', 
    pathParams: z.object({
      id: z.coerce.number()
    }), 
    // ...
  }
})
```

**Comment by michaelangeloio** [comment]
Great feedback! I think it would make sense to include this here: https://ts-rest.com/docs/core/fetch#typed-query-parameters

relevant `md` file: https://github.com/ts-rest/ts-rest/blob/a02ea90f5194caf657287c0ddf9d756832013bcd/apps/docs/docs/core/core.md

**Comment by ihusemann** [comment]
@michaelangeloio I wasn't exactly sure how it would fit in to the page you sent.  With #469 I added some details into the Contract page, though I'm of course open to feedback/suggestions.
