### ISSUE TITLE
Unable to create nested contract router with loosing path narrowing

### ISSUE THREAD

**Issue by oliverbutler** [ts-rest/ts-rest#47]
this works
```typescript
const claims = c.router({
  getClaimsForApproval: {
    method: 'GET',
    path: `/partner/:partnerId/claims`,
    responses: { 200: c.response<{ id: string }[]>() },
    query: z.object({
      take: z.number().optional(),
      skip: z.number().optional(),
    }),
  }
});

export const claimServicePartnerApi = c.router({
  claims,
});

```

this doesn't work "path" becomes string
```typescript
export const claimServicePartnerApi = c.router({
  claim: {
    getClaimsForApproval: {
      method: 'GET',
      path: `/partner/:partnerId/claims`,
      responses: { 200: c.response<{ id: string }[]>() },
      query: z.object({
        take: z.number().optional(),
        skip: z.number().optional(),
      }),
    }
 }
});

```

I think it's due to how I'm naïvely applying the Narrow helper, it probably should recursively go though the object...

**Comment by s1njar** [comment]
Are there any updates here ?
Got the same issue when using ts-rest with nestjs.

![image](https://user-images.githubusercontent.com/64329883/194782873-f444c0b5-c279-4a13-9ea4-2269bd3288b4.png)

`TS2339: Property 'params' does not exist on type 'AppRouteShape{ getPost: { method: "GET"; path: "/posts/:id"; responses: { 200: ZodNullable { id: ZodString; }, "strip", ZodTypeAny, { id: string; }, { id: string; }>>; }; summary: "Get a post by id"; }; }>'`

```
export const c = initContract();

const PostSchema = z.object({
  id: z.string(),
});

const postContract = c.router({
  getPost: {
    method: 'GET',
    path: `/posts/:id`,
    responses: {
      200: PostSchema.nullable(),
    },
    summary: 'Get a post by id',
  },
});

const contract = c.router({
  post: postContract
});

export {contract}
```

**Comment by oliverbutler** [comment]
Maybe going to migrate to TS's 4.9 Satisfies for the 4.0 launch 🤔 Should resolve this, I want to avoid super heavy recursive TS generics as much as possible
