### ISSUE TITLE
Zod validation errors break OpenAPI spec - allow 

### ISSUE THREAD

**Issue by LiamMartens** [ts-rest/ts-rest#476]
I couldn't immediately find an issue regarding this. At this time the spec doesn't consider the validation errors which can be returned from ts-rest internally (the zod errors).

This means if you don't  specify them manually in your contract the spec is technically incorrect. I believe there should be 2 options:

1. Automatically include the possible responses due to validation errors in the OpenAPI spec.
2. If (1) is disabled force a `transformValidationError` (or similar) method to be implemented in the server so validation errors can be transformed into the desired response format

**Comment by LiamMartens** [comment]
digging into this more I realized there is a way to handle this in the express and fastify libs using the `requestValidationErrorHandler` override.

Although this doesn't solve the type mismatch between the contract and the actual implementation.

**Comment by Gabrola** [comment]
Well technically it "breaks" the entire contract, not simply the OpenAPI spec. However, ts-rest is not really intended to be a batteries included solution, so we refrain from from doing any kind of behind-the-scenes magic such as automatically including anything into the contract. We are very mindful of making sure that every part of the contract spec and behavior are explicitly expected by ts-rest users.

Also, in reality we do not really expect any well-designed app that would want to have an absolutely comprehensive contract to actually use the default validation response schema as each app will likely have a common error response schema across different error types.

Might be useful though to supply a ready-made schema that can be manually added, so will open a separate issue.
