### ISSUE TITLE
Are the docs outdated or only confusing?

### ISSUE THREAD

**Issue by Farnsi** [ts-rest/ts-rest#479]
I try to use the sources in the docs and have tried to complete the missing information on imports, functions, types, etc. But whatever i do, i will not achieve typesafety in my complete app.

It starts with the "Super Simple Example" on the Introduction page. `client.getPosts` how?
What is `client`? When i use `const client = initClient(router, ...` it has no getPosts.

Sometimes `posts.get`, sometimes `getPosts`, `{ data }`, `'data`, ...
`client.posts.create`, client has no posts.
`const { data } = await client.posts.get();` what is data?

`Inferring Types`, here i am fully out of everything. I only want to use request and response types in my route tests.
Must i really create such complex things for that?

Exists somewhere a simply example of how to use everything in a basic express or fastify environment?
With typesafety including in tests and clients.

Important hint: I would rather not blame anybody, i know how hard it is to write a good documentation. I really think i am the problem and that i am too stupid to understand it. :smile:

**Comment by Talent30** [comment]
https://ts-rest.com/docs/quickstart

**Comment by Gabrola** [comment]
We've done a bit of an overhaul for the docs. They should be a bit better now.
