### ISSUE TITLE
Bug: react-query "No QueryClient set"-error caused by version incompatibility when using 3.33.0

### ISSUE THREAD

**Issue by Dilvan44** [ts-rest/ts-rest#480]
We just had problems setting up the ts-rest react-query client and I wanted to share our experience. Maybe we have done something wrong but maybe someone else has experienced the same.

Our journey started on ts-rest v3.30.5 and tanstack-react-query v5 until we found out that compatibility with the syntax change were only added after the version by #457. So we upgraded to v3.33.0. 

Now the "No QueryClient set"-error appeared the first time. **(ts-rest 3.33.0 / react-query 5)** 

We thought it may be because of react-query 5 so we downgraded to 4. Still the same error. **(ts-rest 3.33.0 / react-query 5)**

Only when we downgraded ts-rest to 3.30.5 it then worked again. **(ts-rest 3.30.5 / react-query 4)**

Did we do something wrong or is this known? We really fell in love to use ts-rest alongside our NX monorepo, and would like to stay up to date with it :)

**Comment by hayedewit** [comment]
I have the same issue

**Comment by fruchtzwerg** [comment]
I was afraid something like this might happen, hence the "not a full migration" disclaimer in the PR.
I'm pretty swamped right now but if someone can provide a reproduction maybe I'll have a look at it.

Haven't checked but you might still be able to use ts-rest with tanstack query v5 by wiring up the client from `@ts-rest/core` yourself:
```ts
const client = initClient(router, {
  baseUrl: 'http://localhost:3334',
  baseHeaders: {},
});
useQuery({ queryKey: ['todos'], queryFn: () => client.todos.getAll() })
```
You will lose some convenience but if upgrading to v5 is more important that should work.

**Comment by Gabrola** [comment]
Fixed in #507, please keep using tanstack query v4

**Comment by jsve** [comment]
I'm not sure this should be closed. 

We are stuck at v. 3.30.5. Upgrading to a newer version of ts-rest/react-query gives the same error as the original poster had. Note that we _are_ using tanstack query v4.

**Comment by Gabrola** [comment]
@jsve please see https://ts-rest.com/docs/react-query#no-queryclient-set-use-queryclientprovider-to-set-one
