### ISSUE TITLE
Feature request: `serializeResponse` instead of `validateResponses`

### ISSUE THREAD

**Issue by nightspite** [ts-rest/ts-rest#481]
Problem:
I want to remove certain values from objects using pre-defined Dto, but currently the only option is to use validatedResponse, that is causing the 500 error, when zod evaluates any value as wrong. 

Example would be having a deletedAt date and forgetting to add nullish to the Dto, that would cause an error saying that the deletedAt cannot be null. It's all right in most cases, but having something like `serializeResponse` would be better in those cases, when you are not sure if some data exists or not or it can be of different type. 

`serializeResponse` would do the same as `validateResponses` but wouldn't throw the error.

Example schemas:
```ts
// ****************
// DATABASE SCHEMA
// ****************
const selectStripePriceSchema = z.object({
  id: z.string(),
  productId: z.string(),
  active: z.boolean(),
  description: z.string().nullable(),
  unitAmount: z.number(),
  currency: z.string(),
  type: z.enum(STRIPE_PRICE_TYPE_ARRAY),
  interval: z.enum(STRIPE_PRICE_INTERVAL_ARRAY),
  intervalCount: z.number(),
  trialPeriodDays: z.number(),
  metadata: z.object({}).optional(),

  createdAt: z.date(),
  updatedAt: z.date(),
  deletedAt: z.date().nullish(),
});
export type StripePriceModel = z.infer<typeof selectStripePriceSchema>;
```

```ts
// ****************
// API SCHEMA (DTO)
// ****************
// GET ALL ACTIVE PRICES
export const stripePriceForPublicDtoSchema = selectStripePriceSchema.pick({
  id: true,
  productId: true,
  active: true,
  description: true,
  unitAmount: true,
  currency: true,
  type: true,
  interval: true,
  intervalCount: true,
  trialPeriodDays: true,
  metadata: true,
});
export type StripePriceForPublicDTO = z.infer<typeof stripePriceForPublicDtoSchema>;
```

**Comment by Talent30** [comment]
This is out of the scope of this project I believe as it destroy the idea of strong end to end type safety.

**Comment by nightspite** [comment]
I read that, thought alright, kind of makes sense. But literally right now I have a case where I have a complicated schema consisting of many nested objects. The schema is used to create the resource and also describes the jsonb field in database. Let's say that you need to add minimum length for some string field. At this point any record that would be returned from the api that has length lower than minimum length would throw an error. That's pointless.
The only solution is to keep different schemas for create and return or just have an option to disable validating it and just serializing it..

**Comment by Gabrola** [comment]
This isn't possible with Zod anyway, `.parse` will throw an error if doesn't pass validation, so there's no way to use the Zod object `.strip()` feature without passing the validation. So indeed, you will either have to build a "less-strict" schema for your API, or use  another custom solution to be able to do this kind of data-stripping without validation. However, this is beyond the scope ts-rest.
