### ISSUE TITLE
Difficulty using ts-rest with Generic React Components and AppRouter in TypeScript

### ISSUE THREAD

**Issue by LudovicGen** [ts-rest/ts-rest#485]
### Description:
I'm currently facing challenges integrating `ts-rest` within a React context, specifically when dealing with generic React components and `AppRouter` handling. The primary objective is to create versatile React components that utilize AppRouter. However, I'm encountering TypeScript errors that pose difficulties in assigning appropriate generic types.

I'm struggling with how to type the component so that I can **pass a route as a Prop** and use the function directly. For example, using **`useInfiniteQuery`** to construct an infinite component.

### Details of the problem :
Ts-rest Version: `3.30.5`
Issue Type: TypeScript errors, struggling to assign correct generic types

### Expected behaviour:
**`some-page.tsx`**
```tsx
<MyComponent keys=["products"] route=client.products.list />
```

**`my-component.tsx`**
```tsx
interface Props {
 keys: QueryKey
 route: ???; // Struggling with the correct typing
}

export function MyComponent({keys, route}: Props) {
   const infiniteQuery = route.useInfiniteQuery(
    keys,
   ({ pageParam: pageParameter = 1 }) => ({
      query: { page: Number(pageParameter) },
      headers: {},
      params: {},
    }),
   )
}
```
### Additional information :
I've attempted to pass a generic type into my component `MyComponent<TappRoute>` and tried typing route as `AppRouteFunctions<TappRoute, ClientArgs>`. In this snippet, I've tried to reproduce the type by importing `AppRouteFunctions` from `ts-rest`. Unfortunately, I haven't achieved satisfactory results.

**Comment by Gabrola** [comment]
I think it will be pretty difficult to get the typing inside `MyComponent` to play nice, so my suggestion is to get type inference for the props themselves working, and then just use `// @ts-expect-error` inside the component itself.

The way I think you could do this is by designing the component to work something like this.

```typescript
<MyComponent queryKey={["products"]} contract={contract} client={client} route="products.list" args={...} />
```

The idea behind using a path for `route`, is that it would be redundant to do something like `route={contract.products.list} query={client.products.list}`, but you can still do that if you want to. Unfortunately, I don't think you can really infer any of the query args from `client.products.list` directly.

You can take inspiration for typing `route` from the `Path` type here: https://github.com/nestjs/config/blob/master/lib/types/path-value.type.ts

You can type the `args` field by using `ClientInferRequest`
