### ISSUE TITLE
Problems with multiple API handlers in NextJS

### ISSUE THREAD

**Issue by vaetas** [ts-rest/ts-rest#486]
Hello,
I am trying to figure out how to use multiple API handlers so I can split API into different functions.

## Goal

My goal is to have this structure

```
pages
└── api
     ├── first
     │      └── [...ts-rest].tsx
     └── second
            └── [...ts-rest].tsx
```

The contract itself looks like this

```typescript
const firstRouter = c.router({
  test: {
    method: "GET",
    path: "/first/test",
    responses: {
      200: z.object({
        message: z.string(),
      }),
    },
    summary: "First Test",
  },
});

const secondRouter = c.router({
  test: {
    method: "GET",
    path: "/second/test",
    responses: {
      200: z.object({
        message: z.string(),
      }),
    },
    summary: "Second Test",
  },
});

export const contract = c.router({
  first: firstRouter,
  second: secondRouter,
});
```

And the function in `pages/api/first/[...ts-rest].tsx` is implemented like this:
```typescript
const router = createNextRoute(contract.first, {
  test: async () => {
    return {
      status: 200,
      body: {
        message: "first result",
      },
    };
  },
});

export default createNextRouter(contract.first, router, {});
```
And finally the client looks like this. I add /api prefix to by baseUrl.
```typescript
export function initApiClient() {
  const client = initClient(contract, {
    baseUrl: `http://localhost:3000/api`,
    baseHeaders: {},
    credentials: "include",
  });

  return client;
}
```

My idea was to split it like this so it can be packaged independently and each individual edge function has smaller size.

## Problem
Calling API like this returns 404 every time. The problem is that ts-rest parses only `test` as path and does not resolve to any server implementation. I assumed that if the request path is like this: `/api/first/test` and my baseUrl mentions `/api` then the final path to resolve would be `/first/test`. However, because the NextJS API route param is only `test` in this case it finds nothing.

Is this the correct behavior? 

I tried to poke in the code to change the way how to parse the URL but I can't find where `baseUrl` is applied. My naive solution would be to get the full path and subtract /api (or other defined base) from it. Is that wrong?

I created a simple project and included @ts-rest/next to play with it. See especially [this line](https://github.com/vaetas/issue-ts-rest-next-multiple-handlers/blob/cb4656ccd39a8b8f083a29af4558c9d54a8ba4b5/next/src/lib/ts-rest-next.ts#L211) where I edited the params list.

https://github.com/vaetas/issue-ts-rest-next-multiple-handlers

Thank you very much!

**Comment by Gabrola** [comment]
You can now use the new app router instead by using `@ts-rest/serverless/next`. Docs are not ready yet but see an example here https://github.com/ts-rest/ts-rest/blob/main/apps/example-next/app/api/app-router/%5B...ts-rest%5D/route.ts
