### ISSUE TITLE
nestjs with ts-rest the body keys and values from the contract always optional

### ISSUE THREAD

**Issue by ElronKarni** [ts-rest/ts-rest#490]
Hey, I'm using NestJS with ts-rest, and I do get type safety for the function declarations. However, for some reason, the body values and keys are always optional.

This is my contract:

import { initContract } from "@ts-rest/core";
import { z } from "zod";

const c = initContract();

const AuthSchema = z.object({
  firstName: z.string(),
  lastName: z.string(),
  email: z.string(),
  password: z.string(),
});

type SignUpResponse = {
  access_token: string;
};

export type UserSignUpBody = z.infer<typeof AuthSchema>;

export const contract = c.router({
  signUp: {
    method: "POST",
    path: "/auth/signup",
    responses: {
      200: c.type<SignUpResponse>(),
    },
    body: AuthSchema,

    summary: "Sign Up New User",
  },
});

and this is my authController :

import { Controller } from "@nestjs/common";
import { AuthService } from "./auth.service";
import { TsRestHandler, tsRestHandler } from "@ts-rest/nest";
import { contract } from "libs/api/contract";

@Controller("auth")
export class AuthController {
  constructor(private authService: AuthService) {}

  @TsRestHandler(contract)
  handler() {
    return tsRestHandler(contract, {
      signUp: async ({ body }) => {
        return {
          status: 200,
          body: await this.authService.signup(body),
        };
      },
    });
  }
}

and for some reason the body keys and values thats coming from the contract is optional,

(parameter) body: {
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
}

**Comment by aradgoller** [comment]
Really interesting

**Comment by hyphaene** [comment]
the tsconfig you use must enforce strictness, otherwise outputed types will get marked as optional.

can you post yout tsconfig.json ?

**Comment by hyphaene** [comment]
https://ts-rest.com/docs/quickstart#create-a-contract

**Comment by ElronKarni** [comment]
> the tsconfig you use must enforce strictness, otherwise outputed types will get marked as optional.
> 
> can you post yout tsconfig.json ?

hey ty for the replay:
im using monorepo with pnpm workspaces:
this is my tsconfig.json inside the nestjs app:
{
  "compilerOptions": {
    "module": "commonjs",
    "declaration": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "target": "ES2021",
    "sourceMap": true,
    "outDir": "./dist",
    "strict": true,
    "baseUrl": "./",
    "incremental": true,
    "skipLibCheck": true,
    "strictNullChecks": false,
    "noImplicitAny": false,
    "strictBindCallApply": false,
    "forceConsistentCasingInFileNames": false,
    "noFallthroughCasesInSwitch": false
  }
}

and this is my tsconfig.json inside the libs app where i have the contract:
{
  "compilerOptions": {
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true
  }
}

**Comment by hyphaene** [comment]
try to toggle the values from 
"skipLibCheck": true,
"strictNullChecks": false, ?

**Comment by SaizFerri** [comment]
`"strictNullChecks": true` did the trick for me @hyphaene
