### ISSUE TITLE
The inferred type of 'handler' cannot be named without a reference to

### ISSUE THREAD

**Issue by cleytoncarvalho** [ts-rest/ts-rest#493]
Hello! This lib is very cool, thank you guys.

I am using pnpm monorepo where I have a nestjs project in one package and my ts-rest contract in another package, when trying to configure a controller with multi handler approach the handler method shows the error:

The inferred type of 'handler' cannot be named without a reference to '../../../../../core-contract/node_modules/@ts-rest/core/src'. This is likely not portable. A type annotation is necessary.

Can someone help me with this? My tsconfig in the contract package is:

{
	"include": [
		"src/**/*.ts"
	],
	"compilerOptions": {
		"baseUrl": ".",
		"outDir": "./dist",
		"target": "ES2020",
		"module": "CommonJS",
		"strict": true,
		"skipLibCheck": true,
		"isolatedModules": true,
		"esModuleInterop": true,
		"forceConsistentCasingInFileNames": true,
		"sourceMap": true,
		"declaration": true,
	}
}

**Comment by cleytoncarvalho** [comment]
I think the problem is related to pnpm, I switched to use npm workspaces and know the problema is solved.

**Comment by jsaunie** [comment]
Same problème but to fixe temporally that I just type my handler with `: Promise<any>` since `NestHandlerImplementation` isn't exported by the package.

```
@TsRestHandler(contract.auth.updatePassword)
    async updatePassword(): Promise<any> {
        return tsRestHandler(contract.auth.updatePassword, async ({ body }) => {
            return {
                status: 200,
                body: await this.authService.updatePassword(body),
            };
        });
    }
```
