### ISSUE TITLE
Add router level metadata

### ISSUE THREAD

**Issue by somaraani** [ts-rest/ts-rest#494]
We can already add metadata to specific routes as outlined in the documentation:

``` 
const c = initContract();
export const contract = c.router({
    getPosts: {
        ...,
        metadata: { role: 'guest' } as const,
    }
});
```

It would be nice if we can set router level metadata by adding it to `RouterOptions`. This would be useful for auth or other useful data for example:

``` 
const c = initContract();
export const contract = c.router({
    getPosts: { ... },
    getComments: { ... }
}, {
    metadata: { role: 'guest' } as const,
});
```

This can work similarly to `validateResponseOnClient` which can be set on both `Router` or `AppRoute` level.

**Comment by Gabrola** [comment]
Resolved in #581
