### ISSUE TITLE
@ts-rest/open-api incompatible with zod-form-data

### ISSUE THREAD

**Issue by hashraf38** [ts-rest/ts-rest#495]
When using `zod-form-data` and creating swagger docs using `@ts-rest/open-api` the following error is thrown at compilation.

`TypeError: Cannot use 'in' operator to search for 'Symbol(Symbol.iterator)' in null`
    `at ../node_modules/zod-form-data/src/helpers.ts:143:29`
    `at Object.refinement (../node_modules/zod/lib/types.js:200:28)`
    `at executeRefinement (../node_modules/zod/lib/types.js:3004:39)`
    `at ZodEffects._parse (../node_modules/zod/lib/types.js:3024:17)`
    `at ZodEffects._parseSync (../node_modules/zod/lib/types.js:129:29)`
    `at ZodEffects._parse (../node_modules/zod/lib/types.js:3043:47)`
    `at ZodEffects._parseSync (../node_modules/zod/lib/types.js:129:29)`
    `at ZodEffects._parse (../node_modules/zod/lib/types.js:3014:48)`
    `at ZodEffects._parseSync (../node_modules/zod/lib/types.js:129:29)`
    `at ZodEffects._parse (../node_modules/zod/lib/types.js:3043:47)`

**Comment by Gabrola** [comment]
The seems to be a a problem specific to `zod-form-data` rather than ts-rest. Plus, there should be no need to use anything like this; each respective backend framework already handles the parsing of form data, so you consume form data as regular `z.object()`s
