### ISSUE TITLE
Export type `FlattenAppRouter` for Global Middleware Use in @ts-rest/express

### ISSUE THREAD

**Issue by abdirahmn1** [ts-rest/ts-rest#497]
Hi, am using `@ts-rest/express` and i would love if the package exported the type `FlattenAppRouter` so that it can be used when defining a global middleware in a separate file.

Take for example an auth middleware:
```ts
import { RequestHandler } from "express"

const auth: RequestHandler = (req, res, next) => {
  const token = req.headers.authorization;

  if (token) {
    // do verification stuff etc.
    next();
  } else {
    res.status(401).json({ error: 'Unauthorized: No token provided' });
  }
};

export default auth;
```

TS will yell if this barebones middleware is used in 
```ts
createExpressEndpoints(tsContract, tsRrouter, app, {
  globalMiddleware: [auth],  //<-- TS yells
});
```
now following the type definition of the `globalMiddleware` option, we can see 
```ts
export type TsRestExpressOptions<T extends AppRouter> = {
    logInitialization?: boolean;
    jsonQuery?: boolean;
    responseValidation?: boolean;
    globalMiddleware?: TsRestRequestHandler<FlattenAppRouter<T>>[];
    requestValidationErrorHandler?: 'default' | 'combined' | ((err: RequestValidationError, req: TsRestRequest<FlattenAppRouter<T>>, res: Response, next: NextFunction) => void);
};
// we need the below type to be exported also to get rid of errors when defining the array of global middlewares
type FlattenAppRouter<T extends AppRouter | AppRoute> = T extends AppRoute ? T : {
    [TKey in keyof T]: T[TKey] extends AppRoute ? T[TKey] : T[TKey] extends AppRouter ? FlattenAppRouter<T[TKey]> : never;
}[keyof T];
```

here's what it would look like now after the export
```ts
import { FlattenAppRouter, TsRestRequestHandler } from "@ts-rest/express"


const auth: TsRestRequestHandler<FlattenAppRouter<typeof tsContract>> = (req, res, next) => {
  const token = req.headers.authorization;

  if (token) {
    // do verification stuff etc.
    next();
  } else {
    res.status(401).json({ error: 'Unauthorized: No token provided' });
  }
};

export default auth;
```
```ts
createExpressEndpoints(tsContract, tsRrouter, app, {
  globalMiddleware: [auth],  //<-- no more TS errors :D
});
```

This will allow users to define their global middlewares in separate files instead being forced to define them inline, This implementation will result in an easy to maintain and frictionless experience with `ts-rest` :+1:

**Comment by Gabrola** [comment]
Just use `TsRestExpressOptions<typeof contract>['globalMiddleware'][number]`
No need to unnecessarily export internal types as this creates limitations when wanting to do backwards compatible changes.

**Comment by soulchild** [comment]
`globalMiddleware` is an optional property, so the `[number]` indexing didn't work for me. 

For anyone coming across this in the future, here's my workaround to make `globalMiddleware` required and get a reusable type for global Express middlewares:

```ts
import type { TsRestExpressOptions } from '@ts-rest/express';

export type ApiGlobalMiddleware = Required<
  Pick<TsRestExpressOptions<typeof contract>, 'globalMiddleware'>
>['globalMiddleware'][number];
```

**Comment by abdirahmn1** [comment]
> `globalMiddleware` is an optional property, so the `[number]` indexing didn't work for me. 
> 
> For anyone coming across this in the future, here's my workaround to make `globalMiddleware` required and get a reusable type for global Express middlewares:
> 
> ```ts
> import type { TsRestExpressOptions } from '@ts-rest/express';
> 
> export type ApiGlobalMiddleware = Required<
>   Pick<TsRestExpressOptions<typeof contract>, 'globalMiddleware'>
> >['globalMiddleware'][number];
> ```
> 

hi @soulchild, this has already been fixed, checkout this [pull request](https://github.com/ts-rest/ts-rest/pull/511) that's been merged.

**Comment by soulchild** [comment]
@abdirahmn1 I was aware of that PR, but all it does is expose `TsRestExpressOptions` which I'm already using in my type. But the type @Gabrola [suggested](https://github.com/ts-rest/ts-rest/issues/497#issuecomment-1993948323) leads to a type error in my code base:

```ts
export type GlobalMiddleware = TsRestExpressOptions<
  typeof protectedApiContract
>['globalMiddleware'][number];
                        // ^ Type 'TsRestRequestHandler<{ ... has no matching index signature for type 'number'.
```

I reckon this is because `globalMiddleware` is typed as an optional property:

<img width="492" alt="Image" src="https://github.com/user-attachments/assets/65a76d36-fc4a-426d-9c79-0e88a911ab23" />

Thus, it could be `undefined` instead of an array of middlewares and `[number]` is not defined for an undefined property. That's why I had to force `globalMiddleware` to be a required property first.

**Comment by abdirahmn1** [comment]
aaah, i see, here's how i solved this in my app using built-in ts utilities

```ts
type GlobalMiddleware = Exclude<TsRestExpressOptions<typeof contract>["globalMiddleware"], undefined>[number];
```

Take care 👍
