### ISSUE TITLE
Split a router in multiple files or variables

### ISSUE THREAD

**Issue by BenoitClaveau** [ts-rest/ts-rest#521]
Hi,

I'm unable to split a router into multiple files or variables. I prefer not to create nested routers.
I'm encountering a TypeScript error because `getPost` is not recognized.

```javascript
const s = initServer();
const getPost = async ({ params: { id } }) => {
    return {
        status: 200,
        body: {
            id: "1",
            title: "my title",
            body: "000"
        }
    };
};
const createPost = async ({ body }) => {
    return {
        status: 201,
        body: {
            id: "1",
            title: "my title",
            body: "000"
        }
    };
};
const router = s.router(contract, {
    getPost,
    createPost
});
createExpressEndpoints(contract, router, app);
```

This code is fine, but I prefer not to have multiple endpoints in a single file.

```javascript
    const s = initServer();

    const router = s.router(contract, {
        // move getPost in routers/post/get.ts
        getPost: async ({ params: { id } }) => {
            console.log(id);
            return {
                status: 200,
                body: {
                    id: "1",
                    title: "my title",
                    body: "000"
                }
            };
        },
        // move getPost in routers/post/create.ts
        createPost: async ({ body }) => {
            return {
                status: 201,
                body: {
                    id: "1",
                    title: "my title",
                    body: "000"
                }
            };
        }
    });

    createExpressEndpoints(contract, router, app);
```

**Comment by BenoitClaveau** [comment]
The code below works, but doesn't seem very conventional.
```javascript
const router1 = s.router(
    { getPost: contract.getPost },
    {
        getPost: async ({ params: { id } }) => {
            console.log(id);
            return {
                status: 200,
                body: {
                    id: "1",
                    title: "my title",
                    body: "000"
                }
            };
        }
    }
);
const router2 = s.router(
    { createPost: contract.createPost },
    {
        createPost: async ({ body }) => {
            return {
                status: 201,
                body: {
                    id: "23",
                    title: "toto",
                    body: "jhjkhk"
                }
            };
        }
    }
);
createExpressEndpoints(contract, { ...router1, ...router2 }, app);
```

**Comment by toteto** [comment]
```ts
```

**Comment by toteto** [comment]
Think you will have success in using the `AppRouteImplementation` type. Also you have the added benefit of having the request and response typed in your routes definitions 😉 

```ts
import { type AppRouteImplementation } from '@ts-rest/express';

const s = initServer();

const getPost: AppRouteImplementation<typeof contract.getPost> = async ({ params: { id } }) => {
    return {
        status: 200,
        body: {
            id: "1",
            title: "my title",
            body: "000"
        }
    };
};
const createPost: AppRouteImplementation<typeof contract.createPost> = async ({ body }) => {
    return {
        status: 201,
        body: {
            id: "1",
            title: "my title",
            body: "000"
        }
    };
};
const router = s.router(contract, {
    getPost,
    createPost
});

createExpressEndpoints(contract, router, app);
```

**Comment by BenoitClaveau** [comment]
Thanks @toteto is what I was looking for.

**Comment by ElhanM** [comment]
> Think you will have success in using the `AppRouteImplementation` type. Also you have the added benefit of having the request and response typed in your routes definitions 😉
> 
> ```ts
> import { type AppRouteImplementation } from '@ts-rest/express';
> 
> const s = initServer();
> 
> const getPost: AppRouteImplementation<typeof contract.getPost> = async ({ params: { id } }) => {
>     return {
>         status: 200,
>         body: {
>             id: "1",
>             title: "my title",
>             body: "000"
>         }
>     };
> };
> const createPost: AppRouteImplementation<typeof contract.createPost> = async ({ body }) => {
>     return {
>         status: 201,
>         body: {
>             id: "1",
>             title: "my title",
>             body: "000"
>         }
>     };
> };
> const router = s.router(contract, {
>     getPost,
>     createPost
> });
> 
> createExpressEndpoints(contract, router, app);
> ```

Works well enough, thanks!!

**Comment by ElhanM** [comment]
Example of how to type the middleware when doing kind of code splitting:
```
const getUserById: {
	middleware: [TsRestRequestHandler<typeof contract.getUserById>];
	handler: AppRouteImplementation<typeof contract.getUserById>;
} = {
	middleware: [
		(req, res, next) => {
			...
		},
	],
	handler: async ({ params: { id } }) => {
		...
	},
};
```

**Comment by ElhanM** [comment]
I have found that the optimal way of having good code splitting with ts-rest is to create multiple instances of whatever you need across different files (be it router or contract), and create separate implementations there for each as if they are all a standalone entity (this way you will also have TypeScript support, pulling all of the built-in types into you code, and not having to explicitly define them like I was doing in my comment above), and then merging all of that into a main router/contract in one file at the end.

Hope this example can help you understand what I am trying to say:
```
// userRouter.ts
import { initServer } from '@ts-rest/express';

const s = initServer();

const getUsersRoute = s.router(
	{ getUsers: contract.getUsers },
	{
		getUsers: async () => {
			// Handler logic here...
		},
	}
);

const getUserByIdRoute = s.router(
    { getUserById: contract.getUserById },
    {
        getUserById: {
            middleware: [
                (req, res, next) => {
                    // Middleware logic here...
                    next();
                },
            ],
            handler: async ({ params: { id } }) => {
                // Handler logic here...
            },
        },
    }
);



const userRoutes = {
    getUserById: getUserByIdRoute.getUserById,
    getUsers: getUsersRoute.getUsers,
};

export default userRoutes;

// postsRouter.ts
import { initServer } from '@ts-rest/express';

const s = initServer();

const getPostsRoute = s.router(
    { getPosts: contract.getPosts },
    {
        getPosts: async () => {
            // Handler logic here...
        },
    }
);

const postsRoutes = {
    getPosts: getPostsRoute.getPosts,
};

export default postsRoutes;

// mainRouter.ts
import { initServer } from '@ts-rest/express';
import userRoutes from './userRouter';
import postsRoutes from './postsRouter';

const s = initServer();

const mainRouter = s.router(contract, {
    ...userRoutes,
    ...postsRoutes,
    // Add other routes here...
});

export default mainRouter;

// server.ts
import express from 'express';
import { createExpressEndpoints } from '@ts-rest/express';
import mainRouter from './mainRouter';
import { contract } from './contract'; // Assume this is already defined

const app = express();

createExpressEndpoints(contract, mainRouter, app);

app.listen(3000, () => {
    console.log('Server is running on port 3000');
});


```

Use this same logic in the contract.

Keep in mind, this pseudocode is just an example of the thought process behind the implementations. If you can understand logically how it works, then you are good to go. 

```
// usersContract.ts
import { initContract } from '@ts-rest/core';

const c = initContract();

const getUsersContract = c.router({
    getUsers: {
        method: 'GET',
        path: '/users',
        responses: {
            200: { description: 'List of users' },
            404: { description: 'Not found' },
            500: { description: 'Internal server error' },
        },
        summary: 'Get all users',
    },
});

const getUserByIdContract = c.router({
    getUserById: {
        method: 'GET',
        path: '/users/:id',
        responses: {
            200: { description: 'User details' },
            404: { description: 'User not found' },
            500: { description: 'Internal server error' },
        },
        summary: 'Get a user by ID',
    }
});

export const usersContract = {
	getUsers: getUsersContract.getUsers,
	getUserById: getUserByIdContract.getUserById,
};

// postsContract.ts

const getPostsContract = c.router({
    getPosts: {
        method: 'GET',
        path: '/posts',
        responses: {
            200: { description: 'List of posts' },
            404: { description: 'Not found' },
            500: { description: 'Internal server error' },
        },
        summary: 'Get all posts',
    },
});

const postsContract = {
    getPosts: getPostsContract.getPosts,
};

// mainContract.ts

export const contract = c.router({
    ...usersContract,
    ...postsContract,
});
```

@Gabrola This should really be in the docs, someplace easy to find.

**Comment by Gabrola** [comment]
@ElhanM I agree, we need to have a separate clear section in the docs about contract and router splitting - mainly to document the capabilities rather than be opinionated on how to split and re-combine the contracts or routers.

Regarding your code snippet, you can use `c.query` or `c.mutation` (currently undocumented and needs to be added to the docs) to define singular route definitions rather than have redundant names by doing `const getUserByIdContract = c.router({ getUserById: { ... } })`. However, I do not see the point in splitting up the definitions if they are still going to be kept in the same file like in your example - seems like extra effort to me, but anyone should do it however they please. Hence, why we'd just prefer to just document the capability and not be opinionated on the organization of the code.

There is a similar helper function in all server libraries to do the same for route implementations using `s.route` instead of `s.router`.

**Comment by ElhanM** [comment]
@Gabrola They are not in the same file, that is the whole point. Coding the routes/contracts this way allows us to define them in different files, and import/merge all of them together in the end. I put all of the code route/contract code into the same code block for simplicity, but I have comments in place that indicate they should be different files.

I now notice that I forgot to add exports to the routes/contracts, maybe that part was confusing (I put this together quickly, and did not bother going over it too much)

I will update my original comment with exports in place
