### ISSUE TITLE
❓ Doc improvement

### ISSUE THREAD

**Issue by ghoullier** [ts-rest/ts-rest#54]
Hi @oliverbutler

Thanks for this very interresting project.

Have you an example to integrate `@ts-rest/open-api` with `@ts-rest/express` ?

EDIT:

Below my local implementation

```ts
import { contract } from "./contract";
import { generateOpenApi } from "@ts-rest/open-api";
import { serve, setup } from "swagger-ui-express";

const openapi = generateOpenApi(contract, {
  info: { title: "Play API", version: "0.1" },
});

const apiDocs = Router();

apiDocs.use(serve);
apiDocs.get("/", setup(openapi));

app.use("/api-docs", apiDocs);

createExpressEndpoints(contract, router, app);
```

**Comment by oliverbutler** [comment]
Hey @ghoullier! How you've done it here looks perfect, to be honest, does it work as you expect?

I was just saying in #53 that I want to improve the `@ts-rest/open-api`, can I clarify, does this code snippet above work as expected?

**Comment by ghoullier** [comment]
It works, but one point frustrate me, I cannot validate parameters using zod schema.

**Comment by oliverbutler** [comment]
Hmm interesting, I wouldn't have thought we'd want Zod support for the path params, to be honest, they're always strings, and can't be missing or wouldn't match the route.

Of if Zod is ideal, how would you imagine the API to look? I'd love the feedback to create something!

![Uploading Screenshot 2022-09-16 at 20.08.08.png…]()

**Comment by ghoullier** [comment]
It can be useful to validate and/or coerce params

**Comment by oliverbutler** [comment]
I'd be interested to see an example of where you'd use this, it's not something I've needed much, but I'm interested!


For the contract API, potentially something like this?

```typescript
updatePost: {
    method: 'PATCH',
    path: `/posts/:id`,
    pathParams: z.object({
      id: z.string().transform(Number),
    }),
    responses: { 200: PostSchema },
    body: z.object({
      title: z.string().optional(),
      content: z.string().optional(),
      published: z.boolean().optional(),
      description: z.string().optional(),
    }),
    summary: 'Update a post',
  },
```

or 

```typescript
 updatePost: {
    method: 'PATCH',
    path: `/posts/:id`,
    pathParams: (params) => ({
      id: Number(params.id),
    }),
    responses: { 200: PostSchema },
    body: z.object({
      title: z.string().optional(),
      content: z.string().optional(),
      published: z.boolean().optional(),
      description: z.string().optional(),
    }),
    summary: 'Update a post',
  },
```

**Comment by ghoullier** [comment]
This one is pretty nice

```ts
updatePost: {
    method: 'PATCH',
    path: `/posts/:id`,
    pathParams: z.object({
      id: z.string().transform(Number),
    }),
    responses: { 200: PostSchema },
    body: z.object({
      title: z.string().optional(),
      content: z.string().optional(),
      published: z.boolean().optional(),
      description: z.string().optional(),
    }),
    summary: 'Update a post',
  },
```

**Comment by ecyrbe** [comment]
if i may add some tips here.   
since path params are strings, you can add regex validation integrated like express does.  

```ts
updatePost: {
    method: 'PATCH',
    path: `/posts/:id([0-9]+)`,
    responses: { 200: PostSchema },
    body: z.object({
      title: z.string().optional(),
      content: z.string().optional(),
      published: z.boolean().optional(),
      description: z.string().optional(),
    }),
    summary: 'Update a post',
  },
```

I tell this, because adding a zod schema for just strings seems like overkill.  
if you put a number, i should be coerced automatically to a string (no need to add a zod transform)
and regexpr should validate your pattern.

**Bonus**: the express library that does this is separated : 
https://www.npmjs.com/package/path-to-regexp

**Comment by ghoullier** [comment]
`zod` contains primitive to support uuid validation,  regexp and more. Zod also support coercion with preprocess.

**Comment by oliverbutler** [comment]
I kinda prefer Zod in this case, it feels like one less dependency, plus it means users can use any custom behaviour/transformers they may want in Zod.

Great shout on inline regex @ecyrbe though, we could consider that...

**Comment by oliverbutler** [comment]
Implemented this feature @ghoullier , thanks for the idea I went with Zod and "pathParams" ❤️
