### ISSUE TITLE
ts-rest Middleware called after specific Route

### ISSUE THREAD

**Issue by ElhanM** [ts-rest/ts-rest#544]
In the [docs][1], we can see how to create a middleware that is called before a specific route.

```
import { initServer } from '@ts-rest/express';
import { contract } from './contract';

const s = initServer();

const router = s.router(contract, {
  getPost: {
    middleware: [
      (req, res, next) => {
        // req.tsRestRoute is typed as the contract route
        console.log('Called: ', req.tsRestRoute.method, req.tsRestRoute.path);
        // prints: Called: GET /posts/:id
        next();
      }
    ],
    handler: async ({ params: { id } }) => {
      const post = prisma.post.findUnique({ where: { id } });

      return {
        status: 200,
        body: post ?? null,
      };
    }
  },
});

createExpressEndpoints(contract, router, app);
```

But, does anyone know of a way to create a middleware that is called after a specific route?

Same goes for the global middleware (see docs), is there a way to create a global middleware that is called after all routes?

  [1]: https://ts-rest.com/docs/express/middleware

**Comment by ElhanM** [comment]
@Gabrola How do we implement error handling middleware using ts-rest?

Something similar to this:
```
const express = require('express');
const app = express();

app.use(normalMiddleware);
app.get('/', (req, res) => {
  try {
    // Some route handling code
  } catch (err) {
    next(err); // Pass the error to the next middleware
  }
});
app.use(errorHandlerMiddleware);
```

**Comment by Gabrola** [comment]
@ElhanM yes, that is correct, but no need wrap your own code in `try/catch`, as ts-rest will already do that and call `next(err)`

**Comment by ElhanM** [comment]
@Gabrola does ts-rest provide developers with a way to customize the error handling function built into ts-rest (for example if I want to change the response returned to me from the error)?

**Comment by ElhanM** [comment]
@Gabrola Is it even possible to create custom error handling middleware using ts-rest (or something similar to that)

As I saw, you cannot pass next() to the handler function of a route

Can you provide me with some examples?

**Comment by Gabrola** [comment]
ts-rest doesn't handle any errors or form responses for errors thrown from inside route handler. Just throw anything inside your route handler, and it will be passed to your error handler in `app.use(...)`. If you want to customize the error response from failing request validation you check that [here](https://ts-rest.com/docs/express/#request-validation-error-handling)

**Comment by ElhanM** [comment]
I will take a look at this later, thank you so much @Gabrola ❤️
