### ISSUE TITLE
More detailed error context

### ISSUE THREAD

**Issue by ivan-kleshnin** [ts-rest/ts-rest#562]
Hello! Digging `ts-rest` for the first time. I like the API a lot, feels cleaner than Zodios (and not even comparable to tRPC complexity). There's one thing I've noted.

In Zodios Server implementation the error response is contextualized:

```json
{
  "context": "body"
  "error": [{"path": "filters", ...}, ...]
}
```

In Ts-Rest it's not clear WHICH part of request has the error:

```json
{
  "issues": [{"path": ["filters"], ...}, ...]
}
```

^ it can be a path placeholder, a query variable or a body field. IMO either `context` like in Zodios should be present or (alternatively) `path` can be prepended with one of 3 clarifying constants, e.g.:

```json
{
  "issues": [{"path": ["body", "filters"], ...}, ...]
}
```

What do you think?

**Comment by Gabrola** [comment]
This is already possible with all the server libraries through different options. Which server library are you using?

**Comment by ivan-kleshnin** [comment]
Thank you! After I learned it's possible it was easy to find a starting point here: https://ts-rest.com/docs/express/#request-validation-error-handling

Here's an example for other potential seekers:
```ts
createExpressEndpoints(contract, mainRouter, app, {
  requestValidationErrorHandler: (err, req, res, _next) => {
    return res.status(400).json({
      context: (
        err.body ? "body" :
        err.pathParams ? "pathParams" :
        err.query ? "query" :
        err.headers ? "headers" : "unknown"
      ),
      issues: err.body?.issues || err.pathParams?.issues || err.query?.issues || err.headers?.issues,
    })
  },
})
```

I'm shocked there's even a header validation 🤯 , great work Youssef!
