### ISSUE TITLE
Export a Zod response schema that matches the request validation error responses

### ISSUE THREAD

**Issue by Gabrola** [ts-rest/ts-rest#582]
Related to #476 

Would be a good idea to export a Zod response schema that can be added by ts-rest users to their contracts if they decide to keep the default request validation error responses.

Important to note that we have different formats, see https://github.com/ts-rest/ts-rest/blob/308b966/libs/ts-rest/express/src/lib/ts-rest-express.ts#L257-L276

**Comment by ankiiisharma** [comment]
hey @Gabrola , can you please elaborate this more? like what exactly do you want?
