### ISSUE TITLE
Express contract errors are associated with handlers rather than exact code places

### ISSUE THREAD

**Issue by ivan-kleshnin** [ts-rest/ts-rest#587]
I'm trying to migrate an app from **Zodios** to **TS-REST**. 

I've noticed that, in the server code (uses`@ts-rest/express`), all contract errors are attached to / appear on handlers. For example:

```ts
// contract
export const contract = c.router({
  updateProfile: {
    method: "PUT",
    path: "/profile/update",
    body: z_updateProfileBody,
    responses: {
      ...
      404: z.object({message: z.literal("Not Found)}), // 👈 Expecting "Not Found" literal
    },
  }, 
})
```

```ts
// server
s.router(contract, {
  updateProfile: async ({body, req, res}) => { // ❗the error is displayed here
    ...
    return {status: "404", message: "some other message"} // 👈 instead of here
  })
})
```

It happens with both `{name: handler}` and `{name: {middleware, handler}}` interfaces.

The issue is that for larger handlers it gets quite inconvenient to scroll up, hover on handler, scroll the error popup, remember the name of the variable, close the popup, scroll down, try to fix, repeat... – every time there's an error. 

Instead of noticing the error directly under the line it was triggered by. I'm not sure if it's possible to fix, I had similar issues myself with complex TS types and it was very tricky. I'm sure this case has a proper term which I didn't use, but I'm not a TypeScript expert, sorry.

*I can make a code sandbox, if necessary.* 

It behaves differently (properly) in Zodios, I've just rechecked one more time to be sure.

**Comment by ivan-kleshnin** [comment]
Maybe an explicit return type would help to pinpoint the error 🤔?

**Comment by Gabrola** [comment]
@ivan-kleshnin if you would like to do that, then sure, you can explicitly define the return type using `Promise<ServerInferResponses<...>>` but that's just worsening the DX.
