### ISSUE TITLE
Boolean query parameter always true

### ISSUE THREAD

**Issue by GraceG7** [ts-rest/ts-rest#589]
### Describe the bug

I've recently upgraded from version version 3.30.1 to 3.41.2 and I've noticed a potential bug with the boolean query parameter

Here's my the query parameter defined in the contract

```
method: 'GET ',
path: "get-something",     
query: z.object({
        show: z.coerce.boolean(),
}),
responses: {
     200: c.type<any>()
}
```

In my ts rest handler that is implementing this endpoint, r.query.show is always true despite passing false to it.

I've inspected the network request and it shows that the value false is sent to the api on the show query param so I'm very confident that there isn't an error on where it is called.

Thanks in advance for the help

### Code reproduction

```ts
// Add your code reproduction here
```

### ts-rest version

3.41.2

**Comment by robert-king** [comment]
I think this is because Boolean('false') is truthy, if so, can probably close this

**Comment by GraceG7** [comment]
Curious to know why it used to work in previous version in this case

**Comment by Gabrola** [comment]
You can only use string types for query parameters unless you enable [`jsonQuery`](https://ts-rest.com/docs/core/#json-query-parameters)
