### ISSUE TITLE
No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by alex-way** [ts-rest/ts-rest#590]
### Describe the bug

When trying to run the simple example repo: https://github.com/ts-rest/example-next with the dependencies updated to latest you run into an error: "No QueryClient set, use QueryClientProvider to set one"

### How to reproduce

1. Clone https://github.com/alex-way/ts-rest-bug
2. pnpm i
3. pnpm dev
4. Go to http://localhost:3000

### Expected behavior

The pokemon data loads as expected

### Code reproduction

https://github.com/alex-way/ts-rest-bug

### ts-rest version

3.44.1

**Comment by Gabrola** [comment]
You are using `@tanstack/react-query` v5 which is not supported yet. Install v4 instead.

**Comment by kristian-nst** [comment]
Borrowing this issue. v5 is supported now yes? I get the same error.


    "@tanstack/react-query": "5.56.2",
    "@ts-rest/react-query": "3.51.0",

any ideas?
