### ISSUE TITLE
Add support/docs for listenTerminalRoute (SSE)

### ISSUE THREAD

**Issue by kristianmandrup** [ts-rest/ts-rest#594]
**Is your feature request related to a problem? Please describe.**

I'm trying to use `@ts-rest/fastify` with Server Side Events (SSE). It was unclear if or how I could do it.
I found the following snippet as part of the `@ts-rest/fastify` implementation and it seems to allow `reply` as an option argument for the `routeImpl` which was not clear. This should let me do `reply.sse(...)`

```ts
const registerRoute = (routeImpl, appRoute, fastify, options) => {
    if (options.logInitialization) {
        console.log(`[ts-rest] Initialized ${appRoute.method} ${appRoute.path}`);
    }
    fastify.route({
        method: appRoute.method,
        url: appRoute.path,
        handler: async (request, reply) => {
            const validationResults = validateRequest(request, reply, appRoute, options);
            let result;
            try {
                result = await routeImpl({
                    params: validationResults.paramsResult.data,
                    query: validationResults.queryResult.data,
                    headers: validationResults.headersResult.data,
                    request,
                    body: validationResults.bodyResult.data,
                    reply,
                    appRoute,
                });
            }
```

ChatGPT helped me out, suggestion the following routeImpl code for my use case

```ts
// Route handler function for listening for terminal output updates via SSE
export async function listenTerminalRoute(
  { params }: FastifyRequest<{ Params: RouterListenTerminalParams }>,
  reply: FastifyReply
): Promise<RouterListenTerminalResult> {
  const { sessionId, channel } = params;

  // Check if the sessionId is valid
  if (!userSessions.has(sessionId)) {
    return { status: 400, body: { message: "Invalid sessionId" } };
  }
```

**Describe the solution you'd like**

Please make this feature capability more clear in the docs, perhaps with an example in the docs or the code. Thanks
I'll try it out myself now.

**Describe alternatives you've considered**

You could also perhaps also add a thin wrapper for SSE in the SDK/API?

**Additional context**

**Comment by Gabrola** [comment]
SSE is beyond the scope of ts-rest as event schemas are inherently not defined by paths, headers, or anything similar.
