### ISSUE TITLE
support middleware in @ts-rest/fastify similar to @ts-rest/express

### ISSUE THREAD

**Issue by outofthisworld** [ts-rest/ts-rest#603]
Would be nice to have fastify also support middleware being added like the express version of the package.

Without middleware, we are kinda forced to either not use the package or create our own middleware chain. There's also no way to supply configuration to a particular route, making global middleware provided by fastify esentially useless.

I might be missing something, but the docs are limited so

**Comment by atresnjo** [comment]
also looking for this

**Comment by da-max** [comment]
I also think it would be a good feature.

**Comment by Gabrola** [comment]
Solved in #265
