### ISSUE TITLE
Subscriptions/Websockets Support

### ISSUE THREAD

**Issue by joelbqz** [ts-rest/ts-rest#607]
**Is your feature request related to a problem? Please describe.**
I'd like to implement realtime on my app

**Describe the solution you'd like**
Subscriptions, eg https://trpc.io/docs/subscriptions

**Describe alternatives you've considered**
tRPC server

**Comment by digisomni** [comment]
I came here shopping for the same reason, tRPC is such a pain to get working and I was hoping for a simpler implementation.

**Comment by LeulAria** [comment]
oh it would be cool, may be if any unofficial recommendation guy's if any ?

**Comment by shivangrathore** [comment]
Socket.io v3 introduces first class support, maybe you find this useful. https://socket.io/docs/v4/typescript/
