### ISSUE TITLE
Using cache-manager's auto-caching responses in Nest results in empty cache content.

### ISSUE THREAD

**Issue by Codfisher** [ts-rest/ts-rest#608]
### Describe the bug

When using CacheInterceptor, the response data of the first request is normal, but the response data of the second request becomes empty.

### How to reproduce

The usage follows the documentation as described:
https://docs.nestjs.com/techniques/caching#auto-caching-responses

### Expected behavior

Cache content should not be empty.

### Code reproduction

```ts
@UseInterceptors(CacheInterceptor)
@Controller()
export class SingleDataController {
  constructor(
    ...
  ) { }

  @TsRestHandler(singleDataContract.get, {
    validateResponses: true
  })
  async get() {
    return tsRestHandler(singleDataContract.get, async () => {
      const [error, data] = await to(this.singleDataService.get());
      if (error) {
        throw new HttpException(
          'error message',
          HttpStatus.INTERNAL_SERVER_ERROR,
        );
      }

      return {
        status: 200,
        body: data.toJSON(),
      };
    });
  }
}
```

### ts-rest version

3.30.4

**Comment by Gabrola** [comment]
@Codfisher I am unable to replicate, and using cache manager works for me on my end

**Comment by Gabrola** [comment]
@Codfisher I am unable to replicate, and using cache manager works for me on my end. Please post an example repo with your problem
