### ISSUE TITLE
Type inference does not work in TS 5.5

### ISSUE THREAD

**Issue by AkisArou** [ts-rest/ts-rest#618]
### Describe the bug

ts-rest type inference does not work with latest TS version 5.5.2
(Some other libraries have this kind of problem also)

### How to reproduce

Just run the simplest example of yours with TS version 5.5.2, using initClient

### Expected behavior

Should work as in TS 5.4.5

### Code reproduction

createPost is `any` at the example below

```
export const client = initClient(apiBlog, {
	baseUrl: "",
	baseHeaders: {},
});

client.createPost({
	body: {
		content: "",
		title: "",
	},
});
```

### ts-rest version

3.45.2

**Comment by Gabrola** [comment]
https://www.typescriptlang.org/play/?ts=5.5.2#code/JYWwDg9gTgLgBAbzsAdsGBhCKZQIYDGMANMmpgDbACmOcAvnAGZQQhwDkAAjAM4C0UarxgB6AtGocA3AChQkWIjgAvBs1bsOKiABMZs2RJQi4BOAF4y6LDnxEAFAEo5s6gA9F8Y6eO5C8FYEAHSsAK4w1FAOCLJwZkJ4kQAKECIAXIhx8XAg1DAAFnqZHMkA8gDKACocxNnxYEkFJaKQIry19XBCvJAmwpmxOTkATAAMAIyZKsEQAEYAVtSOQ8M5wLrTwSJQqADmznVrOTDoFNRbO-uHXcNzegCel7jXTkdr9G9d9O-x97pPVSzRbLGAxW5wU4wc7PXYoA5fY7-QEzK7wm7DT6-OC8MIgEB4KCAjgYRKROB4OBtGCdeI-bIEMnUVIiZIUPCoQZdPKFYqccrVWk5RqFFrUjrYnp9XgDLLHcZTIHzJYrCHxDaw17Y4ZQmFAtEI7U5ZGa9GIj7munYk1mYIwB5gagAHlWOrOFxxL3hciRj0yBp9OXoAD4MTlcfjCcTSdQktQKVS0jT3vTPq4PF4zNhfFRaIFrJQaDgHH57CQsgBIOZ4GUAVSgFEyACIm3UqzXqAAJWO6KK8QaplyGAi5nDBRmxlJJ8FVv1yk7u5tVd2tro2psAIUeTdkFcHrhHRZg46ZLJgbI5KBnNtdkMXcCby+h1FXdznm+3u-3QA

The types are resolved correctly in the TS Playground, meaning that this is a problem with your IDE's TS Language Server.

**Comment by ArnaudTA** [comment]
I have the same problem I have to downgrade TS to v5.4.5
at the end of declaration file
```ts
export declare const getApiClient: (baseUrl: string, baseHeaders: Record<string, string>, api: ApiFetcher | undefined) => Promise<{
    Clusters: {
        listClusters: any;
    };
    Environments: {
        createEnvironment: any;
        getEnvironments: any;
        updateEnvironment: any;
        deleteEnvironment: any;
        ...
```

**Comment by christian-bromann** [comment]
> meaning that this is a problem with your IDE's TS Language Server.

That is correct, I tried many things to resolve this without success. My setup is pretty general so I assume many folks run into the same issue. I ended up downgrading to TS 5.4.5 again.

**Comment by AkisArou** [comment]
I use NVim with vtsls with wraps the vscode ts extension. I assume it will be resolved for me too sometime if it is fixed in a nightly vscode build
