### ISSUE TITLE
Docs mention tRPC instead of ts-rest

### ISSUE THREAD

**Issue by c-ehrlich** [ts-rest/ts-rest#64]
The docs mention tRPC instead of ts-rest in some places, for example the first word of the introduction. 

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/8353666/191584768-c2aad969-8dd2-47a7-a6fc-68d5a191050a.png">

**Comment by oliverbutler** [comment]
I thought I fixed this ages ago, good catch, these two names regrettably mix up in my brain!
