### ISSUE TITLE
Call reply.send before return causes ERR_HTTP_HEADERS_SENT error

### ISSUE THREAD

**Issue by 5d-jh** [ts-rest/ts-rest#641]
### Describe the bug

On fastify, call reply.send before return causes ERR_HTTP_HEADERS_SENT error.

### How to reproduce

Call `reply.send` before handler returns.

### Code reproduction

```
getLargeJson: async ({ params, reply }) => {
      const readable = await someService.getData()

      return reply
        .status(200)
        .type('application/json')
        .send(readable);
    }
```

### ts-rest version

"@ts-rest/core": "^3.45.2",
"@ts-rest/fastify": "^3.45.2",
"@ts-rest/open-api": "^3.45.2",

**Comment by Gabrola** [comment]
You're not supposed to call `.send` yourself; ts-rest does it for you, just `return { status: 200, body: readable }` instead.

**Comment by 5d-jh** [comment]
I should've created this ticket as a feature request. That's the workaround but it fails type checking.

Also, ts-rest allows handlers to return reply object. I wonder if it is intended since there is no way to respond if you return the object.

**Comment by 5d-jh** [comment]
Also, sending before return still needed for utilize plugins. `@fastify/compress`, for example, supports `reply.compress` method which causes the error when using inside ts-rest handler.

**Comment by greg-atomic** [comment]
> You're not supposed to call .send yourself; ts-rest does it for you, just return { status: 200, body: readable } instead.

There are valid cases when additional tasks have to be run after the response, that the client shouldn't wait for. This case you are actually supposed to do that, so I suggest to reopen this issue.

Other frameworks also support this behavior, like for example Express.js enables using res.send and have additional code in the req handler. Another example: FastAPI has the BackgroundTask feature for this purpose.
