### ISSUE TITLE
Wrong file extension for router.esm and types.esm

### ISSUE THREAD

**Issue by bordeo** [ts-rest/ts-rest#655]
### Describe the bug

```
Module not found: Can't resolve './router.esm.mjs'
Module not found: Can't resolve './types.esm.mjs'
```

Package @ts-rest/serverless@3.49.1 includes `router.esm.js` and `types.esm.js` files instead of `router.esm.mjs` and `types.esm.mjs`
https://www.npmjs.com/package/@ts-rest/serverless?activeTab=code

### How to reproduce

- Use `next@15-rc`  
- Install `@ts-rest/serverless/next`  
- Create a route `/app/api/bff/[...ts-rest]`  
- Use `import { createNextHandler } from "@ts-rest/serverless/next";`  
- Fetch `/api/bff/something`
- An error occurs

### Code reproduction

```ts
import { bffContract } from "@/contracts/bff-contract";
import { createNextHandler } from "@ts-rest/serverless/next";

const handler = createNextHandler(
  bffContract,
  {
    orders: async ({ params, query }) => {
      console.log("running orders");
      return {
        status: 200,
        body: {
          ...params,
          ...query,
          deleteMe: "response validation will delete me :(",
        },
      };
    },
  },
  {
    basePath: "/api/bff",
    jsonQuery: true,
    responseValidation: true,
    handlerType: "app-router",
  },
);

export { handler as GET, handler as POST, handler as PUT, handler as PATCH, handler as DELETE };

```

### ts-rest version

"@ts-rest/core": "^3.49.1",
    "@ts-rest/react-query": "^3.49.1",
    "@ts-rest/serverless": "^3.49.1",

**Comment by Gabrola** [comment]
Oh wow! I was just about to commit a refactor for our build process, but without releasing a change. I had no idea `@ts-rest/serverless` was broken, but luckily the refactor fixes this problem.

Thanks for reporting!
