### ISSUE TITLE
Better package name

### ISSUE THREAD

**Issue by fortezhuo** [ts-rest/ts-rest#658]
**Is your feature request related to a problem? Please describe.**
Sorry for silly request, but several days I spend to search about ts-rest
I think "ts-rest"  is so difficult to search for finding boilerplate / template on github. When I search "ts-rest" on github. So many repo filtered out but not contain package "ts-rest"

![image](https://github.com/user-attachments/assets/bae8ba0e-6817-46c4-adb1-9d3cc9893c4a)

**Describe the solution you'd like**
Better and eye catching name that not contain only "ts" and "rest"

**Comment by Gabrola** [comment]
On the surface, it sounds like a silly request indeed, but a valid point nonetheless.

I don't think we have any plans nor the resources to rebrand any time soon, but this SEO problem will be taken into consideration.

Closing as it is not a functionality issue or request.
