### ISSUE TITLE
React Query V5 throws error in expo

### ISSUE THREAD

**Issue by shawnmclean** [ts-rest/ts-rest#664]
### Describe the bug

In an expo project, when you import

```
import { initTsrReactQuery } from "@ts-rest/react-query/v5";
```

Building with expo/metro throws the following:

```
@ts-rest/react-query/v5 could not be found within the project or in these directories:
│   node_modules
│   ../../node_modules
│   node_modules
│   ../../node_modules
```
The v4 method doesn't throw this issue.
This v5 method also works on nextjs.

Here is the CI build error: https://github.com/shawnmclean/sovoli/actions/runs/10273028512/job/28426580490#step:7:70

### How to reproduce

Try to implement it in an expo project.

I tried it in another smaller expo project here: https://github.com/byCedric/expo-monorepo-example/pull/128

### Expected behavior

Should not throw build/compile time modules error.

### Code reproduction

NA

### ts-rest version

  "@ts-rest/core": 3.49.3
  "@ts-rest/open-api": 3.49.3
  "@ts-rest/react-query": 3.49.3
  "@ts-rest/serverless": 3.49.3

**Comment by thenbe** [comment]
Could be similar to https://github.com/honojs/hono/issues/1773

**Comment by Gabrola** [comment]
I hate the metro bundler with every inch of my being; it is so behind on modern JS standards.

@shawnmclean I can't test this at the moment, but try this instead.

```typescript
const { initTsrReactQuery } = require("@ts-rest/react-query/v5.cjs") as typeof import("@ts-rest/react-query/v5");
```

I'll see if there's something simple we can do to make it work without needing to enable package exports in the metro config. However, I will not bend over backwards to make it happen. Closing as this is on metro for not adopting a standard that was introduced back in 2019 in node v12!

**Comment by waraness99** [comment]
This workaround doesn't work anymore with Expo 52 with the `reactServerFunctions` experiment on.
