### ISSUE TITLE
String attributes are wrapped in double quotes when using content-type multipart/form-data

### ISSUE THREAD

**Issue by VictorienDruon** [ts-rest/ts-rest#665]
### Describe the bug

I've followed the [file uploading doc](https://ts-rest.com/docs/core/form-data) but when i've tried to send a string attribute along my file i've noticed it has been wrapped in double quotes.

<img width="508" alt="image" src="https://github.com/user-attachments/assets/b3ed5c90-5f27-4d9e-b666-d6856b47cfcc">

I only have this bug when using the react query client. It works as expected on swagger.

### How to reproduce

Follow the [file uploading doc](https://ts-rest.com/docs/core/form-data) and try to send a string attribute in the body with the react query client.

### Code reproduction

**contract**
```ts
signUp: {
      method: 'POST',
      path: '/sign-up',
      contentType: 'multipart/form-data',
      body: z.object({
          email: z.string().email(),
          name: z.string(),
          avatar: z.custom<File>().nullish(),
      });,
      responses: {
        201: z.object({
          accessToken: AccessToken,
        }),
        409: ConflictErrorBody,
      },
      summary: 'Sign up',
    },
```

**client**
```ts
export const apiClient = initTsrReactQuery(api, {
    baseUrl,
    credentials: 'include',
    jsonQuery: true,
    validateResponse: true,
    throwOnUnknownStatus: true,
    baseHeaders,
})
```

**form**
```ts
  const mutation = apiClient.auth.signUp.useMutation();

  const onSubmit = () =>
    mutation.mutate({ body: { email, name, avatar } })
  );
```

**nest controller**
```ts
  @TsRestHandler(api.auth.signUp)
  @UseInterceptors(FileInterceptor('avatar'))
  async signUp(
    @Res({ passthrough: true }) res: Response,
    @UploadedFile(
      new ParseFilePipeBuilder()
        .addFileTypeValidator({ fileType: 'jpeg' })
        .addMaxSizeValidator({ maxSize: 1000 })
        .build({ fileIsRequired: false })
    )
    avatar: Express.Multer.File,
    @I18n() locale: I18nContext
  ) {
    return tsRestHandler(api.auth.signUp, async ({ body: { email, name } }) => {
        const user = await this.usersService.create({ email, name, avatar });
        const { accessToken, refreshToken } =
          await this.authService.createSession(user);
        this.authService.setRefreshTokenCookie(res, refreshToken);
        return { status: 201, body: { accessToken } };
    });
  }
```

### ts-rest version

    "@ts-rest/core": "^3.49.3",
    "@ts-rest/nest": "^3.49.3",
    "@ts-rest/open-api": "^3.49.3",
    "@ts-rest/react-query": "^3.49.3",

**Comment by Gabrola** [comment]
Seems like it's intended because there's no other way to encode non-string values, but the corresponding server functionality was not developed to parse the JSON. For now you can work around this by constructing your own `FormData` object and passing it to the `body` parameter.

```typescript
mutation.mutate({ body: formData })
```

**Comment by VictorienDruon** [comment]
Thanks @Gabrola  your workaround did the job. Here's the modified onSubmit:
```ts
  const onSubmit = form.handleSubmit(({ name }) => {
    const formData = new FormData();
    formData.append('email', email);
    formData.append('name', name);
    if (avatar) formData.append('avatar', avatar);
    mutation.mutate({ body: formData });
  });
```
