### ISSUE TITLE
Unable to extend request object in `tsr.router`

### ISSUE THREAD

**Issue by namukang** [ts-rest/ts-rest#668]
### Describe the bug

I'm getting a type error when I try to add back in the extended part of the request object in the generics of the tsr.router function for `@ts-rest/serverless` following the instructions from https://ts-rest.com/docs/serverless/routers

### Code reproduction

Minimal repro:

```typescript
import { initContract } from "@ts-rest/core";
import { tsr } from "@ts-rest/serverless/next";

const c = initContract();
const testContract = c.router({
  test: {
    method: "GET",
    path: "/test",
    responses: {
      200: z.object({
        success: z.boolean(),
      }),
    },
  },
});

// `testId` is added to the request via middleware in the handler

// With generic
const testRouter = tsr.router<{ testId: string }>(testContract, {
  test: // <-- Error due to `test` being of type `never`
    async ({}, { request }) => {
      const { testId } = request;
      console.log(testId);
      return {
        status: 200,
        body: { success: true },
      };
    },
});

// Without generic
const testRouter2 = tsr.router(testContract, {
  test: async ({}, { request }) => {
    const { testId } = request; // <-- Error due to `testId` not being defined on `request`
    console.log(testId);
    return {
      status: 200,
      body: { success: true },
    };
  },
});
```

### Expected behavior

The expected behavior is that I'm able to add the generic without the routes having type `never`.

### Actual behavior

When the generic is added to `tsr.router<{ testId: string }>`, all the routes have type `never`.

(Error on test in testRouter: `Type '({}: {}, { request }: { request: any; }) => Promise<{ status: 200; body: { success: boolean; }; }>' is not assignable to type 'never'.ts(2322)`)

When the generic is removed, the routes have no error, but testId is no longer able to be type inferred from request.

### ts-rest version

3.49.3

**Comment by Gabrola** [comment]
@namukang ah, you're right. You need to pass `tsr.router<{ testId: string }, typeof testContract>` to make it work. Need to make sure that generic is mandatory.

However, check out the new router builder, it should make extending the request much easier. It's not documented yet, but you can find various examples here https://github.com/ts-rest/ts-rest/blob/ff7b46de6c1a264ec9c06daf003b8d16912e812a/libs/ts-rest/serverless/src/lib/handlers/ts-rest-fetch.spec.ts#L75-L79

**Comment by namukang** [comment]
@Gabrola Thanks for the quick fix! I'll also check out the new router builder — thanks for the pointer 😎
