### ISSUE TITLE
req.query not being parsed

### ISSUE THREAD

**Issue by maximilianschmitt** [ts-rest/ts-rest#677]
### Describe the bug

If I provide the following query schema:

```
const querySchema = z.object({ custom: z.boolean({ coerce: true }).optional() });
```

and I call my endpoint with query parameters `?custom=true`, I expect `req.query` in the handler to be `{ custom: true }`. Instead, I receive `{ custom: "true" }` (note that `custom` is now a string). I can even provide `?hello=world` and `hello` won't get stripped from `req.query`.

### Step 1

Install the following dependencies:

```
{
    "express": "^4.17.3",
    "@ts-rest/core": "^3.50.0",
    "@ts-rest/express": "^3.50.0",
    "@ts-rest/open-api": "^3.50.0"
}
```

### Step 2

Create `server.ts`:

```ts
import express from "express";
import { initContract } from "@ts-rest/core";
import { createExpressEndpoints, initServer } from "@ts-rest/express";
import { z } from "zod";

const querySchema = z.object({ custom: z.boolean({ coerce: true }).optional() });

const s = initServer(),
      c = initContract();

const indexContract = c.query({
  method: "GET",
  path: "/",
  query: querySchema,
  responses: { 200: querySchema },
  summary: "Get broadcaster commands"
});

const indexRoute = s.route(indexContract, {
  handler: async ({ req }) => ({
    status: 200,
    body: req.query
  })
});

export const contract = c.router({ index: indexContract }),
      router = s.router(contract, { index: indexRoute });

const app = express();

createExpressEndpoints(contract, router, app);

app.listen(3000, () => {
  console.log("Server started on http://localhost:3000");
});
```

### Step 3

Run the server:

```
npx tsx server.ts
```

### Step 4

Call the endpoint:

```
$ curl localhost:3000?hello=world
{"hello":"world"}          // ❌ Expecting {} (empty object)

$ curl localhost:3000?custom=true
{"custom":"true"}        // ❌ Expecting { "custom": true } (custom should be boolean, not string)
```

### Expected behavior

See "How to reproduce"

### Code reproduction

See "How to reproduce"

### ts-rest version

See "How to reproduce"

**Comment by Gabrola** [comment]
`req.query` contains express's raw query parameters not the validated query. Your handler lines should be `handler: async ({ query }) => ({`

**Comment by maximilianschmitt** [comment]
@Gabrola Thanks for the quick response. I completely missed that I need to take `query` from ts-rest's context. Thank you!
