### ISSUE TITLE
Swagger UI display twice sub-sub-contract routes

### ISSUE THREAD

**Issue by VictorienDruon** [ts-rest/ts-rest#680]
### Describe the bug

I have combined my contracts in one single contract as described in the [doc](https://ts-rest.com/docs/core/#combining-contracts).

It worked as expected until I tried to combine contracts into what was already a sub-contract.

Everything is working except the **Swagger UI** where sub-sub-contract's routes are displayed twice.

<img width="1268" alt="image" src="https://github.com/user-attachments/assets/3b0bd3f6-b886-4884-b6c2-4f438a4dd934">

### How to reproduce

Combine combined contracts in one single contract.

### Expected behavior

Sub-sub-contract's routes should be displayed only once in Swagger UI, preferably within their parent contract section (here it would be auth).

### Code reproduction

**index.ts**
```ts
export const api = c.router({
    auth,
    users,
    calendars,
    events,
})
```

**auth.ts**
```ts
export const auth = c.router({
    otp,
    sessions,
    signIn: {}
    ...
})
```

**otp.ts**
```ts
export const otp = c.router( {
    send: {},
})

### ts-rest version

    "@ts-rest/core": "^3.49.3",
    "@ts-rest/nest": "^3.49.3",
    "@ts-rest/open-api": "^3.49.3",

**Comment by Gabrola** [comment]
OpenAPI doesn't support nested tags, therefore endpoints marked as `auth` and `otp` will appear twice, once under each tag. If you want to customize this behavior, just run all the endpoints in the OpenAPI document through a loop and remove whatever tags you want. Say you want something like the "Send OTP" to only appear under `otp`, then just check any endpoints that have more than one tag and remove all tags except the last one in the array.

**Comment by VictorienDruon** [comment]
Okay I see thank you for your help !
Here's what I ended up doing:

```ts
import { generateOpenApi } from '@ts-rest/open-api';
import type {
  PathsObject,
  OperationObject,
} from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

function isOperationObject(value: unknown): value is OperationObject {
  return typeof value === 'object' && value !== null && 'tags' in value;
}

const document = generateOpenApi(api, config);

document.paths = Object.entries(document.paths).reduce<PathsObject>(
  (paths, [path, definition]) => {
    paths[path] = Object.entries(definition).reduce<Record<string, unknown>>(
      (newDefinition, [key, value]) => {
        if (isOperationObject(value))
          // Limit tags to 1 so sub-sub-routes are gathered under the parent router
          newDefinition[key] = { ...value, tags: value.tags?.slice(0, 1) };
        else newDefinition[key] = value;
        return newDefinition;
      },
      {},
    );
    return paths;
  },
  {},
);
```

**Comment by VictorienDruon** [comment]
Okay I see thank you for your help !
Here's what I ended up doing:

```ts
import { generateOpenApi } from '@ts-rest/open-api';
import type {
  PathsObject,
  OperationObject,
} from '@nestjs/swagger/dist/interfaces/open-api-spec.interface';

function isOperationObject(value: unknown): value is OperationObject {
  return typeof value === 'object' && value !== null && 'tags' in value;
}

const document = generateOpenApi(api, config);

document.paths = Object.entries(document.paths).reduce<PathsObject>(
  (paths, [path, definition]) => {
    paths[path] = Object.entries(definition).reduce<Record<string, unknown>>(
      (newDefinition, [key, value]) => {
        if (isOperationObject(value))
          // Limit tags to 1 so sub-sub-routes are gathered under the parent router
          newDefinition[key] = { ...value, tags: value.tags?.slice(0, 1) };
        else newDefinition[key] = value;
        return newDefinition;
      },
      {},
    );
    return paths;
  },
  {},
);
```

**Comment by Gabrola** [comment]
@VictorienDruon Great, thanks for sharing your solution!
