### ISSUE TITLE
ts-rest.com: fonts are broken in a couple of places

### ISSUE THREAD

**Issue by angusjf** [ts-rest/ts-rest#69]
<img width="722" alt="Screenshot 2022-10-16 at 09 59 56" src="https://user-images.githubusercontent.com/8879326/196027158-92c28892-5751-46cc-8a9c-b8037f461ea4.png">

`serif -> font-family="Virgil, Segoe UI Emoji"`

This one should be easy, I guess the font just isn't linked properly / needs a better fallback

<img width="355" alt="Screenshot 2022-10-16 at 09 59 51" src="https://user-images.githubusercontent.com/8879326/196027164-94490ce7-f384-4d0a-bdac-ac7140052185.png">

`monospace -> style="font-family:'HackNerdFontComplete-Bold', 'Hack Nerd Font', monospace`

This one is harder, embedded svg so the font should probs just be a path. not even God knows how to make svgs

**Comment by oliverbutler** [comment]
It was easier to rebrand than deal with svgs lol
