### ISSUE TITLE
@Api decorator not working properly with nest versioning 

### ISSUE THREAD

**Issue by PedroFonseca17** [ts-rest/ts-rest#70]
Hey guys! 
I'm having some issues when creating an endpoint on nestjs + ts-rest that receives a param and has versioning configured by nest have you guys ever faced these issues?

Example: 

Contract route
```ts
 getIndustryTag: {
    method: 'GET',
    path: `/industry-tags/:uid`,
    responses: {
      200: ResponseIndustryTagModel.nullable(),
    },
    summary: 'Get an industry tag',
  },
```
  
  
  Controller
  ```ts
  @Controller({
    version: '1',
  })
  export class IndustryTagsController {
    constructor(private readonly industryTagsService: IndustryTagsService) {}
  
    @Api(server.route.getIndustryTag)
    async findOne(
      @ApiDecorator() { params: { uid } }: RouteShape['getIndustryTag']
    ) {  
          ....
      }
```

The end route for this would be `http://localhost:3000/v1/industry-tags/uid-123` but since the contract route doesn't know about the versioning that was applied, I receive the string `industry-tags` has the param instead of the `uid-123`

Even if I apply the v1 to the contract path it will become `v1/v1/industry-tags` so it wouldn't help either

The only solution I can see working is managing the versioning inside the contract only and letting go of the nestjs versioning system, but I wanted to know if there are other options for this and if this is a known issue

Thanks!

**Comment by oliverbutler** [comment]
This is a super interesting point, we can definitely work on this, the root problem here is that ts-rest is trying to instantiate the path for you, to avoid typos and improve dev x.

Out of interest, would this also work by adding "/v1" to your baseUrl when you call this api?

Or is having the ability to add /v1/.. in the contract important?

**Comment by PedroFonseca17** [comment]
I believe that adding the version to the contract (whole contract and endpoint specific) would be the best approach.
This way, if you are trying to achieve a full type-safety project with API and frontend both of them will know which version of the endpoint they are using just by accessing the contracts information.


So maybe something like this would work:

```
contract.router({
  version: '2':
  getIndustryTag: {
      method: 'GET',
      path: `/industry-tags/:uid`,
      responses: {
        200: ResponseIndustryTagModel.nullable(),
      },
      summary: 'Get an industry tag',
      version: '1'
  },
)}
```

What do you think?

**Comment by oliverbutler** [comment]
I've been playing with this locally for a while, and seeing how it's played out in reality.

One issue we might face is if we add "version" to the contract, not all versioning across frameworks, or even the same framework will be consistent

Some APIs may have one of the following
- A path like /vX/...
- A path like /version-X/...
- A versioning header

I'm not entirely sure if we want to work around this, in the worst case, for your use case I imagine in the front end you could postfix the baseUrl with "/v1"? Honestly, I'm not sure about this one, so I'm happy to implement something if we can agree on a solution

**Comment by oliverbutler** [comment]
Related to #79, happy to hear you both out for suggestions on implementation here. 

@Gabrola have you considered this whilst looking at the Nest implementation at all?

**Comment by oliverbutler** [comment]
@PedroFonseca17, since you submitted this issue has any other workaround helped, or is this still something you'd want from ts-rest?

**Comment by oliverbutler** [comment]
For now, closing as "won't fix", but let's loop back around to this, especially for the 4.0 release.

**Comment by oliverbutler** [comment]
For now, closing as "won't fix", but let's loop back around to this, especially for the 4.0 release.

**Comment by LeulAria** [comment]
nest js support is too bad actually

**Comment by LeulAria** [comment]
nest js support is bad

**Comment by LeulAria** [comment]
so when is v4.0 planned ?

would expect some thing better for nest js integration it should have been easy specially for nest js as it embrases abstraction
