### ISSUE TITLE
Feature request - query adapter support (vue)

### ISSUE THREAD

**Issue by reslear** [ts-rest/ts-rest#71]
add use query adapters support for example vue - https://tanstack.com/query/v4/docs/adapters/vue-query

**Comment by oliverbutler** [comment]
Out of all of the tanstack adapters Vue is my least familiar! I'm more than happy to assist with the creation of an adapter if you want to work on this with me.

From attempting solid-query adapter it was mostly copy/paste while changing some of the names

**Comment by dzcpy** [comment]
Any updates?

**Comment by oliverbutler** [comment]
Happy to assist anyone who wants to take this on :)

**Comment by Jwcode-uk** [comment]
Hi, happy to pick this up this issue and begin work :)
