### ISSUE TITLE
Error handling in Express server

### ISSUE THREAD

**Issue by netiperher** [ts-rest/ts-rest#72]
Today when using the `createExpressEndpoints` it will wrap all route handlers in a 
```
     try {
     ...
     } catch (e) {
      console.error(`[ts-rest] Error on ${method} ${schema.path}`, e);
      return res.status(500).send('Internal Server Error');
    }
```
making it difficult to use any kind of error handling middleware in Express.

Would it be an option to just remove this handling completely and simply let Express take care of forwarding the error to next handler/middleware?

**Comment by oliverbutler** [comment]
Hey @netiperher, this is a great point, I wonder if just removing the try/catch entirely should solve this for you?
