### ISSUE TITLE
Make it so only the response codes defined in the contract can be returned in route handlers

### ISSUE THREAD

**Issue by greatsolace** [ts-rest/ts-rest#723]
**Is your feature request related to a problem? Please describe.**
You can mistakenly return a response code that isn't defined in the contract, and this won't be caught at compile time. For example, here I define the contract so `getPost` is expected to return a `200` response. However, in the route handler I am allowed to return a random `300` response without triggering a compile error.

```ts
const PostSchema = z.object({
  id: z.string(),
  title: z.string(),
  body: z.string(),
});

const contract = c.router({
  getPost: {
    method: 'GET',
    path: `/post`,
    responses: {
      200: PostSchema
    },
  },
});

const s = initServer();
const r = s.router(contract, {
  getPost: async () => {
    // I can return a status code that wasn't defined in the contract
    return {
      status: 300,
      body: {
        msg: 'random garbage',
      },
    };
  },
});
```

**Describe the solution you'd like**
Type-checking to ensure only response codes defined in the contract can be returned in route handlers.

**Comment by ArnoldVanN** [comment]
Thats expected behavior:
https://ts-rest.com/docs/core/#strict-response-status-codes
