### ISSUE TITLE
Code in docs is centered for some reason

### ISSUE THREAD

**Issue by WildlandHerald** [ts-rest/ts-rest#74]
https://ts-rest.com/docs/quickstart?utm_source=github&utm_medium=documentation&utm_campaign=readme
![image](https://user-images.githubusercontent.com/82415295/203001045-048f0438-0ced-4181-b316-2d7a23683b28.png)

**Comment by oliverbutler** [comment]
I've occasionally spotted this, but yup you're 100% right.

I just realised the CI was doing a recursive S3 copy rather than a sync, potentially some of the built files were weirdly affected after a few deploys, I'll try address it and see if that works - I've never noticed this locally

**Comment by oliverbutler** [comment]
@WildlandHerald I believe this is fixed, _please_ can you check if that page is fixed?

**Comment by WildlandHerald** [comment]
> @WildlandHerald I believe this is fixed, _please_ can you check if that page is fixed?

Sorry for not answering so long, I had quite a busy week. The problem is not fixed for me. I did provide a link to the broken page in my original post.
