### ISSUE TITLE
Unnecessarily requiring args for a GET request

### ISSUE THREAD

**Issue by miguellteixeira** [ts-rest/ts-rest#77]
First of all, congrats on building such a cool library! 🙌 

It seems I've stumbled upon an unwanted behaviour, when calling a client router method that simply does a GET request without any required parameters:

<img width="80%" src="https://cdn-std.droplr.net/files/acc_683877/6gSTOL"/>

I might be missing something, but it seems that the root cause is in the `DataReturn` type that's being applied where the `args` parameter is never optional:

```typescript
// ts-rest/libs/ts-rest/core/src/lib/client.ts

/**
 * Returned from a mutation or query call
 */
export type DataReturn<TRoute extends AppRoute> = (
  args: Without<DataReturnArgs<TRoute>, never>
) => Promise<ApiRouteResponse<TRoute['responses']>>;
```

**1 - Could we make `args` optional for "query calls" where there aren't any required path parameters?**

<br>

Also, if the query property is specified on the contract:

```typescript
const c = initContract();

export const contract = c.router({
  getMembers: {
    method: 'GET',
    path: 'members',
    responses: {
      200: c.response<{ members: Member[]; total: number }>(),
    },
    query: z.object({
      take: z.string().transform(Number).optional(),
      skip: z.string().transform(Number).optional(),
      search: z.string().optional(),
    }),
    summary: 'Get all members',
  },
});
```

It seems to become required on the client:

<img width="80%" src="https://cdn-std.droplr.net/files/acc_683877/INL0kH"/>

**2 - Could we make query params optional?**

**Comment by oliverbutler** [comment]
Having a look at this, the difficulty is allowing this second argument to be optional, only if everything inside the DataReturnObject is empty, taking a look.

<img width="725" alt="Screenshot 2022-12-05 at 09 42 32" src="https://user-images.githubusercontent.com/47489826/205604951-e5e64ce9-2f19-4af9-a08a-e478ab4e9762.png">

**Comment by oliverbutler** [comment]
@miguellteixeira, I spent a while looking for a generic which should accomplish this behaviour, I ran out of time to figure something out

Any ideas on how we'd go about doing this? Maybe I'll tweet @mattpocock this little challenge 🪄 😆

**Comment by mattpocock** [comment]
Send me a TS playground and I'll see what I can do!

**Comment by oliverbutler** [comment]
Funnily enough I found a solution whilst working on a new Query Client API.

**Comment by oliverbutler** [comment]
Funnily enough @mattpocock I found a solution whilst working on a new Query Client (ts-rest v4 👀 ) implementation!

https://www.typescriptlang.org/play?ts=4.9.3#code/C4TwDgpgBAggNnA8mYBLA9gOwIZygXigG8BYAKCkqmwC4oBXTAEwgDNVMImAacqqAEYB+OgGdgAJw4BzcgF9y5UJCgA5dMHhIUGHHkKkKVWlHFTMssgrLkIADzDoJwKMugwJELQAUJ6SM6oEKLIaFi4ADwAKgB8BMR8UADaANJQHFAA1hAg6KxQUQC6ALQiDMxsHFxQ9sAQzKIFqYVQQq4S9NB0rLiiEADc8knZuflFNXZ1De2diW2Ss0bdvQOKNmRuUADKABbo9HBMAEIQUR3QhB5eCL7+EIHBobqRWk-hcDFK4NC7+4cnADEVvErj4-AE0I8dO8IupNAg3noYkA

Super interesting problem, thanks for reaching out, this one stumped me momentarily until I realised we should look at the values, as a union, for every in in an object, then for those, check if undefined is a part of the union.

One thing I'm unsure on, why does `undefined extends T[K] ? true : false`, differ from `T[K] extends undefined ? true : false`... 🤔

**Comment by mattpocock** [comment]
`Dog extends Animal` means 'is every dog an animal'

`Animal extends Dog` means 'is every animal a dog'

Hopefully that rather cryptic answer helps!

**Comment by oliverbutler** [comment]
@miguellteixeira, we've got a working solution to improve this, I may hang off until V4, as there may be some breaking changes. I really wanted to make a code mod to adjust contracts/client implementations for V4... Hoping for a beta release this week!

**Comment by oliverbutler** [comment]
https://github.com/ts-rest/ts-rest/discussions/41 <- relevant

**Comment by miguellteixeira** [comment]
Thank you @oliverbutler, really appreciate it! 🙌

**Comment by oliverbutler** [comment]
I found a way to do this, non breaking, without a major version bump. I'll try push it though today @miguellteixeira  :)
