### ISSUE TITLE
@ApiDecorator retrieves wrong params in Nest

### ISSUE THREAD

**Issue by franckdsf** [ts-rest/ts-rest#79]
Hey, I've been using ts-rest for a few days and find it extremely well made!
But I have quite a big issue.

@ApiDecorator is not working properly.

When hitting ``/media/:id`` with like ``/media/some-id``
it returns ``media`` instead of ``some-id``

```ts
// .............

const m = initContract();

const mediaContract = m.router({
// ..........
  getMedia: {
    method: 'GET',
    path: '/:id',
    responses: { 200: m.response<any>(), },
    summary: 'get a media',
  },
})

const c = initContract();

export const contract = c.router({
 //..........
  media: mediaContract,
});

const s = initRouteContract(contract.media);
type ControllerShape = typeof s.controllerShape;
type RouteShape = typeof s.routeShapes;

@Controller('media')
export class MediaController implements ControllerShape {
  @Api(s.route.getMedia)
  async getMedia(@ApiDecorator() { params: { id } }: RouteShape['getMedia']) { 
    return id; // returns "media" instead of the ID
  }
}
```

Please provide an hotfix, I can't use the library anymore for now... because of this bug

EDIT : WORKAROUND FOR NOW :  use the native @Param from NestJS :
```ts
@Api(s.route.getMedia)
// async getMedia(@ApiDecorator() { params: { id } }: RouteShape['getMedia']) {
async getMedia(@Param('id') id: string) {
  return id; // returns "some-id" correctly
}
```

**Comment by oliverbutler** [comment]
Hey @franckdsf, thanks for the bug report, this is pretty foundational so I'll investigate ASAP.

**Comment by oliverbutler** [comment]
Ah! @franckdsf just realised, maybe the docs are lacking here, but the "path" property must be the _full_ path, at least given ts-rest's current implementation.

We've been discussing this in another issue, but right now ts-rest ignores the controllers prefix, or any global prefix, we could do a feature and a codemod to improve this though!

```typescript
const mediaContract = m.router({
// ..........
  getMedia: {
    method: 'GET',
    path: '/media/:id',
    responses: { 200: m.response<any>(), },
    summary: 'get a media',
  },
})
```

If you look in your console when you spin up the Nest dev server, you may notice currently the path "/:id" is created, rather than "/media/:id" as you'd expect.


For a bit more context here, initially when adding Nest support for the lib, I wasn't 100% how to (type safely) use the version and controller prefix 🤔

**Comment by franckdsf** [comment]
Hey @oliverbutler,
It is still not working. My implementation correctly init the server with  :
```bash
[Nest] 42668  - 10/12/2022, 14:24:17     LOG [RouterExplorer] Mapped {/media/:id, GET} route +2ms
```

And when replacing by ``  path: '/media/:id', ```, It creates the following route.

```bash
[Nest] 42668  - 10/12/2022, 14:24:17     LOG [RouterExplorer] Mapped {/media/media/:id, GET} route +2ms
```

Also when querying this route, it still doesn't get the good param

```ts
@Api(s.route.getMedia)
async getMedia(@ApiDecorator() { params: { id } }: RouteShape['getMedia']) {
  console.log(id); // logs "media"
 }
    ```

**Comment by oliverbutler** [comment]
Interesting, does this happen even when you remove the path from the controller? @Controller(), maybe they get appended to each other incorrectly.. 

If not could you send over a super simple reproduction please? Maybe stackblitz or code sandbox, or even a repo?

**Comment by franckdsf** [comment]
It **does** work when removing the path from the controller and prepending my routes with "/media/".
But It makes the whole ts-rest/nestjs experience different.

I found 4 possible approches : 
```ts
const mediaContract = m.router({
  path: "media", // reserved name
// ..........
  getMedia: {
    method: 'GET',
    path: '/:id',
    responses: { 200: m.response<any>(), },
    summary: 'get a media',
  },
})
```

```ts
export const contract = c.router({
  media: mediaContract,
});
// making it that it automatically preprends mediaContract routes with "media"
```

```ts
const path = "media";
export const contract = c.router({
  media: (path) => mediaContract,
});
// making it possible to use a function that preprends the path
```

I'll work on a reproduction.

**Comment by franckdsf** [comment]
@oliverbutler I didn't implement the front-end yet but faced an issue when working with the controller path like I did.

```ts
s.route.getMedia.path // returns "/:id"
```
Whenthe actual path is ``/media/:id`` (because the controller preprends /media to the path). ts-rest can't know there will be a preprended path during compilation time, so it's better to not work with @Controller(path) at all.

The best solution is to make it possible to preprend the path during instantiation, and I find this way the best :
```ts
const path = "media";
export const contract = c.router({
  media: ({path}) => mediaContract,
});
// making it possible to use a function that preprends the path
```
