### ISSUE TITLE
@ApiDecorator() types properties as optional when zod schema defines them as required

### ISSUE THREAD

**Issue by JarvisPrestidge** [ts-rest/ts-rest#98]
Hi 👋 really interesting lib and love the integration with nestjs <3

I'm having issues with the `@ApiDecorator()` typing my zod schema as optional for all the properties. Maybe I'm not understanding correctly, but I assumed that zod was being used to validate those fields and therefore they would always be available to the controller (unless there was a validation error).

My schema looks like this:

![image](https://user-images.githubusercontent.com/6669336/206929390-e1cc5fd8-fbf4-40b9-8e94-76b43db73123.png)

And my nest controller route looks like this:

![image](https://user-images.githubusercontent.com/6669336/206929256-e8782bf4-0e87-46cb-b1ce-b0dd609da7c1.png)

These values being optional obviously break my typing when passing down to the service etc. 

Is this expected, or am I doing something wrong? Cheers again 🙇

**Comment by oliverbutler** [comment]
Hey @JarvisPrestidge, this is super interesting, yeah these should be typed as non-optional, can you show me your contract? Also I'm pretty sure the runtime Zod validation won't work without the @Api wrapper (instead of @Post("signup"))!

**Comment by Gabrola** [comment]
@JarvisPrestidge in addition to what Olly mentioned, I'm guessing you are not using strict mode in your tsconfig.json, not doing that will make all zod schema fields optional. You must enable `strict` mode in your `tsconfig.json` and make sure your are not explicitly disabling `strictNullChecks`

See https://github.com/colinhacks/zod#requirements

**Comment by JarvisPrestidge** [comment]
Hey @Gabrola, I didn't know about the zod requirements, turning on `strict` gets those values passed as required.

I'm still having some other unrelated issues. Have you guys considered starting a community discord, so people can ask more general questions?

**Comment by oliverbutler** [comment]
@JarvisPrestidge , I was considering a discord (or equivalent) community, wasn't 100% sure if we had the volume requirement to make it worth it, but maybe we're getting there...
